/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_ASDU_PY_H_
#define	_ASDU_PY_H_


#include <ASDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <UtcTime_Py.h>
#include <Data_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ASDU */
PyCompat_DEF_STRUCT(ASDU);
PyCompat_DEF_TYPE(ASDU);
PyCompat_DEF_ENUM(ASDU_smpSynch);
PyCompat_DEF_ENUM(ASDU_smpMod);

/* Type Converters */
int PyAsnASDU_FromPython(PyObject *pObj, ASDU_t *pDst);
PyObject *PyAsnASDU_ToPython(ASDU_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnASDU_ModSetupTypes(void);
void PyAsnASDU_ModClear(PyObject *);
int PyAsnASDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ASDU_PY_H_ */
