/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_ASDU_H_
#define	_ASDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NativeInteger.h>
#include "UtcTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASDU__smpSynch {
	ASDU__smpSynch_none	= 0,
	ASDU__smpSynch_local	= 1,
	ASDU__smpSynch_global	= 2
} e_ASDU__smpSynch;
typedef enum ASDU__smpMod {
	ASDU__smpMod_samplesPerNormalPeriod	= 0,
	ASDU__smpMod_samplesPerSecond	= 1,
	ASDU__smpMod_secondsPerSample	= 2
} e_ASDU__smpMod;

/* Forward declarations */
struct Data;

/* ASDU */
typedef struct ASDU {
	VisibleString_t	 svID;
	VisibleString_t	*datSet;	/* OPTIONAL */
	long	 smpCnt;
	unsigned long	 confRev;
	UtcTime_t	*refrTm;	/* OPTIONAL */
	long	*smpSynch;	/* OPTIONAL */
	long	*smpRate;	/* OPTIONAL */
	struct Data	*seqData;
	long	*smpMod;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASDU_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_confRev_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASDU;
extern asn_SEQUENCE_specifics_t asn_SPC_ASDU_specs_1;
extern asn_TYPE_member_t asn_MBR_ASDU_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _ASDU_H_ */
#include <asn_internal.h>
