/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_ErrorReason_PY_H_
#define	_ErrorReason_PY_H_


#include <ErrorReason.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ErrorReason */
PyCompat_DEF_STRUCT(ErrorReason);
PyCompat_DEF_TYPE(ErrorReason);
PyCompat_DEF_ENUM(ErrorReason);

/* Type Converters */
static inline int PyAsnErrorReason_FromPython(PyObject *pObj, ErrorReason_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(ErrorReason, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnErrorReason_ToPython(ErrorReason_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumErrorReason_Type, *pSrc);
}

/* Module Initializers */
int PyAsnErrorReason_ModSetupTypes(void);
void PyAsnErrorReason_ModClear(PyObject *);
int PyAsnErrorReason_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ErrorReason_PY_H_ */
