/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GetElementRequestPdu_H_
#define	_GetElementRequestPdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetElementRequestPdu */
typedef struct GetElementRequestPdu {
	VisibleString_t	 ident;
	struct GetElementRequestPdu__references {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} references;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetElementRequestPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetElementRequestPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_GetElementRequestPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_GetElementRequestPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GetElementRequestPdu_H_ */
#include <asn_internal.h>
