/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GetElementRequestPdu_PY_H_
#define	_GetElementRequestPdu_PY_H_


#include <GetElementRequestPdu.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetElementRequestPdu */
typedef struct GetElementRequestPdu__references GetElementRequestPdu_references_ANON_3_t;
PyCompat_DEF_STRUCT(GetElementRequestPdu_references_ANON_3);
PyCompat_DEF_TYPE(GetElementRequestPdu_references_ANON_3);
PyCompat_DEF_STRUCT(GetElementRequestPdu);
PyCompat_DEF_TYPE(GetElementRequestPdu);

/* Type Converters */
int PyAsnGetElementRequestPdu_references_ANON_3_FromPython(PyObject *pObj, GetElementRequestPdu_references_ANON_3_t *pDst);
PyObject *PyAsnGetElementRequestPdu_references_ANON_3_ToPython(GetElementRequestPdu_references_ANON_3_t *pSrc, PyObject *parent);
int PyAsnGetElementRequestPdu_FromPython(PyObject *pObj, GetElementRequestPdu_t *pDst);
PyObject *PyAsnGetElementRequestPdu_ToPython(GetElementRequestPdu_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetElementRequestPdu_ModSetupTypes(void);
void PyAsnGetElementRequestPdu_ModClear(PyObject *);
int PyAsnGetElementRequestPdu_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetElementRequestPdu_PY_H_ */
