/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GetReferenceRequestPdu_H_
#define	_GetReferenceRequestPdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetReferenceRequestPdu */
typedef struct GetReferenceRequestPdu {
	VisibleString_t	 ident;
	struct GetReferenceRequestPdu__offset {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offset;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetReferenceRequestPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetReferenceRequestPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_GetReferenceRequestPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_GetReferenceRequestPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GetReferenceRequestPdu_H_ */
#include <asn_internal.h>
