/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GlbErrors_PY_H_
#define	_GlbErrors_PY_H_


#include <GlbErrors.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GlbErrors */
PyCompat_DEF_STRUCT(GlbErrors);
PyCompat_DEF_TYPE(GlbErrors);
PyCompat_DEF_ENUM(GlbErrors);

/* Type Converters */
static inline int PyAsnGlbErrors_FromPython(PyObject *pObj, GlbErrors_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(GlbErrors, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnGlbErrors_ToPython(GlbErrors_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumGlbErrors_Type, *pSrc);
}

/* Module Initializers */
int PyAsnGlbErrors_ModSetupTypes(void);
void PyAsnGlbErrors_ModClear(PyObject *);
int PyAsnGlbErrors_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GlbErrors_PY_H_ */
