/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GSEMngtResponses_PY_H_
#define	_GSEMngtResponses_PY_H_


#include <GSEMngtResponses.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <GSEMngtResponsePdu_Py.h>
#include <GSEMngtResponsePdu_Py.h>
#include <GSEMngtResponsePdu_Py.h>
#include <GSEMngtResponsePdu_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GSEMngtResponses */
PyCompat_DEF_STRUCT(GSEMngtResponses);
PyCompat_DEF_TYPE(GSEMngtResponses);
PyCompat_DEF_ENUM(GSEMngtResponses_PRESENT);

/* Type Converters */
int PyAsnGSEMngtResponses_FromPython(PyObject *pObj, GSEMngtResponses_t *pDst);
PyObject *PyAsnGSEMngtResponses_ToPython(GSEMngtResponses_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGSEMngtResponses_ModSetupTypes(void);
void PyAsnGSEMngtResponses_ModClear(PyObject *);
int PyAsnGSEMngtResponses_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GSEMngtResponses_PY_H_ */
