/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GSEMngtPdu_PY_H_
#define	_GSEMngtPdu_PY_H_


#include <GSEMngtPdu.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <GSERequestResponse_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GSEMngtPdu */
PyCompat_DEF_STRUCT(GSEMngtPdu);
PyCompat_DEF_TYPE(GSEMngtPdu);

/* Type Converters */
int PyAsnGSEMngtPdu_FromPython(PyObject *pObj, GSEMngtPdu_t *pDst);
PyObject *PyAsnGSEMngtPdu_ToPython(GSEMngtPdu_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGSEMngtPdu_ModSetupTypes(void);
void PyAsnGSEMngtPdu_ModClear(PyObject *);
int PyAsnGSEMngtPdu_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GSEMngtPdu_PY_H_ */
