/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GSEMngtResponses_H_
#define	_GSEMngtResponses_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GSEMngtResponses_PR {
	GSEMngtResponses_PR_NOTHING,	/* No components present */
	GSEMngtResponses_PR_gseMngtNotSupported,
	GSEMngtResponses_PR_getGoReference,
	GSEMngtResponses_PR_getGOOSEElementNumber,
	GSEMngtResponses_PR_getGsReference,
	GSEMngtResponses_PR_getGSSEDataOffset
} GSEMngtResponses_PR;

/* Forward declarations */
struct GSEMngtResponsePdu;

/* GSEMngtResponses */
typedef struct GSEMngtResponses {
	GSEMngtResponses_PR present;
	union GSEMngtResponses_u {
		NULL_t	 gseMngtNotSupported;
		struct GSEMngtResponsePdu	*getGoReference;
		struct GSEMngtResponsePdu	*getGOOSEElementNumber;
		struct GSEMngtResponsePdu	*getGsReference;
		struct GSEMngtResponsePdu	*getGSSEDataOffset;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GSEMngtResponses_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSEMngtResponses;
extern asn_CHOICE_specifics_t asn_SPC_GSEMngtResponses_specs_1;
extern asn_TYPE_member_t asn_MBR_GSEMngtResponses_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GSEMngtResponsePdu.h"

#endif	/* _GSEMngtResponses_H_ */
#include <asn_internal.h>
