/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GSEMngtRequests_H_
#define	_GSEMngtRequests_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GSEMngtRequests_PR {
	GSEMngtRequests_PR_NOTHING,	/* No components present */
	GSEMngtRequests_PR_getGoReference,
	GSEMngtRequests_PR_getGOOSEElementNumber,
	GSEMngtRequests_PR_getGsReference,
	GSEMngtRequests_PR_getGSSEDataOffset
} GSEMngtRequests_PR;

/* Forward declarations */
struct GetReferenceRequestPdu;
struct GetElementRequestPdu;

/* GSEMngtRequests */
typedef struct GSEMngtRequests {
	GSEMngtRequests_PR present;
	union GSEMngtRequests_u {
		struct GetReferenceRequestPdu	*getGoReference;
		struct GetElementRequestPdu	*getGOOSEElementNumber;
		struct GetReferenceRequestPdu	*getGsReference;
		struct GetElementRequestPdu	*getGSSEDataOffset;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GSEMngtRequests_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSEMngtRequests;
extern asn_CHOICE_specifics_t asn_SPC_GSEMngtRequests_specs_1;
extern asn_TYPE_member_t asn_MBR_GSEMngtRequests_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GetReferenceRequestPdu.h"
#include "GetElementRequestPdu.h"

#endif	/* _GSEMngtRequests_H_ */
#include <asn_internal.h>
