/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GSEMngtPdu_H_
#define	_GSEMngtPdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GSERequestResponse;

/* GSEMngtPdu */
typedef struct GSEMngtPdu {
	long	 stateID;
	struct GSERequestResponse	*requestResp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GSEMngtPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSEMngtPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_GSEMngtPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_GSEMngtPdu_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GSERequestResponse.h"

#endif	/* _GSEMngtPdu_H_ */
#include <asn_internal.h>
