/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_GSERequestResponse_H_
#define	_GSERequestResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GSERequestResponse_PR {
	GSERequestResponse_PR_NOTHING,	/* No components present */
	GSERequestResponse_PR_requests,
	GSERequestResponse_PR_responses
} GSERequestResponse_PR;

/* Forward declarations */
struct GSEMngtRequests;
struct GSEMngtResponses;

/* GSERequestResponse */
typedef struct GSERequestResponse {
	GSERequestResponse_PR present;
	union GSERequestResponse_u {
		struct GSEMngtRequests	*requests;
		struct GSEMngtResponses	*responses;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GSERequestResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GSERequestResponse;
extern asn_CHOICE_specifics_t asn_SPC_GSERequestResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_GSERequestResponse_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GSEMngtRequests.h"
#include "GSEMngtResponses.h"

#endif	/* _GSERequestResponse_H_ */
#include <asn_internal.h>
