/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_IEC61850_Specific_Protocol_H_
#define	_IEC61850_Specific_Protocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IEC61850_Specific_Protocol_PR {
	IEC61850_Specific_Protocol_PR_NOTHING,	/* No components present */
	IEC61850_Specific_Protocol_PR_gseMngtPdu,
	IEC61850_Specific_Protocol_PR_goosePdu
} IEC61850_Specific_Protocol_PR;

/* Forward declarations */
struct GSEMngtPdu;
struct IECGoosePdu;

/* IEC61850-Specific-Protocol */
typedef struct IEC61850_Specific_Protocol {
	IEC61850_Specific_Protocol_PR present;
	union IEC61850_Specific_Protocol_u {
		struct GSEMngtPdu	*gseMngtPdu;
		struct IECGoosePdu	*goosePdu;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IEC61850_Specific_Protocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IEC61850_Specific_Protocol;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GSEMngtPdu.h"
#include "IECGoosePdu.h"

#endif	/* _IEC61850_Specific_Protocol_H_ */
#include <asn_internal.h>
