/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_IECGoosePdu_PY_H_
#define	_IECGoosePdu_PY_H_


#include <IECGoosePdu.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Data_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IECGoosePdu */
typedef struct IECGoosePdu__allData IECGoosePdu_allData_ANON_13_t;
PyCompat_DEF_STRUCT(IECGoosePdu_allData_ANON_13);
PyCompat_DEF_TYPE(IECGoosePdu_allData_ANON_13);
PyCompat_DEF_STRUCT(IECGoosePdu);
PyCompat_DEF_TYPE(IECGoosePdu);

/* Type Converters */
int PyAsnIECGoosePdu_allData_ANON_13_FromPython(PyObject *pObj, IECGoosePdu_allData_ANON_13_t *pDst);
PyObject *PyAsnIECGoosePdu_allData_ANON_13_ToPython(IECGoosePdu_allData_ANON_13_t *pSrc, PyObject *parent);
int PyAsnIECGoosePdu_FromPython(PyObject *pObj, IECGoosePdu_t *pDst);
PyObject *PyAsnIECGoosePdu_ToPython(IECGoosePdu_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnIECGoosePdu_ModSetupTypes(void);
void PyAsnIECGoosePdu_ModClear(PyObject *);
int PyAsnIECGoosePdu_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _IECGoosePdu_PY_H_ */
