/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_IECGoosePdu_H_
#define	_IECGoosePdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data;

/* IECGoosePdu */
typedef struct IECGoosePdu {
	VisibleString_t	 gocbRef;
	long	 timeAllowedtoLive;
	VisibleString_t	 datSet;
	VisibleString_t	*goID;	/* OPTIONAL */
	OCTET_STRING_t	 time;
	long	 stNum;
	long	 sqNum;
	BOOLEAN_t	 simulation;	/* DEFAULT FALSE */
	long	 confRev;
	BOOLEAN_t	 ndsCom;	/* DEFAULT FALSE */
	long	 numDatSetEntries;
	struct IECGoosePdu__allData {
		A_SEQUENCE_OF(struct Data) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} allData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IECGoosePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IECGoosePdu;
extern asn_SEQUENCE_specifics_t asn_SPC_IECGoosePdu_specs_1;
extern asn_TYPE_member_t asn_MBR_IECGoosePdu_1[12];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _IECGoosePdu_H_ */
#include <asn_internal.h>
