/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_MMSString_H_
#define	_MMSString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MMSString */
typedef UTF8String_t	 MMSString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MMSString;
asn_struct_free_f MMSString_free;
asn_struct_print_f MMSString_print;
asn_constr_check_f MMSString_constraint;
ber_type_decoder_f MMSString_decode_ber;
der_type_encoder_f MMSString_encode_der;
xer_type_decoder_f MMSString_decode_xer;
xer_type_encoder_f MMSString_encode_xer;
jer_type_encoder_f MMSString_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _MMSString_H_ */
#include <asn_internal.h>
