/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_RequestResults_PY_H_
#define	_RequestResults_PY_H_


#include <RequestResults.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ErrorReason_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RequestResults */
PyCompat_DEF_STRUCT(RequestResults);
PyCompat_DEF_TYPE(RequestResults);
PyCompat_DEF_ENUM(RequestResults_PRESENT);

/* Type Converters */
int PyAsnRequestResults_FromPython(PyObject *pObj, RequestResults_t *pDst);
PyObject *PyAsnRequestResults_ToPython(RequestResults_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnRequestResults_ModSetupTypes(void);
void PyAsnRequestResults_ModClear(PyObject *);
int PyAsnRequestResults_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RequestResults_PY_H_ */
