/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_SavPdu_H_
#define	_SavPdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <ANY.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASDU;

/* SavPdu */
typedef struct SavPdu {
	long	 noASDU;
	ANY_t	*security;	/* OPTIONAL */
	struct SavPdu__seqASDU {
		A_SEQUENCE_OF(struct ASDU) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} seqASDU;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SavPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SavPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_SavPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_SavPdu_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASDU.h"

#endif	/* _SavPdu_H_ */
#include <asn_internal.h>
