/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_SavPdu_PY_H_
#define	_SavPdu_PY_H_


#include <SavPdu.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ASDU_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SavPdu */
typedef struct SavPdu__seqASDU SavPdu_seqASDU_ANON_4_t;
PyCompat_DEF_STRUCT(SavPdu_seqASDU_ANON_4);
PyCompat_DEF_TYPE(SavPdu_seqASDU_ANON_4);
PyCompat_DEF_STRUCT(SavPdu);
PyCompat_DEF_TYPE(SavPdu);

/* Type Converters */
int PyAsnSavPdu_seqASDU_ANON_4_FromPython(PyObject *pObj, SavPdu_seqASDU_ANON_4_t *pDst);
PyObject *PyAsnSavPdu_seqASDU_ANON_4_ToPython(SavPdu_seqASDU_ANON_4_t *pSrc, PyObject *parent);
int PyAsnSavPdu_FromPython(PyObject *pObj, SavPdu_t *pDst);
PyObject *PyAsnSavPdu_ToPython(SavPdu_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnSavPdu_ModSetupTypes(void);
void PyAsnSavPdu_ModClear(PyObject *);
int PyAsnSavPdu_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _SavPdu_PY_H_ */
