/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "IEC61850"
 */

#ifndef	_TimeOfDay_PY_H_
#define	_TimeOfDay_PY_H_


#include <TimeOfDay.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeOfDay */
PyCompat_DEF_STRUCT(TimeOfDay);
PyCompat_DEF_TYPE(TimeOfDay);

/* Type Converters */
static inline int PyAsnTimeOfDay_FromPython(PyObject *pObj, TimeOfDay_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(TimeOfDay, pObj, pDst);
	return PyCompatBytes_ToStringAndSize(pObj, &pDst->buf, &pDst->size);
}
static inline PyObject *PyAsnTimeOfDay_ToPython(TimeOfDay_t *pSrc, PyObject *parent)
{
	return PyCompatBytes_FromStringAndSize(pSrc->buf, pSrc->size);
}

/* Module Initializers */
int PyAsnTimeOfDay_ModSetupTypes(void);
void PyAsnTimeOfDay_ModClear(PyObject *);
int PyAsnTimeOfDay_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TimeOfDay_PY_H_ */
