[build-system]
# We use scikit-build-core to build our project, which heavily relies on certain
# dependencies to be installed:
# - CMake
# - Ninja
# - A compatible compiler (GCC recommended)
requires = ["scikit-build-core", "setuptools-scm>=8"]
build-backend = "scikit_build_core.build"

[project]
name = "icspacket"
dynamic = ["version"]
description = "Python classes to interact with industrial control systems (ICS) using various protocols."
readme = "README.md"
requires-python = ">=3.10"
keywords = [
  "ics",
  "ics-security",
  "libiec61850",
  "iec61850",
  "iso8823",
  "iso8237",
  "cotp",
  "tpkt",
  "goose",
]
authors = [{ name = "MatrixEditor" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
dependencies = [
  "caterpillar-py>=2.9.1", # binary protocols
  "bitarray",              # asn1c-python extensions
  "typing-extensions",     # compatibility with 3.10
  # --- protocol dependencies
  "pymodbus>=3.8.6",
  "asyncua>=1.1",
  "bacpypes3==0.0.106",
  # ---  dependencies for examples
  "rich",   # colored terminal output and logging
  "cmd2",   # advanced command shells (cmd 2.0)
  "crcmod", # dnp3 checksum algorithm
  "scapy",  # GOOSE and SV send/recv
]

[project.urls]
Documentation = "https://github.com/MatrixEditor/icspacket#readme"
Issues = "https://github.com/MatrixEditor/icspacket/issues"
GitHub = "https://github.com/MatrixEditor/icspacket"

[tool.scikit-build.cmake]
# NOTE: To enable extra debugging output at runtime you might also add
# -DASN_EMIT_DEBUG=1 as a compile-time define.
# build-type = "Debug"

# --- Dynamic Version scheme
[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["src/icspacket/_version.py"]

[tool.setuptools_scm]
write_to = "src/icspacket/_version.py"

[dependency-groups]
dev = ["pytest>=9.1.1"]

# --- example scripts
[project.scripts]
"mms_utility.py" = "icspacket.examples.mms_utility:cli_main"
"mmsclient.py" = "icspacket.examples.mmsclient:cli_main"
"iedmap.py" = "icspacket.examples.iedmap:cli_main"
"iedctrl.py" = "icspacket.examples.iedctrl:cli_main"
"dnp3dump.py" = "icspacket.examples.dnp3dump:cli_main"
"dnp3read.py" = "icspacket.examples.dnp3read:cli_main"
"dnp3linkaddr.py" = "icspacket.examples.dnp3linkaddr:cli_main"
"iec104read.py" = "icspacket.examples.iec104read:cli_main"
"modbusclient.py" = "icspacket.examples.modbusclient:cli_main"
"cipclient.py" = "icspacket.examples.cipclient:cli_main"
"opcuaclient.py" = "icspacket.examples.opcuaclient:cli_main"
"bacnetclient.py" = "icspacket.examples.bacnetclient:cli_main"

