/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#include <ABRT-diagnostic.h>
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static const asn_INTEGER_enum_map_t asn_MAP_ABRT_diagnostic_value2enum_1[] = {
	{ 1,	15,	"no-reason-given" },
	{ 2,	14,	"protocol-error" },
	{ 3,	44,	"authentication-mechanism-name-not-recognized" },
	{ 4,	38,	"authentication-mechanism-name-required" },
	{ 5,	22,	"authentication-failure" },
	{ 6,	23,	"authentication-required" }
};
static int asn_validate_ABRT_diagnostic_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) {
        ASN__CTFAIL(app_key, td, sptr, "%s: value not given (%s:%d)",
                    td->name, __FILE__, __LINE__);
        return -1;
    }
    e_ABRT_diagnostic value = *(e_ABRT_diagnostic*)sptr;
    switch(value) {
    case ABRT_diagnostic_no_reason_given:
    case ABRT_diagnostic_protocol_error:
    case ABRT_diagnostic_authentication_mechanism_name_not_recognized:
    case ABRT_diagnostic_authentication_mechanism_name_required:
    case ABRT_diagnostic_authentication_failure:
    case ABRT_diagnostic_authentication_required:
        return 0;
    }
    ASN__CTFAIL(app_key, td, sptr,
                "%s: %ld does not correspond to any enumeration value (%s:%d)",
                td->name, (long)value, __FILE__, __LINE__);
    return -1;
}
static const unsigned int asn_MAP_ABRT_diagnostic_enum2value_1[] = {
	4,	/* authentication-failure(5) */
	2,	/* authentication-mechanism-name-not-recognized(3) */
	3,	/* authentication-mechanism-name-required(4) */
	5,	/* authentication-required(6) */
	0,	/* no-reason-given(1) */
	1	/* protocol-error(2) */
};
const asn_INTEGER_specifics_t asn_SPC_ABRT_diagnostic_specs_1 = {
	asn_MAP_ABRT_diagnostic_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ABRT_diagnostic_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ABRT_diagnostic_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ABRT_diagnostic = {
	"ABRT-diagnostic",
	"ABRT-diagnostic",
	&asn_OP_NativeEnumerated,
	asn_DEF_ABRT_diagnostic_tags_1,
	sizeof(asn_DEF_ABRT_diagnostic_tags_1)
		/sizeof(asn_DEF_ABRT_diagnostic_tags_1[0]), /* 1 */
	asn_DEF_ABRT_diagnostic_tags_1,	/* Same as above */
	sizeof(asn_DEF_ABRT_diagnostic_tags_1)
		/sizeof(asn_DEF_ABRT_diagnostic_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_ABRT_diagnostic_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ABRT_diagnostic_specs_1	/* Additional specs */
};

