/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AccessResult_H_
#define	_AccessResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataAccessError.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccessResult_PR {
	AccessResult_PR_NOTHING,	/* No components present */
	AccessResult_PR_failure,
	AccessResult_PR_success
} AccessResult_PR;

/* Forward declarations */
struct Data;

/* AccessResult */
typedef struct AccessResult {
	AccessResult_PR present;
	union AccessResult_u {
		DataAccessError_t	 failure;
		struct Data	*success;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccessResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccessResult;
extern asn_CHOICE_specifics_t asn_SPC_AccessResult_specs_1;
extern asn_TYPE_member_t asn_MBR_AccessResult_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _AccessResult_H_ */
#include <asn_internal.h>
