/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AccessResult_PY_H_
#define	_AccessResult_PY_H_


#include <AccessResult.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <DataAccessError_Py.h>
#include <Data_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AccessResult */
PyCompat_DEF_STRUCT(AccessResult);
PyCompat_DEF_TYPE(AccessResult);
PyCompat_DEF_ENUM(AccessResult_PRESENT);

/* Type Converters */
int PyAsnAccessResult_FromPython(PyObject *pObj, AccessResult_t *pDst);
PyObject *PyAsnAccessResult_ToPython(AccessResult_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAccessResult_ModSetupTypes(void);
void PyAsnAccessResult_ModClear(PyObject *);
int PyAsnAccessResult_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AccessResult_PY_H_ */
