/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AcknowledgeEventNotification_Request_H_
#define	_AcknowledgeEventNotification_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EC-State.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct EventTime;

/* AcknowledgeEventNotification-Request */
typedef struct AcknowledgeEventNotification_Request {
	struct ObjectName	*eventEnrollmentName;
	EC_State_t	 acknowledgedState;
	struct EventTime	*timeOfAcknowledgedTransition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcknowledgeEventNotification_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcknowledgeEventNotification_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_AcknowledgeEventNotification_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_AcknowledgeEventNotification_Request_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "EventTime.h"

#endif	/* _AcknowledgeEventNotification_Request_H_ */
#include <asn_internal.h>
