/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_ACSE_apdu_H_
#define	_ACSE_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ACSE_apdu_PR {
	ACSE_apdu_PR_NOTHING,	/* No components present */
	ACSE_apdu_PR_aarq,
	ACSE_apdu_PR_aare,
	ACSE_apdu_PR_rlrq,
	ACSE_apdu_PR_rlre,
	ACSE_apdu_PR_abrt
} ACSE_apdu_PR;

/* Forward declarations */
struct AARQ_apdu;
struct AARE_apdu;
struct RLRQ_apdu;
struct RLRE_apdu;
struct ABRT_apdu;

/* ACSE-apdu */
typedef struct ACSE_apdu {
	ACSE_apdu_PR present;
	union ACSE_apdu_u {
		struct AARQ_apdu	*aarq;
		struct AARE_apdu	*aare;
		struct RLRQ_apdu	*rlrq;
		struct RLRE_apdu	*rlre;
		struct ABRT_apdu	*abrt;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ACSE_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACSE_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AARQ-apdu.h"
#include "AARE-apdu.h"
#include "RLRQ-apdu.h"
#include "RLRE-apdu.h"
#include "ABRT-apdu.h"

#endif	/* _ACSE_apdu_H_ */
#include <asn_internal.h>
