/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AdditionalService_Error_PY_H_
#define	_AdditionalService_Error_PY_H_


#include <AdditionalService-Error.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <DefineEventConditionList-Error_Py.h>
#include <AddEventConditionListReference-Error_Py.h>
#include <RemoveEventConditionListReference-Error_Py.h>
#include <InitiateUnitControl-Error_Py.h>
#include <StartUnitControl-Error_Py.h>
#include <StopUnitControl-Error_Py.h>
#include <DeleteUnitControl-Error_Py.h>
#include <LoadUnitControlFromFile-Error_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AdditionalService-Error */
PyCompat_DEF_STRUCT(AdditionalService_Error);
PyCompat_DEF_TYPE(AdditionalService_Error);
PyCompat_DEF_ENUM(AdditionalService_Error_PRESENT);

/* Type Converters */
int PyAsnAdditionalService_Error_FromPython(PyObject *pObj, AdditionalService_Error_t *pDst);
PyObject *PyAsnAdditionalService_Error_ToPython(AdditionalService_Error_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAdditionalService_Error_ModSetupTypes(void);
void PyAsnAdditionalService_Error_ModClear(PyObject *);
int PyAsnAdditionalService_Error_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalService_Error_PY_H_ */
