/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AdditionalCBBOptions_H_
#define	_AdditionalCBBOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdditionalCBBOptions {
	AdditionalCBBOptions_des	= 0,
	AdditionalCBBOptions_dei	= 1,
	AdditionalCBBOptions_recl	= 2
} e_AdditionalCBBOptions;

/* AdditionalCBBOptions */
typedef BIT_STRING_t	 AdditionalCBBOptions_t;

/* Implementation */
extern asn_jer_constraints_t asn_JER_type_AdditionalCBBOptions_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdditionalCBBOptions;
asn_struct_free_f AdditionalCBBOptions_free;
asn_struct_print_f AdditionalCBBOptions_print;
asn_constr_check_f AdditionalCBBOptions_constraint;
ber_type_decoder_f AdditionalCBBOptions_decode_ber;
der_type_encoder_f AdditionalCBBOptions_encode_der;
xer_type_decoder_f AdditionalCBBOptions_decode_xer;
xer_type_encoder_f AdditionalCBBOptions_encode_xer;
jer_type_encoder_f AdditionalCBBOptions_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalCBBOptions_H_ */
#include <asn_internal.h>
