/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AdditionalService_Response_H_
#define	_AdditionalService_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VMDStop-Response.h"
#include "Select-Response.h"
#include "AlterProgramInvocationAttributes-Response.h"
#include "InitiateUnitControlLoad-Response.h"
#include "StartUnitControl-Response.h"
#include "StopUnitControl-Response.h"
#include "CreateUnitControl-Response.h"
#include "AddToUnitControl-Response.h"
#include "RemoveFromUnitControl-Response.h"
#include "LoadUnitControlFromFile-Response.h"
#include "StoreUnitControlToFile-Response.h"
#include "DeleteUnitControl-Response.h"
#include "DefineEventConditionList-Response.h"
#include "DeleteEventConditionList-Response.h"
#include "AddEventConditionListReference-Response.h"
#include "RemoveEventConditionListReference-Response.h"
#include "AlterEventConditionListMonitoring-Response.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdditionalService_Response_PR {
	AdditionalService_Response_PR_NOTHING,	/* No components present */
	AdditionalService_Response_PR_vMDStop,
	AdditionalService_Response_PR_vMDReset,
	AdditionalService_Response_PR_select,
	AdditionalService_Response_PR_alterPI,
	AdditionalService_Response_PR_initiateUCLoad,
	AdditionalService_Response_PR_uCLoad,
	AdditionalService_Response_PR_uCUpload,
	AdditionalService_Response_PR_startUC,
	AdditionalService_Response_PR_stopUC,
	AdditionalService_Response_PR_createUC,
	AdditionalService_Response_PR_addToUC,
	AdditionalService_Response_PR_removeFromUC,
	AdditionalService_Response_PR_getUCAttributes,
	AdditionalService_Response_PR_loadUCFromFile,
	AdditionalService_Response_PR_storeUCToFile,
	AdditionalService_Response_PR_deleteUC,
	AdditionalService_Response_PR_defineECL,
	AdditionalService_Response_PR_deleteECL,
	AdditionalService_Response_PR_addECLReference,
	AdditionalService_Response_PR_removeECLReference,
	AdditionalService_Response_PR_getECLAttributes,
	AdditionalService_Response_PR_reportECLStatus,
	AdditionalService_Response_PR_alterECLMonitoring
} AdditionalService_Response_PR;

/* Forward declarations */
struct VMDReset_Response;
struct UnitControlLoadSegment_Response;
struct UnitControlUpload_Response;
struct GetUnitControlAttributes_Response;
struct GetEventConditionListAttributes_Response;
struct ReportEventConditionListStatus_Response;
struct StatusResponse;

/* AdditionalService-Response */
typedef struct AdditionalService_Response {
	AdditionalService_Response_PR present;
	union AdditionalService_Response_u {
		VMDStop_Response_t	 vMDStop;
		struct StatusResponse	*vMDReset;
		Select_Response_t	 select;
		AlterProgramInvocationAttributes_Response_t	 alterPI;
		InitiateUnitControlLoad_Response_t	 initiateUCLoad;
		struct UnitControlLoadSegment_Response	*uCLoad;
		struct UnitControlUpload_Response	*uCUpload;
		StartUnitControl_Response_t	 startUC;
		StopUnitControl_Response_t	 stopUC;
		CreateUnitControl_Response_t	 createUC;
		AddToUnitControl_Response_t	 addToUC;
		RemoveFromUnitControl_Response_t	 removeFromUC;
		struct GetUnitControlAttributes_Response	*getUCAttributes;
		LoadUnitControlFromFile_Response_t	 loadUCFromFile;
		StoreUnitControlToFile_Response_t	 storeUCToFile;
		DeleteUnitControl_Response_t	 deleteUC;
		DefineEventConditionList_Response_t	 defineECL;
		DeleteEventConditionList_Response_t	 deleteECL;
		AddEventConditionListReference_Response_t	 addECLReference;
		RemoveEventConditionListReference_Response_t	 removeECLReference;
		struct GetEventConditionListAttributes_Response	*getECLAttributes;
		struct ReportEventConditionListStatus_Response	*reportECLStatus;
		AlterEventConditionListMonitoring_Response_t	 alterECLMonitoring;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalService_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalService_Response;
extern asn_CHOICE_specifics_t asn_SPC_AdditionalService_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_AdditionalService_Response_1[23];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VMDReset-Response.h"
#include "UnitControlLoadSegment-Response.h"
#include "UnitControlUpload-Response.h"
#include "GetUnitControlAttributes-Response.h"
#include "GetEventConditionListAttributes-Response.h"
#include "ReportEventConditionListStatus-Response.h"

#endif	/* _AdditionalService_Response_H_ */
#include <asn_internal.h>
