/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AdditionalService_Request_H_
#define	_AdditionalService_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VMDStop-Request.h"
#include "VMDReset-Request.h"
#include "InitiateUnitControlLoad-Request.h"
#include "UnitControlLoadSegment-Request.h"
#include "StopUnitControl-Request.h"
#include "GetUnitControlAttributes-Request.h"
#include "DeleteUnitControl-Request.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdditionalService_Request_PR {
	AdditionalService_Request_PR_NOTHING,	/* No components present */
	AdditionalService_Request_PR_vMDStop,
	AdditionalService_Request_PR_vMDReset,
	AdditionalService_Request_PR_select,
	AdditionalService_Request_PR_alterPI,
	AdditionalService_Request_PR_initiateUCLoad,
	AdditionalService_Request_PR_uCLoad,
	AdditionalService_Request_PR_uCUpload,
	AdditionalService_Request_PR_startUC,
	AdditionalService_Request_PR_stopUC,
	AdditionalService_Request_PR_createUC,
	AdditionalService_Request_PR_addToUC,
	AdditionalService_Request_PR_removeFromUC,
	AdditionalService_Request_PR_getUCAttributes,
	AdditionalService_Request_PR_loadUCFromFile,
	AdditionalService_Request_PR_storeUCToFile,
	AdditionalService_Request_PR_deleteUC,
	AdditionalService_Request_PR_defineECL,
	AdditionalService_Request_PR_deleteECL,
	AdditionalService_Request_PR_addECLReference,
	AdditionalService_Request_PR_removeECLReference,
	AdditionalService_Request_PR_getECLAttributes,
	AdditionalService_Request_PR_reportECLStatus,
	AdditionalService_Request_PR_alterECLMonitoring
} AdditionalService_Request_PR;

/* Forward declarations */
struct Select_Request;
struct AlterProgramInvocationAttributes_Request;
struct UnitControlUpload_Request;
struct StartUnitControl_Request;
struct CreateUnitControl_Request;
struct AddToUnitControl_Request;
struct RemoveFromUnitControl_Request;
struct LoadUnitControlFromFile_Request;
struct StoreUnitControlToFile_Request;
struct DefineEventConditionList_Request;
struct DeleteEventConditionList_Request;
struct AddEventConditionListReference_Request;
struct RemoveEventConditionListReference_Request;
struct GetEventConditionListAttributes_Request;
struct ReportEventConditionListStatus_Request;
struct AlterEventConditionListMonitoring_Request;
struct ObjectName;

/* AdditionalService-Request */
typedef struct AdditionalService_Request {
	AdditionalService_Request_PR present;
	union AdditionalService_Request_u {
		VMDStop_Request_t	 vMDStop;
		VMDReset_Request_t	 vMDReset;
		struct Select_Request	*select;
		struct AlterProgramInvocationAttributes_Request	*alterPI;
		InitiateUnitControlLoad_Request_t	 initiateUCLoad;
		UnitControlLoadSegment_Request_t	 uCLoad;
		struct UnitControlUpload_Request	*uCUpload;
		struct StartUnitControl_Request	*startUC;
		StopUnitControl_Request_t	 stopUC;
		struct CreateUnitControl_Request	*createUC;
		struct AddToUnitControl_Request	*addToUC;
		struct RemoveFromUnitControl_Request	*removeFromUC;
		GetUnitControlAttributes_Request_t	 getUCAttributes;
		struct LoadUnitControlFromFile_Request	*loadUCFromFile;
		struct StoreUnitControlToFile_Request	*storeUCToFile;
		DeleteUnitControl_Request_t	 deleteUC;
		struct DefineEventConditionList_Request	*defineECL;
		struct ObjectName	*deleteECL;
		struct AddEventConditionListReference_Request	*addECLReference;
		struct RemoveEventConditionListReference_Request	*removeECLReference;
		struct ObjectName	*getECLAttributes;
		struct ReportEventConditionListStatus_Request	*reportECLStatus;
		struct AlterEventConditionListMonitoring_Request	*alterECLMonitoring;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalService_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalService_Request;
extern asn_CHOICE_specifics_t asn_SPC_AdditionalService_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_AdditionalService_Request_1[23];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Select-Request.h"
#include "AlterProgramInvocationAttributes-Request.h"
#include "UnitControlUpload-Request.h"
#include "StartUnitControl-Request.h"
#include "CreateUnitControl-Request.h"
#include "AddToUnitControl-Request.h"
#include "RemoveFromUnitControl-Request.h"
#include "LoadUnitControlFromFile-Request.h"
#include "StoreUnitControlToFile-Request.h"
#include "DefineEventConditionList-Request.h"
#include "DeleteEventConditionList-Request.h"
#include "AddEventConditionListReference-Request.h"
#include "RemoveEventConditionListReference-Request.h"
#include "GetEventConditionListAttributes-Request.h"
#include "ReportEventConditionListStatus-Request.h"
#include "AlterEventConditionListMonitoring-Request.h"

#endif	/* _AdditionalService_Request_H_ */
#include <asn_internal.h>
