/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Address_PY_H_
#define	_Address_PY_H_


#include <Address.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <MMSString_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Address */
PyCompat_DEF_STRUCT(Address);
PyCompat_DEF_TYPE(Address);
PyCompat_DEF_ENUM(Address_PRESENT);

/* Type Converters */
int PyAsnAddress_FromPython(PyObject *pObj, Address_t *pDst);
PyObject *PyAsnAddress_ToPython(Address_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAddress_ModSetupTypes(void);
void PyAsnAddress_ModClear(PyObject *);
int PyAsnAddress_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Address_PY_H_ */
