/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_AE_qualifier_H_
#define	_AE_qualifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AE-qualifier-form2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AE_qualifier_PR {
	AE_qualifier_PR_NOTHING,	/* No components present */
	AE_qualifier_PR_ae_qualifier_form1,
	AE_qualifier_PR_ae_qualifier_form2
} AE_qualifier_PR;

/* Forward declarations */
struct AE_qualifier_form1;
struct RelativeDistinguishedName;

/* AE-qualifier */
typedef struct AE_qualifier {
	AE_qualifier_PR present;
	union AE_qualifier_u {
		struct RelativeDistinguishedName	*ae_qualifier_form1;
		AE_qualifier_form2_t	 ae_qualifier_form2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AE_qualifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AE_qualifier;
extern asn_CHOICE_specifics_t asn_SPC_AE_qualifier_specs_1;
extern asn_TYPE_member_t asn_MBR_AE_qualifier_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AE-qualifier-form1.h"

#endif	/* _AE_qualifier_H_ */
#include <asn_internal.h>
