/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_AE_title_H_
#define	_AE_title_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AE-title-form2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AE_title_PR {
	AE_title_PR_NOTHING,	/* No components present */
	AE_title_PR_ae_title_form1,
	AE_title_PR_ae_title_form2
} AE_title_PR;

/* Forward declarations */
struct AE_title_form1;
struct Name;

/* AE-title */
typedef struct AE_title {
	AE_title_PR present;
	union AE_title_u {
		struct Name	*ae_title_form1;
		AE_title_form2_t	 ae_title_form2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AE_title_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AE_title;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AE-title-form1.h"

#endif	/* _AE_title_H_ */
#include <asn_internal.h>
