/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_AE_title_form1_PY_H_
#define	_AE_title_form1_PY_H_


#include <AE-title-form1.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Name_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AE-title-form1 */
PyCompat_DEF_STRUCT(AE_title_form1);
PyCompat_DEF_TYPE(AE_title_form1);
PyCompat_DEF_ENUM(AE_title_form1);

/* Type Converters */
static inline PyObject *PyAsnAE_title_form1_ToPython(AE_title_form1_t *pSrc, PyObject *parent)
{
	return PyAsnName_ToPython(pSrc, parent);
}
static inline int PyAsnAE_title_form1_FromPython(PyObject *pObj, AE_title_form1_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(AE_title_form1, pObj, pDst);
	return PyAsnName_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnAE_title_form1_ModSetupTypes(void);
void PyAsnAE_title_form1_ModClear(PyObject *);
int PyAsnAE_title_form1_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AE_title_form1_PY_H_ */
