/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlarmSummary_PY_H_
#define	_AlarmSummary_PY_H_


#include <AlarmSummary.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Unsigned8_Py.h>
#include <EC-State_Py.h>
#include <EN-Additional-Detail_Py.h>
#include <EventTime_Py.h>
#include <EventTime_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlarmSummary */
PyCompat_DEF_STRUCT(AlarmSummary);
PyCompat_DEF_TYPE(AlarmSummary);
PyCompat_DEF_ENUM(AlarmSummary_unacknowledgedState);

/* Type Converters */
int PyAsnAlarmSummary_FromPython(PyObject *pObj, AlarmSummary_t *pDst);
PyObject *PyAsnAlarmSummary_ToPython(AlarmSummary_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAlarmSummary_ModSetupTypes(void);
void PyAsnAlarmSummary_ModClear(PyObject *);
int PyAsnAlarmSummary_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AlarmSummary_PY_H_ */
