/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlarmSummary_H_
#define	_AlarmSummary_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned8.h"
#include "EC-State.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlarmSummary__unacknowledgedState {
	AlarmSummary__unacknowledgedState_none	= 0,
	AlarmSummary__unacknowledgedState_active	= 1,
	AlarmSummary__unacknowledgedState_idle	= 2,
	AlarmSummary__unacknowledgedState_both	= 3
} e_AlarmSummary__unacknowledgedState;

/* Forward declarations */
struct ObjectName;
struct EN_Additional_Detail;
struct EventTime;

/* AlarmSummary */
typedef struct AlarmSummary {
	struct ObjectName	*eventConditionName;
	Unsigned8_t	 severity;
	EC_State_t	 currentState;
	long	 unacknowledgedState;
	struct EN_Additional_Detail	*displayEnhancement;	/* OPTIONAL */
	struct EventTime	*timeOfLastTransitionToActive;	/* OPTIONAL */
	struct EventTime	*timeOfLastTransitionToIdle;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlarmSummary_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlarmSummary;
extern asn_SEQUENCE_specifics_t asn_SPC_AlarmSummary_specs_1;
extern asn_TYPE_member_t asn_MBR_AlarmSummary_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "EN-Additional-Detail.h"
#include "EventTime.h"

#endif	/* _AlarmSummary_H_ */
#include <asn_internal.h>
