/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlarmEnrollmentSummary_PY_H_
#define	_AlarmEnrollmentSummary_PY_H_


#include <AlarmEnrollmentSummary.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <ApplicationReference_Py.h>
#include <Unsigned8_Py.h>
#include <EC-State_Py.h>
#include <EN-Additional-Detail_Py.h>
#include <AlarmAckRule_Py.h>
#include <EE-State_Py.h>
#include <EventTime_Py.h>
#include <EventTime_Py.h>
#include <EventTime_Py.h>
#include <EventTime_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlarmEnrollmentSummary */
PyCompat_DEF_STRUCT(AlarmEnrollmentSummary);
PyCompat_DEF_TYPE(AlarmEnrollmentSummary);

/* Type Converters */
int PyAsnAlarmEnrollmentSummary_FromPython(PyObject *pObj, AlarmEnrollmentSummary_t *pDst);
PyObject *PyAsnAlarmEnrollmentSummary_ToPython(AlarmEnrollmentSummary_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAlarmEnrollmentSummary_ModSetupTypes(void);
void PyAsnAlarmEnrollmentSummary_ModClear(PyObject *);
int PyAsnAlarmEnrollmentSummary_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AlarmEnrollmentSummary_PY_H_ */
