/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlterEventConditionMonitoring_Request_H_
#define	_AlterEventConditionMonitoring_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "Priority.h"
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* AlterEventConditionMonitoring-Request */
typedef struct AlterEventConditionMonitoring_Request {
	struct ObjectName	*eventConditionName;
	BOOLEAN_t	*enabled;	/* OPTIONAL */
	Priority_t	*priority;	/* OPTIONAL */
	BOOLEAN_t	*alarmSummaryReports;	/* OPTIONAL */
	Unsigned32_t	*evaluationInterval;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlterEventConditionMonitoring_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlterEventConditionMonitoring_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_AlterEventConditionMonitoring_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_AlterEventConditionMonitoring_Request_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _AlterEventConditionMonitoring_Request_H_ */
#include <asn_internal.h>
