/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlternateAccess_H_
#define	_AlternateAccess_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Identifier.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlternateAccess__AlternateAccess_Member_PR {
	AlternateAccess__AlternateAccess_Member_PR_NOTHING,	/* No components present */
	AlternateAccess__AlternateAccess_Member_PR_unnamed,
	AlternateAccess__AlternateAccess_Member_PR_named
} AlternateAccess__AlternateAccess_Member_PR;

/* Forward declarations */
struct AlternateAccessSelection;

/* Forward definitions */
typedef struct AlternateAccess__AlternateAccess_Member {
	AlternateAccess__AlternateAccess_Member_PR present;
	union AlternateAccess__AlternateAccess_Member_u {
		struct AlternateAccessSelection	*unnamed;
		struct AlternateAccess__AlternateAccess_Member__named {
			Identifier_t	 componentName;
			struct AlternateAccessSelection	*access;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} named;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternateAccess__AlternateAccess_Member;

/* AlternateAccess */
typedef struct AlternateAccess {
	A_SEQUENCE_OF(AlternateAccess__AlternateAccess_Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternateAccess_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlternateAccess;
extern asn_SET_OF_specifics_t asn_SPC_AlternateAccess_specs_1;
extern asn_TYPE_member_t asn_MBR_AlternateAccess_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateAccessSelection.h"

#endif	/* _AlternateAccess_H_ */
#include <asn_internal.h>
