/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlterEventConditionMonitoring_Response_PY_H_
#define	_AlterEventConditionMonitoring_Response_PY_H_


#include <AlterEventConditionMonitoring-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlterEventConditionMonitoring-Response */
PyCompat_DEF_STRUCT(AlterEventConditionMonitoring_Response);
PyCompat_DEF_TYPE(AlterEventConditionMonitoring_Response);

/* Type Converters */
static inline PyObject *PyAsnAlterEventConditionMonitoring_Response_ToPython(AlterEventConditionMonitoring_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnAlterEventConditionMonitoring_Response_FromPython(PyObject *pObj, AlterEventConditionMonitoring_Response_t *pDst)
{
	*pDst = (AlterEventConditionMonitoring_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnAlterEventConditionMonitoring_Response_ModSetupTypes(void);
void PyAsnAlterEventConditionMonitoring_Response_ModClear(PyObject *);
int PyAsnAlterEventConditionMonitoring_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AlterEventConditionMonitoring_Response_PY_H_ */
