/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlterProgramInvocationAttributes_Request_PY_H_
#define	_AlterProgramInvocationAttributes_Request_PY_H_


#include <AlterProgramInvocationAttributes-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <StartCount_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlterProgramInvocationAttributes-Request */
PyCompat_DEF_STRUCT(AlterProgramInvocationAttributes_Request);
PyCompat_DEF_TYPE(AlterProgramInvocationAttributes_Request);

/* Type Converters */
int PyAsnAlterProgramInvocationAttributes_Request_FromPython(PyObject *pObj, AlterProgramInvocationAttributes_Request_t *pDst);
PyObject *PyAsnAlterProgramInvocationAttributes_Request_ToPython(AlterProgramInvocationAttributes_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAlterProgramInvocationAttributes_Request_ModSetupTypes(void);
void PyAsnAlterProgramInvocationAttributes_Request_ModClear(PyObject *);
int PyAsnAlterProgramInvocationAttributes_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AlterProgramInvocationAttributes_Request_PY_H_ */
