/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlterEventEnrollment_Request_PY_H_
#define	_AlterEventEnrollment_Request_PY_H_


#include <AlterEventEnrollment-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Transitions_Py.h>
#include <AlarmAckRule_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlterEventEnrollment-Request */
PyCompat_DEF_STRUCT(AlterEventEnrollment_Request);
PyCompat_DEF_TYPE(AlterEventEnrollment_Request);

/* Type Converters */
int PyAsnAlterEventEnrollment_Request_FromPython(PyObject *pObj, AlterEventEnrollment_Request_t *pDst);
PyObject *PyAsnAlterEventEnrollment_Request_ToPython(AlterEventEnrollment_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAlterEventEnrollment_Request_ModSetupTypes(void);
void PyAsnAlterEventEnrollment_Request_ModClear(PyObject *);
int PyAsnAlterEventEnrollment_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AlterEventEnrollment_Request_PY_H_ */
