/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AlternateAccess_PY_H_
#define	_AlternateAccess_PY_H_


#include <AlternateAccess.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <AlternateAccessSelection_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <AlternateAccessSelection_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlternateAccess */
PyCompat_DEF_ANON_STRUCT(AlternateAccess_named_ANON_4, AlternateAccess__AlternateAccess_Member__named);
PyCompat_DEF_TYPE(AlternateAccess_named_ANON_4);
PyCompat_DEF_ANON_STRUCT(AlternateAccess_AlternateAccess_Member_ANON_2, AlternateAccess__AlternateAccess_Member);
PyCompat_DEF_TYPE(AlternateAccess_AlternateAccess_Member_ANON_2);
PyCompat_DEF_ENUM(AlternateAccess_AlternateAccess_Member_ANON_2_PRESENT);
PyCompat_DEF_STRUCT(AlternateAccess);
PyCompat_DEF_TYPE(AlternateAccess);

/* Type Converters */
int PyAsnAlternateAccess_named_ANON_4_FromPython(PyObject *pObj, AlternateAccess_named_ANON_4_t *pDst);
PyObject *PyAsnAlternateAccess_named_ANON_4_ToPython(AlternateAccess_named_ANON_4_t *pSrc, PyObject *parent);
int PyAsnAlternateAccess_AlternateAccess_Member_ANON_2_FromPython(PyObject *pObj, AlternateAccess_AlternateAccess_Member_ANON_2_t *pDst);
PyObject *PyAsnAlternateAccess_AlternateAccess_Member_ANON_2_ToPython(AlternateAccess_AlternateAccess_Member_ANON_2_t *pSrc, PyObject *parent);
int PyAsnAlternateAccess_FromPython(PyObject *pObj, AlternateAccess_t *pDst);
PyObject *PyAsnAlternateAccess_ToPython(AlternateAccess_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAlternateAccess_ModSetupTypes(void);
void PyAsnAlternateAccess_ModClear(PyObject *);
int PyAsnAlternateAccess_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AlternateAccess_PY_H_ */
