/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_AP_title_H_
#define	_AP_title_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AP-title-form2.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AP_title_PR {
	AP_title_PR_NOTHING,	/* No components present */
	AP_title_PR_ap_title_form1,
	AP_title_PR_ap_title_form2
} AP_title_PR;

/* Forward declarations */
struct AP_title_form1;
struct Name;

/* AP-title */
typedef struct AP_title {
	AP_title_PR present;
	union AP_title_u {
		struct Name	*ap_title_form1;
		AP_title_form2_t	 ap_title_form2;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AP_title_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AP_title;
extern asn_CHOICE_specifics_t asn_SPC_AP_title_specs_1;
extern asn_TYPE_member_t asn_MBR_AP_title_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AP-title-form1.h"

#endif	/* _AP_title_H_ */
#include <asn_internal.h>
