/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Application_context_name_list_PY_H_
#define	_Application_context_name_list_PY_H_


#include <Application-context-name-list.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Application-context-name_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Application-context-name-list */
PyCompat_DEF_STRUCT(Application_context_name_list);
PyCompat_DEF_TYPE(Application_context_name_list);

/* Type Converters */
int PyAsnApplication_context_name_list_FromPython(PyObject *pObj, Application_context_name_list_t *pDst);
PyObject *PyAsnApplication_context_name_list_ToPython(Application_context_name_list_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnApplication_context_name_list_ModSetupTypes(void);
void PyAsnApplication_context_name_list_ModClear(PyObject *);
int PyAsnApplication_context_name_list_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Application_context_name_list_PY_H_ */
