/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ApplicationReference_PY_H_
#define	_ApplicationReference_PY_H_


#include <ApplicationReference.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <AP-title_Py.h>
#include <AP-invocation-identifier_Py.h>
#include <AE-qualifier_Py.h>
#include <AE-invocation-identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ApplicationReference */
PyCompat_DEF_STRUCT(ApplicationReference);
PyCompat_DEF_TYPE(ApplicationReference);

/* Type Converters */
int PyAsnApplicationReference_FromPython(PyObject *pObj, ApplicationReference_t *pDst);
PyObject *PyAsnApplicationReference_ToPython(ApplicationReference_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnApplicationReference_ModSetupTypes(void);
void PyAsnApplicationReference_ModClear(PyObject *);
int PyAsnApplicationReference_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ApplicationReference_PY_H_ */
