/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Association_information_PY_H_
#define	_Association_information_PY_H_


#include <Association-information.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <EXTERNAL_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Association-information */
PyCompat_DEF_STRUCT(Association_information);
PyCompat_DEF_TYPE(Association_information);

/* Type Converters */
int PyAsnAssociation_information_FromPython(PyObject *pObj, Association_information_t *pDst);
PyObject *PyAsnAssociation_information_ToPython(Association_information_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAssociation_information_ModSetupTypes(void);
void PyAsnAssociation_information_ModClear(PyObject *);
int PyAsnAssociation_information_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Association_information_PY_H_ */
