/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AttachToEventCondition_PY_H_
#define	_AttachToEventCondition_PY_H_


#include <AttachToEventCondition.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <ObjectName_Py.h>
#include <Transitions_Py.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttachToEventCondition */
PyCompat_DEF_STRUCT(AttachToEventCondition);
PyCompat_DEF_TYPE(AttachToEventCondition);

/* Type Converters */
int PyAsnAttachToEventCondition_FromPython(PyObject *pObj, AttachToEventCondition_t *pDst);
PyObject *PyAsnAttachToEventCondition_ToPython(AttachToEventCondition_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAttachToEventCondition_ModSetupTypes(void);
void PyAsnAttachToEventCondition_ModClear(PyObject *);
int PyAsnAttachToEventCondition_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AttachToEventCondition_PY_H_ */
