/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_AttachToEventCondition_H_
#define	_AttachToEventCondition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Transitions.h"
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* AttachToEventCondition */
typedef struct AttachToEventCondition {
	struct ObjectName	*eventEnrollmentName;
	struct ObjectName	*eventConditionName;
	Transitions_t	 causingTransitions;
	Unsigned32_t	*acceptableDelay;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttachToEventCondition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttachToEventCondition;
extern asn_SEQUENCE_specifics_t asn_SPC_AttachToEventCondition_specs_1;
extern asn_TYPE_member_t asn_MBR_AttachToEventCondition_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _AttachToEventCondition_H_ */
#include <asn_internal.h>
