/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_AttributeTypeAndValue_PY_H_
#define	_AttributeTypeAndValue_PY_H_


#include <AttributeTypeAndValue.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <py_convert_OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeTypeAndValue */
PyCompat_DEF_STRUCT(AttributeTypeAndValue);
PyCompat_DEF_TYPE(AttributeTypeAndValue);

/* Type Converters */
int PyAsnAttributeTypeAndValue_FromPython(PyObject *pObj, AttributeTypeAndValue_t *pDst);
PyObject *PyAsnAttributeTypeAndValue_ToPython(AttributeTypeAndValue_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnAttributeTypeAndValue_ModSetupTypes(void);
void PyAsnAttributeTypeAndValue_ModClear(PyObject *);
int PyAsnAttributeTypeAndValue_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeTypeAndValue_PY_H_ */
