/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Authentication_value_H_
#define	_Authentication_value_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>
#include <BIT_STRING.h>
#include "Mechanism-name.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Authentication_value_PR {
	Authentication_value_PR_NOTHING,	/* No components present */
	Authentication_value_PR_charstring,
	Authentication_value_PR_bitstring,
	Authentication_value_PR_external,
	Authentication_value_PR_other
} Authentication_value_PR;

/* Forward declarations */
struct EXTERNAL;

/* Authentication-value */
typedef struct Authentication_value {
	Authentication_value_PR present;
	union Authentication_value_u {
		GraphicString_t	 charstring;
		BIT_STRING_t	 bitstring;
		struct EXTERNAL	*external;
		struct Authentication_value__other {
			Mechanism_name_t	 other_mechanism_name;
			ANY_t	 other_mechanism_value;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} other;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Authentication_value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authentication_value;
extern asn_CHOICE_specifics_t asn_SPC_Authentication_value_specs_1;
extern asn_TYPE_member_t asn_MBR_Authentication_value_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNAL.h"

#endif	/* _Authentication_value_H_ */
#include <asn_internal.h>
