/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Cancel_ResponsePDU_PY_H_
#define	_Cancel_ResponsePDU_PY_H_


#include <Cancel-ResponsePDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cancel-ResponsePDU */
PyCompat_DEF_STRUCT(Cancel_ResponsePDU);
PyCompat_DEF_TYPE(Cancel_ResponsePDU);

/* Type Converters */
static inline PyObject *PyAsnCancel_ResponsePDU_ToPython(Cancel_ResponsePDU_t *pSrc, PyObject *parent)
{
	return PyAsnUnsigned32_ToPython(pSrc, parent);
}
static inline int PyAsnCancel_ResponsePDU_FromPython(PyObject *pObj, Cancel_ResponsePDU_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Cancel_ResponsePDU, pObj, pDst);
	return PyAsnUnsigned32_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnCancel_ResponsePDU_ModSetupTypes(void);
void PyAsnCancel_ResponsePDU_ModClear(PyObject *);
int PyAsnCancel_ResponsePDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Cancel_ResponsePDU_PY_H_ */
