/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Cancel_RequestPDU_PY_H_
#define	_Cancel_RequestPDU_PY_H_


#include <Cancel-RequestPDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cancel-RequestPDU */
PyCompat_DEF_STRUCT(Cancel_RequestPDU);
PyCompat_DEF_TYPE(Cancel_RequestPDU);

/* Type Converters */
static inline PyObject *PyAsnCancel_RequestPDU_ToPython(Cancel_RequestPDU_t *pSrc, PyObject *parent)
{
	return PyAsnUnsigned32_ToPython(pSrc, parent);
}
static inline int PyAsnCancel_RequestPDU_FromPython(PyObject *pObj, Cancel_RequestPDU_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Cancel_RequestPDU, pObj, pDst);
	return PyAsnUnsigned32_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnCancel_RequestPDU_ModSetupTypes(void);
void PyAsnCancel_RequestPDU_ModClear(PyObject *);
int PyAsnCancel_RequestPDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Cancel_RequestPDU_PY_H_ */
