/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Cancel_RequestPDU_H_
#define	_Cancel_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cancel-RequestPDU */
typedef Unsigned32_t	 Cancel_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cancel_RequestPDU;
asn_struct_free_f Cancel_RequestPDU_free;
asn_struct_print_f Cancel_RequestPDU_print;
asn_constr_check_f Cancel_RequestPDU_constraint;
ber_type_decoder_f Cancel_RequestPDU_decode_ber;
der_type_encoder_f Cancel_RequestPDU_encode_der;
xer_type_decoder_f Cancel_RequestPDU_decode_xer;
xer_type_encoder_f Cancel_RequestPDU_encode_xer;
jer_type_encoder_f Cancel_RequestPDU_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Cancel_RequestPDU_H_ */
#include <asn_internal.h>
