/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Cancel_ErrorPDU_PY_H_
#define	_Cancel_ErrorPDU_PY_H_


#include <Cancel-ErrorPDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <ServiceError_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cancel-ErrorPDU */
PyCompat_DEF_STRUCT(Cancel_ErrorPDU);
PyCompat_DEF_TYPE(Cancel_ErrorPDU);

/* Type Converters */
int PyAsnCancel_ErrorPDU_FromPython(PyObject *pObj, Cancel_ErrorPDU_t *pDst);
PyObject *PyAsnCancel_ErrorPDU_ToPython(Cancel_ErrorPDU_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnCancel_ErrorPDU_ModSetupTypes(void);
void PyAsnCancel_ErrorPDU_ModClear(PyObject *);
int PyAsnCancel_ErrorPDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Cancel_ErrorPDU_PY_H_ */
