/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Cancel_ErrorPDU_H_
#define	_Cancel_ErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceError;

/* Cancel-ErrorPDU */
typedef struct Cancel_ErrorPDU {
	Unsigned32_t	 originalInvokeID;
	struct ServiceError	*serviceError;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cancel_ErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cancel_ErrorPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_Cancel_ErrorPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_Cancel_ErrorPDU_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceError.h"

#endif	/* _Cancel_ErrorPDU_H_ */
#include <asn_internal.h>
