/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ChangeAccessControl_Response_H_
#define	_ChangeAccessControl_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeAccessControl-Response */
typedef struct ChangeAccessControl_Response {
	Unsigned32_t	 numberMatched;
	Unsigned32_t	 numberChanged;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeAccessControl_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeAccessControl_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_ChangeAccessControl_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_ChangeAccessControl_Response_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeAccessControl_Response_H_ */
#include <asn_internal.h>
