/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ChangeAccessControl_Response_PY_H_
#define	_ChangeAccessControl_Response_PY_H_


#include <ChangeAccessControl-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeAccessControl-Response */
PyCompat_DEF_STRUCT(ChangeAccessControl_Response);
PyCompat_DEF_TYPE(ChangeAccessControl_Response);

/* Type Converters */
int PyAsnChangeAccessControl_Response_FromPython(PyObject *pObj, ChangeAccessControl_Response_t *pDst);
PyObject *PyAsnChangeAccessControl_Response_ToPython(ChangeAccessControl_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnChangeAccessControl_Response_ModSetupTypes(void);
void PyAsnChangeAccessControl_Response_ModClear(PyObject *);
int PyAsnChangeAccessControl_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeAccessControl_Response_PY_H_ */
