/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ChangeAccessControl_Error_PY_H_
#define	_ChangeAccessControl_Error_PY_H_


#include <ChangeAccessControl-Error.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeAccessControl-Error */
PyCompat_DEF_STRUCT(ChangeAccessControl_Error);
PyCompat_DEF_TYPE(ChangeAccessControl_Error);

/* Type Converters */
static inline PyObject *PyAsnChangeAccessControl_Error_ToPython(ChangeAccessControl_Error_t *pSrc, PyObject *parent)
{
	return PyAsnUnsigned32_ToPython(pSrc, parent);
}
static inline int PyAsnChangeAccessControl_Error_FromPython(PyObject *pObj, ChangeAccessControl_Error_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(ChangeAccessControl_Error, pObj, pDst);
	return PyAsnUnsigned32_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnChangeAccessControl_Error_ModSetupTypes(void);
void PyAsnChangeAccessControl_Error_ModClear(PyObject *);
int PyAsnChangeAccessControl_Error_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeAccessControl_Error_PY_H_ */
