/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Conclude_RequestPDU_PY_H_
#define	_Conclude_RequestPDU_PY_H_


#include <Conclude-RequestPDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Conclude-RequestPDU */
PyCompat_DEF_STRUCT(Conclude_RequestPDU);
PyCompat_DEF_TYPE(Conclude_RequestPDU);

/* Type Converters */
static inline PyObject *PyAsnConclude_RequestPDU_ToPython(Conclude_RequestPDU_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnConclude_RequestPDU_FromPython(PyObject *pObj, Conclude_RequestPDU_t *pDst)
{
	*pDst = (Conclude_RequestPDU_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnConclude_RequestPDU_ModSetupTypes(void);
void PyAsnConclude_RequestPDU_ModClear(PyObject *);
int PyAsnConclude_RequestPDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Conclude_RequestPDU_PY_H_ */
