/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Confirmed_ErrorPDU_PY_H_
#define	_Confirmed_ErrorPDU_PY_H_


#include <Confirmed-ErrorPDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <Unsigned32_Py.h>
#include <ServiceError_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Confirmed-ErrorPDU */
PyCompat_DEF_STRUCT(Confirmed_ErrorPDU);
PyCompat_DEF_TYPE(Confirmed_ErrorPDU);

/* Type Converters */
int PyAsnConfirmed_ErrorPDU_FromPython(PyObject *pObj, Confirmed_ErrorPDU_t *pDst);
PyObject *PyAsnConfirmed_ErrorPDU_ToPython(Confirmed_ErrorPDU_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnConfirmed_ErrorPDU_ModSetupTypes(void);
void PyAsnConfirmed_ErrorPDU_ModClear(PyObject *);
int PyAsnConfirmed_ErrorPDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Confirmed_ErrorPDU_PY_H_ */
