/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Confirmed_ResponsePDU_H_
#define	_Confirmed_ResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConfirmedServiceResponse;
struct Response_Detail;

/* Confirmed-ResponsePDU */
typedef struct Confirmed_ResponsePDU {
	Unsigned32_t	 invokeID;
	struct ConfirmedServiceResponse	*service;
	struct Response_Detail	*service_ext;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Confirmed_ResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Confirmed_ResponsePDU;
extern asn_SEQUENCE_specifics_t asn_SPC_Confirmed_ResponsePDU_specs_1;
extern asn_TYPE_member_t asn_MBR_Confirmed_ResponsePDU_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConfirmedServiceResponse.h"
#include "Response-Detail.h"

#endif	/* _Confirmed_ResponsePDU_H_ */
#include <asn_internal.h>
