/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ConfirmedServiceResponse_H_
#define	_ConfirmedServiceResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Rename-Response.h"
#include "DefineNamedVariable-Response.h"
#include "DefineScatteredAccess-Response.h"
#include "DefineNamedVariableList-Response.h"
#include "DefineNamedType-Response.h"
#include "Input-Response.h"
#include "Output-Response.h"
#include "RelinquishControl-Response.h"
#include "DefineSemaphore-Response.h"
#include "DeleteSemaphore-Response.h"
#include "InitiateDownloadSequence-Response.h"
#include "TerminateDownloadSequence-Response.h"
#include "TerminateUploadSequence-Response.h"
#include "RequestDomainDownload-Response.h"
#include "RequestDomainUpload-Response.h"
#include "LoadDomainContent-Response.h"
#include "StoreDomainContent-Response.h"
#include "DeleteDomain-Response.h"
#include "CreateProgramInvocation-Response.h"
#include "DeleteProgramInvocation-Response.h"
#include "Start-Response.h"
#include "Stop-Response.h"
#include "Resume-Response.h"
#include "Reset-Response.h"
#include "Kill-Response.h"
#include "ObtainFile-Response.h"
#include "DefineEventCondition-Response.h"
#include "DeleteEventCondition-Response.h"
#include "AlterEventConditionMonitoring-Response.h"
#include "TriggerEvent-Response.h"
#include "DefineEventAction-Response.h"
#include "DeleteEventAction-Response.h"
#include "ReportEventActionStatus-Response.h"
#include "DefineEventEnrollment-Response.h"
#include "DeleteEventEnrollment-Response.h"
#include "AcknowledgeEventNotification-Response.h"
#include "WriteJournal-Response.h"
#include "InitializeJournal-Response.h"
#include "CreateJournal-Response.h"
#include "DeleteJournal-Response.h"
#include "FileClose-Response.h"
#include "FileRename-Response.h"
#include "FileDelete-Response.h"
#include "DefineAccessControlList-Response.h"
#include "DeleteAccessControlList-Response.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfirmedServiceResponse_PR {
	ConfirmedServiceResponse_PR_NOTHING,	/* No components present */
	ConfirmedServiceResponse_PR_status,
	ConfirmedServiceResponse_PR_getNameList,
	ConfirmedServiceResponse_PR_identify,
	ConfirmedServiceResponse_PR_rename,
	ConfirmedServiceResponse_PR_read,
	ConfirmedServiceResponse_PR_write,
	ConfirmedServiceResponse_PR_getVariableAccessAttributes,
	ConfirmedServiceResponse_PR_defineNamedVariable,
	ConfirmedServiceResponse_PR_defineScatteredAccess,
	ConfirmedServiceResponse_PR_getScatteredAccessAttributes,
	ConfirmedServiceResponse_PR_deleteVariableAccess,
	ConfirmedServiceResponse_PR_defineNamedVariableList,
	ConfirmedServiceResponse_PR_getNamedVariableListAttributes,
	ConfirmedServiceResponse_PR_deleteNamedVariableList,
	ConfirmedServiceResponse_PR_defineNamedType,
	ConfirmedServiceResponse_PR_getNamedTypeAttributes,
	ConfirmedServiceResponse_PR_deleteNamedType,
	ConfirmedServiceResponse_PR_input,
	ConfirmedServiceResponse_PR_output,
	ConfirmedServiceResponse_PR_takeControl,
	ConfirmedServiceResponse_PR_relinquishControl,
	ConfirmedServiceResponse_PR_defineSemaphore,
	ConfirmedServiceResponse_PR_deleteSemaphore,
	ConfirmedServiceResponse_PR_reportSemaphoreStatus,
	ConfirmedServiceResponse_PR_reportPoolSemaphoreStatus,
	ConfirmedServiceResponse_PR_reportSemaphoreEntryStatus,
	ConfirmedServiceResponse_PR_initiateDownloadSequence,
	ConfirmedServiceResponse_PR_downloadSegment,
	ConfirmedServiceResponse_PR_terminateDownloadSequence,
	ConfirmedServiceResponse_PR_initiateUploadSequence,
	ConfirmedServiceResponse_PR_uploadSegment,
	ConfirmedServiceResponse_PR_terminateUploadSequence,
	ConfirmedServiceResponse_PR_requestDomainDownload,
	ConfirmedServiceResponse_PR_requestDomainUpload,
	ConfirmedServiceResponse_PR_loadDomainContent,
	ConfirmedServiceResponse_PR_storeDomainContent,
	ConfirmedServiceResponse_PR_deleteDomain,
	ConfirmedServiceResponse_PR_getDomainAttributes,
	ConfirmedServiceResponse_PR_createProgramInvocation,
	ConfirmedServiceResponse_PR_deleteProgramInvocation,
	ConfirmedServiceResponse_PR_start,
	ConfirmedServiceResponse_PR_stop,
	ConfirmedServiceResponse_PR_resume,
	ConfirmedServiceResponse_PR_reset,
	ConfirmedServiceResponse_PR_kill,
	ConfirmedServiceResponse_PR_getProgramInvocationAttributes,
	ConfirmedServiceResponse_PR_obtainFile,
	ConfirmedServiceResponse_PR_defineEventCondition,
	ConfirmedServiceResponse_PR_deleteEventCondition,
	ConfirmedServiceResponse_PR_getEventConditionAttributes,
	ConfirmedServiceResponse_PR_reportEventConditionStatus,
	ConfirmedServiceResponse_PR_alterEventConditionMonitoring,
	ConfirmedServiceResponse_PR_triggerEvent,
	ConfirmedServiceResponse_PR_defineEventAction,
	ConfirmedServiceResponse_PR_deleteEventAction,
	ConfirmedServiceResponse_PR_getEventActionAttributes,
	ConfirmedServiceResponse_PR_reportEventActionStatus,
	ConfirmedServiceResponse_PR_defineEventEnrollment,
	ConfirmedServiceResponse_PR_deleteEventEnrollment,
	ConfirmedServiceResponse_PR_alterEventEnrollment,
	ConfirmedServiceResponse_PR_reportEventEnrollmentStatus,
	ConfirmedServiceResponse_PR_getEventEnrollmentAttributes,
	ConfirmedServiceResponse_PR_acknowledgeEventNotification,
	ConfirmedServiceResponse_PR_getAlarmSummary,
	ConfirmedServiceResponse_PR_getAlarmEnrollmentSummary,
	ConfirmedServiceResponse_PR_readJournal,
	ConfirmedServiceResponse_PR_writeJournal,
	ConfirmedServiceResponse_PR_initializeJournal,
	ConfirmedServiceResponse_PR_reportJournalStatus,
	ConfirmedServiceResponse_PR_createJournal,
	ConfirmedServiceResponse_PR_deleteJournal,
	ConfirmedServiceResponse_PR_getCapabilityList,
	ConfirmedServiceResponse_PR_fileOpen,
	ConfirmedServiceResponse_PR_fileRead,
	ConfirmedServiceResponse_PR_fileClose,
	ConfirmedServiceResponse_PR_fileRename,
	ConfirmedServiceResponse_PR_fileDelete,
	ConfirmedServiceResponse_PR_fileDirectory,
	ConfirmedServiceResponse_PR_additionalService,
	ConfirmedServiceResponse_PR_getDataExchangeAttributes,
	ConfirmedServiceResponse_PR_exchangeData,
	ConfirmedServiceResponse_PR_defineAccessControlList,
	ConfirmedServiceResponse_PR_getAccessControlListAttributes,
	ConfirmedServiceResponse_PR_reportAccessControlledObjects,
	ConfirmedServiceResponse_PR_deleteAccessControlList,
	ConfirmedServiceResponse_PR_changeAccessControl
} ConfirmedServiceResponse_PR;

/* Forward declarations */
struct Status_Response;
struct GetNameList_Response;
struct Identify_Response;
struct Read_Response;
struct Write_Response;
struct GetVariableAccessAttributes_Response;
struct GetScatteredAccessAttributes_Response;
struct DeleteVariableAccess_Response;
struct GetNamedVariableListAttributes_Response;
struct DeleteNamedVariableList_Response;
struct GetNamedTypeAttributes_Response;
struct DeleteNamedType_Response;
struct TakeControl_Response;
struct ReportSemaphoreStatus_Response;
struct ReportPoolSemaphoreStatus_Response;
struct ReportSemaphoreEntryStatus_Response;
struct DownloadSegment_Response;
struct InitiateUploadSequence_Response;
struct UploadSegment_Response;
struct GetDomainAttributes_Response;
struct GetProgramInvocationAttributes_Response;
struct GetEventConditionAttributes_Response;
struct ReportEventConditionStatus_Response;
struct GetEventActionAttributes_Response;
struct AlterEventEnrollment_Response;
struct ReportEventEnrollmentStatus_Response;
struct GetEventEnrollmentAttributes_Response;
struct GetAlarmSummary_Response;
struct GetAlarmEnrollmentSummary_Response;
struct ReadJournal_Response;
struct ReportJournalStatus_Response;
struct GetCapabilityList_Response;
struct FileOpen_Response;
struct FileRead_Response;
struct FileDirectory_Response;
struct AdditionalService_Response;
struct GetDataExchangeAttributes_Response;
struct ExchangeData_Response;
struct GetAccessControlListAttributes_Response;
struct ReportAccessControlledObjects_Response;
struct ChangeAccessControl_Response;
struct StatusResponse;

/* ConfirmedServiceResponse */
typedef struct ConfirmedServiceResponse {
	ConfirmedServiceResponse_PR present;
	union ConfirmedServiceResponse_u {
		struct StatusResponse	*status;
		struct GetNameList_Response	*getNameList;
		struct Identify_Response	*identify;
		Rename_Response_t	 rename;
		struct Read_Response	*read;
		struct Write_Response	*write;
		struct GetVariableAccessAttributes_Response	*getVariableAccessAttributes;
		DefineNamedVariable_Response_t	 defineNamedVariable;
		DefineScatteredAccess_Response_t	 defineScatteredAccess;
		struct GetScatteredAccessAttributes_Response	*getScatteredAccessAttributes;
		struct DeleteVariableAccess_Response	*deleteVariableAccess;
		DefineNamedVariableList_Response_t	 defineNamedVariableList;
		struct GetNamedVariableListAttributes_Response	*getNamedVariableListAttributes;
		struct DeleteNamedVariableList_Response	*deleteNamedVariableList;
		DefineNamedType_Response_t	 defineNamedType;
		struct GetNamedTypeAttributes_Response	*getNamedTypeAttributes;
		struct DeleteNamedType_Response	*deleteNamedType;
		Input_Response_t	 input;
		Output_Response_t	 output;
		struct TakeControl_Response	*takeControl;
		RelinquishControl_Response_t	 relinquishControl;
		DefineSemaphore_Response_t	 defineSemaphore;
		DeleteSemaphore_Response_t	 deleteSemaphore;
		struct ReportSemaphoreStatus_Response	*reportSemaphoreStatus;
		struct ReportPoolSemaphoreStatus_Response	*reportPoolSemaphoreStatus;
		struct ReportSemaphoreEntryStatus_Response	*reportSemaphoreEntryStatus;
		InitiateDownloadSequence_Response_t	 initiateDownloadSequence;
		struct DownloadSegment_Response	*downloadSegment;
		TerminateDownloadSequence_Response_t	 terminateDownloadSequence;
		struct InitiateUploadSequence_Response	*initiateUploadSequence;
		struct UploadSegment_Response	*uploadSegment;
		TerminateUploadSequence_Response_t	 terminateUploadSequence;
		RequestDomainDownload_Response_t	 requestDomainDownload;
		RequestDomainUpload_Response_t	 requestDomainUpload;
		LoadDomainContent_Response_t	 loadDomainContent;
		StoreDomainContent_Response_t	 storeDomainContent;
		DeleteDomain_Response_t	 deleteDomain;
		struct GetDomainAttributes_Response	*getDomainAttributes;
		CreateProgramInvocation_Response_t	 createProgramInvocation;
		DeleteProgramInvocation_Response_t	 deleteProgramInvocation;
		Start_Response_t	 start;
		Stop_Response_t	 stop;
		Resume_Response_t	 resume;
		Reset_Response_t	 reset;
		Kill_Response_t	 kill;
		struct GetProgramInvocationAttributes_Response	*getProgramInvocationAttributes;
		ObtainFile_Response_t	 obtainFile;
		DefineEventCondition_Response_t	 defineEventCondition;
		DeleteEventCondition_Response_t	 deleteEventCondition;
		struct GetEventConditionAttributes_Response	*getEventConditionAttributes;
		struct ReportEventConditionStatus_Response	*reportEventConditionStatus;
		AlterEventConditionMonitoring_Response_t	 alterEventConditionMonitoring;
		TriggerEvent_Response_t	 triggerEvent;
		DefineEventAction_Response_t	 defineEventAction;
		DeleteEventAction_Response_t	 deleteEventAction;
		struct GetEventActionAttributes_Response	*getEventActionAttributes;
		ReportEventActionStatus_Response_t	 reportEventActionStatus;
		DefineEventEnrollment_Response_t	 defineEventEnrollment;
		DeleteEventEnrollment_Response_t	 deleteEventEnrollment;
		struct AlterEventEnrollment_Response	*alterEventEnrollment;
		struct ReportEventEnrollmentStatus_Response	*reportEventEnrollmentStatus;
		struct GetEventEnrollmentAttributes_Response	*getEventEnrollmentAttributes;
		AcknowledgeEventNotification_Response_t	 acknowledgeEventNotification;
		struct GetAlarmSummary_Response	*getAlarmSummary;
		struct GetAlarmEnrollmentSummary_Response	*getAlarmEnrollmentSummary;
		struct ReadJournal_Response	*readJournal;
		WriteJournal_Response_t	 writeJournal;
		InitializeJournal_Response_t	 initializeJournal;
		struct ReportJournalStatus_Response	*reportJournalStatus;
		CreateJournal_Response_t	 createJournal;
		DeleteJournal_Response_t	 deleteJournal;
		struct GetCapabilityList_Response	*getCapabilityList;
		struct FileOpen_Response	*fileOpen;
		struct FileRead_Response	*fileRead;
		FileClose_Response_t	 fileClose;
		FileRename_Response_t	 fileRename;
		FileDelete_Response_t	 fileDelete;
		struct FileDirectory_Response	*fileDirectory;
		struct AdditionalService_Response	*additionalService;
		struct GetDataExchangeAttributes_Response	*getDataExchangeAttributes;
		struct ExchangeData_Response	*exchangeData;
		DefineAccessControlList_Response_t	 defineAccessControlList;
		struct GetAccessControlListAttributes_Response	*getAccessControlListAttributes;
		struct ReportAccessControlledObjects_Response	*reportAccessControlledObjects;
		DeleteAccessControlList_Response_t	 deleteAccessControlList;
		struct ChangeAccessControl_Response	*changeAccessControl;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmedServiceResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmedServiceResponse;
extern asn_CHOICE_specifics_t asn_SPC_ConfirmedServiceResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfirmedServiceResponse_1[86];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Status-Response.h"
#include "GetNameList-Response.h"
#include "Identify-Response.h"
#include "Read-Response.h"
#include "Write-Response.h"
#include "GetVariableAccessAttributes-Response.h"
#include "GetScatteredAccessAttributes-Response.h"
#include "DeleteVariableAccess-Response.h"
#include "GetNamedVariableListAttributes-Response.h"
#include "DeleteNamedVariableList-Response.h"
#include "GetNamedTypeAttributes-Response.h"
#include "DeleteNamedType-Response.h"
#include "TakeControl-Response.h"
#include "ReportSemaphoreStatus-Response.h"
#include "ReportPoolSemaphoreStatus-Response.h"
#include "ReportSemaphoreEntryStatus-Response.h"
#include "DownloadSegment-Response.h"
#include "InitiateUploadSequence-Response.h"
#include "UploadSegment-Response.h"
#include "GetDomainAttributes-Response.h"
#include "GetProgramInvocationAttributes-Response.h"
#include "GetEventConditionAttributes-Response.h"
#include "ReportEventConditionStatus-Response.h"
#include "GetEventActionAttributes-Response.h"
#include "AlterEventEnrollment-Response.h"
#include "ReportEventEnrollmentStatus-Response.h"
#include "GetEventEnrollmentAttributes-Response.h"
#include "GetAlarmSummary-Response.h"
#include "GetAlarmEnrollmentSummary-Response.h"
#include "ReadJournal-Response.h"
#include "ReportJournalStatus-Response.h"
#include "GetCapabilityList-Response.h"
#include "FileOpen-Response.h"
#include "FileRead-Response.h"
#include "FileDirectory-Response.h"
#include "AdditionalService-Response.h"
#include "GetDataExchangeAttributes-Response.h"
#include "ExchangeData-Response.h"
#include "GetAccessControlListAttributes-Response.h"
#include "ReportAccessControlledObjects-Response.h"
#include "ChangeAccessControl-Response.h"

#endif	/* _ConfirmedServiceResponse_H_ */
#include <asn_internal.h>
