/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Confirmed_ErrorPDU_H_
#define	_Confirmed_ErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceError;

/* Confirmed-ErrorPDU */
typedef struct Confirmed_ErrorPDU {
	Unsigned32_t	 invokeID;
	Unsigned32_t	*modifierPosition;	/* OPTIONAL */
	struct ServiceError	*serviceError;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Confirmed_ErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Confirmed_ErrorPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_Confirmed_ErrorPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_Confirmed_ErrorPDU_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceError.h"

#endif	/* _Confirmed_ErrorPDU_H_ */
#include <asn_internal.h>
