/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Confirmed_RequestPDU_H_
#define	_Confirmed_RequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConfirmedServiceRequest;
struct Request_Detail;
struct Modifier;

/* Confirmed-RequestPDU */
typedef struct Confirmed_RequestPDU {
	Unsigned32_t	 invokeID;
	struct Confirmed_RequestPDU__listOfModifiers {
		A_SEQUENCE_OF(struct Modifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfModifiers;
	struct ConfirmedServiceRequest	*service;
	struct Request_Detail	*service_ext;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Confirmed_RequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Confirmed_RequestPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_Confirmed_RequestPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_Confirmed_RequestPDU_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConfirmedServiceRequest.h"
#include "Request-Detail.h"
#include "Modifier.h"

#endif	/* _Confirmed_RequestPDU_H_ */
#include <asn_internal.h>
