/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CreateJournal_Request_H_
#define	_CreateJournal_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* CreateJournal-Request */
typedef struct CreateJournal_Request {
	struct ObjectName	*journalName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateJournal_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateJournal_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_CreateJournal_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_CreateJournal_Request_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _CreateJournal_Request_H_ */
#include <asn_internal.h>
