/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CreateJournal_Request_PY_H_
#define	_CreateJournal_Request_PY_H_


#include <CreateJournal-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateJournal-Request */
PyCompat_DEF_STRUCT(CreateJournal_Request);
PyCompat_DEF_TYPE(CreateJournal_Request);

/* Type Converters */
int PyAsnCreateJournal_Request_FromPython(PyObject *pObj, CreateJournal_Request_t *pDst);
PyObject *PyAsnCreateJournal_Request_ToPython(CreateJournal_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnCreateJournal_Request_ModSetupTypes(void);
void PyAsnCreateJournal_Request_ModClear(PyObject *);
int PyAsnCreateJournal_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _CreateJournal_Request_PY_H_ */
