/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CreateJournal_Response_PY_H_
#define	_CreateJournal_Response_PY_H_


#include <CreateJournal-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateJournal-Response */
PyCompat_DEF_STRUCT(CreateJournal_Response);
PyCompat_DEF_TYPE(CreateJournal_Response);

/* Type Converters */
static inline PyObject *PyAsnCreateJournal_Response_ToPython(CreateJournal_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnCreateJournal_Response_FromPython(PyObject *pObj, CreateJournal_Response_t *pDst)
{
	*pDst = (CreateJournal_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnCreateJournal_Response_ModSetupTypes(void);
void PyAsnCreateJournal_Response_ModClear(PyObject *);
int PyAsnCreateJournal_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _CreateJournal_Response_PY_H_ */
