/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CreateUnitControl_Response_PY_H_
#define	_CreateUnitControl_Response_PY_H_


#include <CreateUnitControl-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CreateUnitControl-Response */
PyCompat_DEF_STRUCT(CreateUnitControl_Response);
PyCompat_DEF_TYPE(CreateUnitControl_Response);

/* Type Converters */
static inline PyObject *PyAsnCreateUnitControl_Response_ToPython(CreateUnitControl_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnCreateUnitControl_Response_FromPython(PyObject *pObj, CreateUnitControl_Response_t *pDst)
{
	*pDst = (CreateUnitControl_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnCreateUnitControl_Response_ModSetupTypes(void);
void PyAsnCreateUnitControl_Response_ModClear(PyObject *);
int PyAsnCreateUnitControl_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _CreateUnitControl_Response_PY_H_ */
