/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CS_DefineEventCondition_Request_PY_H_
#define	_CS_DefineEventCondition_Request_PY_H_


#include <CS-DefineEventCondition-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CS-DefineEventCondition-Request */
PyCompat_DEF_STRUCT(CS_DefineEventCondition_Request);
PyCompat_DEF_TYPE(CS_DefineEventCondition_Request);
PyCompat_DEF_ENUM(CS_DefineEventCondition_Request_PRESENT);

/* Type Converters */
int PyAsnCS_DefineEventCondition_Request_FromPython(PyObject *pObj, CS_DefineEventCondition_Request_t *pDst);
PyObject *PyAsnCS_DefineEventCondition_Request_ToPython(CS_DefineEventCondition_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnCS_DefineEventCondition_Request_ModSetupTypes(void);
void PyAsnCS_DefineEventCondition_Request_ModClear(PyObject *);
int PyAsnCS_DefineEventCondition_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _CS_DefineEventCondition_Request_PY_H_ */
