/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CS_DefineEventEnrollment_Request_H_
#define	_CS_DefineEventEnrollment_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NativeInteger.h>
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CS_DefineEventEnrollment_Request_PR {
	CS_DefineEventEnrollment_Request_PR_NOTHING,	/* No components present */
	CS_DefineEventEnrollment_Request_PR_string,
	CS_DefineEventEnrollment_Request_PR_index,
	CS_DefineEventEnrollment_Request_PR_noEnhancement
} CS_DefineEventEnrollment_Request_PR;

/* CS-DefineEventEnrollment-Request */
typedef struct CS_DefineEventEnrollment_Request {
	CS_DefineEventEnrollment_Request_PR present;
	union CS_DefineEventEnrollment_Request_u {
		VisibleString_t	 string;
		long	 index;
		NULL_t	 noEnhancement;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CS_DefineEventEnrollment_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CS_DefineEventEnrollment_Request;
extern asn_CHOICE_specifics_t asn_SPC_CS_DefineEventEnrollment_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_CS_DefineEventEnrollment_Request_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CS_DefineEventEnrollment_Request_H_ */
#include <asn_internal.h>
