/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CS_EventNotification_PY_H_
#define	_CS_EventNotification_PY_H_


#include <CS-EventNotification.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CS-EventNotification */
PyCompat_DEF_STRUCT(CS_EventNotification);
PyCompat_DEF_TYPE(CS_EventNotification);
PyCompat_DEF_ENUM(CS_EventNotification_PRESENT);

/* Type Converters */
int PyAsnCS_EventNotification_FromPython(PyObject *pObj, CS_EventNotification_t *pDst);
PyObject *PyAsnCS_EventNotification_ToPython(CS_EventNotification_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnCS_EventNotification_ModSetupTypes(void);
void PyAsnCS_EventNotification_ModClear(PyObject *);
int PyAsnCS_EventNotification_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _CS_EventNotification_PY_H_ */
