/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <CS-GetEventConditionAttributes-Response.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_groupPriorityOverride __attribute__((weak, alias("asn_DEF_groupPriorityOverride_2")));
#else
static asn_TYPE_descriptor_t asn_DEF_groupPriorityOverride_2;
static asn_TYPE_descriptor_t asn_DEF_groupPriorityOverride;
__attribute__((constructor)) static void asn_DEF_groupPriorityOverride_2_alias_init(void) {
	asn_DEF_groupPriorityOverride = asn_DEF_groupPriorityOverride_2;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfReferencingECL __attribute__((weak, alias("asn_DEF_listOfReferencingECL_5")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfReferencingECL_5;
static asn_TYPE_descriptor_t asn_DEF_listOfReferencingECL;
__attribute__((constructor)) static void asn_DEF_listOfReferencingECL_5_alias_init(void) {
	asn_DEF_listOfReferencingECL = asn_DEF_listOfReferencingECL_5;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_displayEnhancement __attribute__((weak, alias("asn_DEF_displayEnhancement_7")));
#else
static asn_TYPE_descriptor_t asn_DEF_displayEnhancement_7;
static asn_TYPE_descriptor_t asn_DEF_displayEnhancement;
__attribute__((constructor)) static void asn_DEF_displayEnhancement_7_alias_init(void) {
	asn_DEF_displayEnhancement = asn_DEF_displayEnhancement_7;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_CS_GetEventConditionAttributes_Response__groupPriorityOverride_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetEventConditionAttributes_Response__groupPriorityOverride, choice.priority),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Priority,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"priority"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetEventConditionAttributes_Response__groupPriorityOverride, choice.undefined),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"undefined"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_groupPriorityOverride_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* priority */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* undefined */
};
static asn_CHOICE_specifics_t asn_SPC_groupPriorityOverride_specs_2 = {
	sizeof(struct CS_GetEventConditionAttributes_Response__groupPriorityOverride),
	offsetof(struct CS_GetEventConditionAttributes_Response__groupPriorityOverride, _asn_ctx),
	offsetof(struct CS_GetEventConditionAttributes_Response__groupPriorityOverride, present),
	sizeof(((struct CS_GetEventConditionAttributes_Response__groupPriorityOverride *)0)->present),
	asn_MAP_groupPriorityOverride_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_groupPriorityOverride_2 = {
	"groupPriorityOverride",
	"groupPriorityOverride",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_GetEventConditionAttributes_Response__groupPriorityOverride_2,
	2,	/* Elements count */
	&asn_SPC_groupPriorityOverride_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_GetEventConditionAttributes_Response__listOfReferencingECL_5[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfReferencingECL_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfReferencingECL_specs_5 = {
	sizeof(struct CS_GetEventConditionAttributes_Response__listOfReferencingECL),
	offsetof(struct CS_GetEventConditionAttributes_Response__listOfReferencingECL, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfReferencingECL_5 = {
	"listOfReferencingECL",
	"listOfReferencingECL",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfReferencingECL_tags_5,
	sizeof(asn_DEF_listOfReferencingECL_tags_5)
		/sizeof(asn_DEF_listOfReferencingECL_tags_5[0]) - 1, /* 1 */
	asn_DEF_listOfReferencingECL_tags_5,	/* Same as above */
	sizeof(asn_DEF_listOfReferencingECL_tags_5)
		/sizeof(asn_DEF_listOfReferencingECL_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_CS_GetEventConditionAttributes_Response__listOfReferencingECL_5,
	1,	/* Single element */
	&asn_SPC_listOfReferencingECL_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_GetEventConditionAttributes_Response__displayEnhancement_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetEventConditionAttributes_Response__displayEnhancement, choice.string),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetEventConditionAttributes_Response__displayEnhancement, choice.index),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"index"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetEventConditionAttributes_Response__displayEnhancement, choice.noEnhancement),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"noEnhancement"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_displayEnhancement_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* string */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* index */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* noEnhancement */
};
static asn_CHOICE_specifics_t asn_SPC_displayEnhancement_specs_7 = {
	sizeof(struct CS_GetEventConditionAttributes_Response__displayEnhancement),
	offsetof(struct CS_GetEventConditionAttributes_Response__displayEnhancement, _asn_ctx),
	offsetof(struct CS_GetEventConditionAttributes_Response__displayEnhancement, present),
	sizeof(((struct CS_GetEventConditionAttributes_Response__displayEnhancement *)0)->present),
	asn_MAP_displayEnhancement_tag2el_7,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_displayEnhancement_7 = {
	"displayEnhancement",
	"displayEnhancement",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_GetEventConditionAttributes_Response__displayEnhancement_7,
	3,	/* Elements count */
	&asn_SPC_displayEnhancement_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CS_GetEventConditionAttributes_Response_1[] = {
	{ ATF_POINTER, 2, offsetof(struct CS_GetEventConditionAttributes_Response, groupPriorityOverride),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_groupPriorityOverride_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"groupPriorityOverride"
		},
	{ ATF_POINTER, 1, offsetof(struct CS_GetEventConditionAttributes_Response, listOfReferencingECL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfReferencingECL_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfReferencingECL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetEventConditionAttributes_Response, displayEnhancement),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_displayEnhancement_7,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"displayEnhancement"
		},
};
static const int asn_MAP_CS_GetEventConditionAttributes_Response_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_CS_GetEventConditionAttributes_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CS_GetEventConditionAttributes_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* groupPriorityOverride */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfReferencingECL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* displayEnhancement */
};
asn_SEQUENCE_specifics_t asn_SPC_CS_GetEventConditionAttributes_Response_specs_1 = {
	sizeof(struct CS_GetEventConditionAttributes_Response),
	offsetof(struct CS_GetEventConditionAttributes_Response, _asn_ctx),
	asn_MAP_CS_GetEventConditionAttributes_Response_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_CS_GetEventConditionAttributes_Response_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CS_GetEventConditionAttributes_Response = {
	"CS-GetEventConditionAttributes-Response",
	"CS-GetEventConditionAttributes-Response",
	&asn_OP_SEQUENCE,
	asn_DEF_CS_GetEventConditionAttributes_Response_tags_1,
	sizeof(asn_DEF_CS_GetEventConditionAttributes_Response_tags_1)
		/sizeof(asn_DEF_CS_GetEventConditionAttributes_Response_tags_1[0]), /* 1 */
	asn_DEF_CS_GetEventConditionAttributes_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_CS_GetEventConditionAttributes_Response_tags_1)
		/sizeof(asn_DEF_CS_GetEventConditionAttributes_Response_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CS_GetEventConditionAttributes_Response_1,
	3,	/* Elements count */
	&asn_SPC_CS_GetEventConditionAttributes_Response_specs_1	/* Additional specs */
};

