/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <CS-GetProgramInvocationAttributes-Response.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_controlledPI __attribute__((weak, alias("asn_DEF_controlledPI_5")));
#else
static asn_TYPE_descriptor_t asn_DEF_controlledPI_5;
static asn_TYPE_descriptor_t asn_DEF_controlledPI;
__attribute__((constructor)) static void asn_DEF_controlledPI_5_alias_init(void) {
	asn_DEF_controlledPI = asn_DEF_controlledPI_5;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_runningMode __attribute__((weak, alias("asn_DEF_runningMode_8")));
#else
static asn_TYPE_descriptor_t asn_DEF_runningMode_8;
static asn_TYPE_descriptor_t asn_DEF_runningMode;
__attribute__((constructor)) static void asn_DEF_runningMode_8_alias_init(void) {
	asn_DEF_runningMode = asn_DEF_runningMode_8;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_controlling __attribute__((weak, alias("asn_DEF_controlling_4")));
#else
static asn_TYPE_descriptor_t asn_DEF_controlling_4;
static asn_TYPE_descriptor_t asn_DEF_controlling;
__attribute__((constructor)) static void asn_DEF_controlling_4_alias_init(void) {
	asn_DEF_controlling = asn_DEF_controlling_4;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_controlled __attribute__((weak, alias("asn_DEF_controlled_12")));
#else
static asn_TYPE_descriptor_t asn_DEF_controlled_12;
static asn_TYPE_descriptor_t asn_DEF_controlled;
__attribute__((constructor)) static void asn_DEF_controlled_12_alias_init(void) {
	asn_DEF_controlled = asn_DEF_controlled_12;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_control __attribute__((weak, alias("asn_DEF_control_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_control_3;
static asn_TYPE_descriptor_t asn_DEF_control;
__attribute__((constructor)) static void asn_DEF_control_3_alias_init(void) {
	asn_DEF_control = asn_DEF_control_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlling__controlledPI_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_Identifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_controlledPI_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_controlledPI_specs_5 = {
	sizeof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__controlledPI),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__controlledPI, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlledPI_5 = {
	"controlledPI",
	"controlledPI",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_controlledPI_tags_5,
	sizeof(asn_DEF_controlledPI_tags_5)
		/sizeof(asn_DEF_controlledPI_tags_5[0]) - 1, /* 1 */
	asn_DEF_controlledPI_tags_5,	/* Same as above */
	sizeof(asn_DEF_controlledPI_tags_5)
		/sizeof(asn_DEF_controlledPI_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlling__controlledPI_5,
	1,	/* Single element */
	&asn_SPC_controlledPI_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode, choice.freeRunning),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"freeRunning"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode, choice.cycleLimited),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cycleLimited"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode, choice.stepLimited),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"stepLimited"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_runningMode_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* freeRunning */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cycleLimited */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* stepLimited */
};
static asn_CHOICE_specifics_t asn_SPC_runningMode_specs_8 = {
	sizeof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode, _asn_ctx),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode, present),
	sizeof(((struct CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode *)0)->present),
	asn_MAP_runningMode_tag2el_8,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_runningMode_8 = {
	"runningMode",
	"runningMode",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlling__runningMode_8,
	3,	/* Elements count */
	&asn_SPC_runningMode_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlling_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling, controlledPI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_controlledPI_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"controlledPI"
		},
	{ ATF_POINTER, 1, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling, programLocation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"programLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling, runningMode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_runningMode_8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"runningMode"
		},
};
static const int asn_MAP_controlling_oms_4[] = { 1 };
static const ber_tlv_tag_t asn_DEF_controlling_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_controlling_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* controlledPI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* programLocation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* runningMode */
};
static asn_SEQUENCE_specifics_t asn_SPC_controlling_specs_4 = {
	sizeof(struct CS_GetProgramInvocationAttributes_Response__control__controlling),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlling, _asn_ctx),
	asn_MAP_controlling_tag2el_4,
	3,	/* Count of tags in the map */
	asn_MAP_controlling_oms_4,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlling_4 = {
	"controlling",
	"controlling",
	&asn_OP_SEQUENCE,
	asn_DEF_controlling_tags_4,
	sizeof(asn_DEF_controlling_tags_4)
		/sizeof(asn_DEF_controlling_tags_4[0]) - 1, /* 1 */
	asn_DEF_controlling_tags_4,	/* Same as above */
	sizeof(asn_DEF_controlling_tags_4)
		/sizeof(asn_DEF_controlling_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlling_4,
	3,	/* Elements count */
	&asn_SPC_controlling_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlled_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlled, choice.controllingPI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"controllingPI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlled, choice.none),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"none"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_controlled_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* controllingPI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* none */
};
static asn_CHOICE_specifics_t asn_SPC_controlled_specs_12 = {
	sizeof(struct CS_GetProgramInvocationAttributes_Response__control__controlled),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlled, _asn_ctx),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control__controlled, present),
	sizeof(((struct CS_GetProgramInvocationAttributes_Response__control__controlled *)0)->present),
	asn_MAP_controlled_tag2el_12,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlled_12 = {
	"controlled",
	"controlled",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_GetProgramInvocationAttributes_Response__control__controlled_12,
	2,	/* Elements count */
	&asn_SPC_controlled_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_GetProgramInvocationAttributes_Response__control_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control, choice.controlling),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_controlling_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"controlling"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control, choice.controlled),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_controlled_12,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"controlled"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response__control, choice.normal),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"normal"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_control_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* controlling */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* controlled */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* normal */
};
static asn_CHOICE_specifics_t asn_SPC_control_specs_3 = {
	sizeof(struct CS_GetProgramInvocationAttributes_Response__control),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control, _asn_ctx),
	offsetof(struct CS_GetProgramInvocationAttributes_Response__control, present),
	sizeof(((struct CS_GetProgramInvocationAttributes_Response__control *)0)->present),
	asn_MAP_control_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_control_3 = {
	"control",
	"control",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_GetProgramInvocationAttributes_Response__control_3,
	3,	/* Elements count */
	&asn_SPC_control_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CS_GetProgramInvocationAttributes_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response, errorCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"errorCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_GetProgramInvocationAttributes_Response, control),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_control_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"control"
		},
};
static const ber_tlv_tag_t asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CS_GetProgramInvocationAttributes_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* errorCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* control */
};
asn_SEQUENCE_specifics_t asn_SPC_CS_GetProgramInvocationAttributes_Response_specs_1 = {
	sizeof(struct CS_GetProgramInvocationAttributes_Response),
	offsetof(struct CS_GetProgramInvocationAttributes_Response, _asn_ctx),
	asn_MAP_CS_GetProgramInvocationAttributes_Response_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CS_GetProgramInvocationAttributes_Response = {
	"CS-GetProgramInvocationAttributes-Response",
	"CS-GetProgramInvocationAttributes-Response",
	&asn_OP_SEQUENCE,
	asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1,
	sizeof(asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1)
		/sizeof(asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1[0]), /* 1 */
	asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1)
		/sizeof(asn_DEF_CS_GetProgramInvocationAttributes_Response_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CS_GetProgramInvocationAttributes_Response_1,
	2,	/* Elements count */
	&asn_SPC_CS_GetProgramInvocationAttributes_Response_specs_1	/* Additional specs */
};

