/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <CS-Resume-Request.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_modeType __attribute__((weak, alias("asn_DEF_modeType_4")));
#else
static asn_TYPE_descriptor_t asn_DEF_modeType_4;
static asn_TYPE_descriptor_t asn_DEF_modeType;
__attribute__((constructor)) static void asn_DEF_modeType_4_alias_init(void) {
	asn_DEF_modeType = asn_DEF_modeType_4;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_controlling __attribute__((weak, alias("asn_DEF_controlling_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_controlling_3;
static asn_TYPE_descriptor_t asn_DEF_controlling;
__attribute__((constructor)) static void asn_DEF_controlling_3_alias_init(void) {
	asn_DEF_controlling = asn_DEF_controlling_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_CS_Resume_Request__controlling__modeType_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Resume_Request__controlling__modeType, choice.continueMode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"continueMode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Resume_Request__controlling__modeType, choice.changeMode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_StartCount,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"changeMode"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_modeType_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* continueMode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* changeMode */
};
static asn_CHOICE_specifics_t asn_SPC_modeType_specs_4 = {
	sizeof(struct CS_Resume_Request__controlling__modeType),
	offsetof(struct CS_Resume_Request__controlling__modeType, _asn_ctx),
	offsetof(struct CS_Resume_Request__controlling__modeType, present),
	sizeof(((struct CS_Resume_Request__controlling__modeType *)0)->present),
	asn_MAP_modeType_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_modeType_4 = {
	"modeType",
	"modeType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_Resume_Request__controlling__modeType_4,
	2,	/* Elements count */
	&asn_SPC_modeType_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CS_Resume_Request__controlling_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Resume_Request__controlling, modeType),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_modeType_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"modeType"
		},
};
static const ber_tlv_tag_t asn_DEF_controlling_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_controlling_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* continueMode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 } /* changeMode */
};
static asn_SEQUENCE_specifics_t asn_SPC_controlling_specs_3 = {
	sizeof(struct CS_Resume_Request__controlling),
	offsetof(struct CS_Resume_Request__controlling, _asn_ctx),
	asn_MAP_controlling_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_controlling_3 = {
	"controlling",
	"controlling",
	&asn_OP_SEQUENCE,
	asn_DEF_controlling_tags_3,
	sizeof(asn_DEF_controlling_tags_3)
		/sizeof(asn_DEF_controlling_tags_3[0]), /* 1 */
	asn_DEF_controlling_tags_3,	/* Same as above */
	sizeof(asn_DEF_controlling_tags_3)
		/sizeof(asn_DEF_controlling_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CS_Resume_Request__controlling_3,
	1,	/* Elements count */
	&asn_SPC_controlling_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CS_Resume_Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Resume_Request, choice.normal),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"normal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CS_Resume_Request, choice.controlling),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_controlling_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"controlling"
		},
};
static const ber_tlv_tag_t asn_DEF_CS_Resume_Request_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CS_Resume_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 0, 0, 0 }, /* normal */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* controlling */
};
asn_CHOICE_specifics_t asn_SPC_CS_Resume_Request_specs_1 = {
	sizeof(struct CS_Resume_Request),
	offsetof(struct CS_Resume_Request, _asn_ctx),
	offsetof(struct CS_Resume_Request, present),
	sizeof(((struct CS_Resume_Request *)0)->present),
	asn_MAP_CS_Resume_Request_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CS_Resume_Request = {
	"CS-Resume-Request",
	"CS-Resume-Request",
	&asn_OP_CHOICE,
	asn_DEF_CS_Resume_Request_tags_1,
	sizeof(asn_DEF_CS_Resume_Request_tags_1)
		/sizeof(asn_DEF_CS_Resume_Request_tags_1[0]), /* 1 */
	asn_DEF_CS_Resume_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_CS_Resume_Request_tags_1)
		/sizeof(asn_DEF_CS_Resume_Request_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CS_Resume_Request_1,
	2,	/* Elements count */
	&asn_SPC_CS_Resume_Request_specs_1	/* Additional specs */
};

