/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_CS_Start_Request_PY_H_
#define	_CS_Start_Request_PY_H_


#include <CS-Start-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <StartCount_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CS-Start-Request */
PyCompat_DEF_ANON_STRUCT(CS_Start_Request_controlling_ANON_3, CS_Start_Request__controlling);
PyCompat_DEF_TYPE(CS_Start_Request_controlling_ANON_3);
PyCompat_DEF_STRUCT(CS_Start_Request);
PyCompat_DEF_TYPE(CS_Start_Request);
PyCompat_DEF_ENUM(CS_Start_Request_PRESENT);

/* Type Converters */
int PyAsnCS_Start_Request_controlling_ANON_3_FromPython(PyObject *pObj, CS_Start_Request_controlling_ANON_3_t *pDst);
PyObject *PyAsnCS_Start_Request_controlling_ANON_3_ToPython(CS_Start_Request_controlling_ANON_3_t *pSrc, PyObject *parent);
int PyAsnCS_Start_Request_FromPython(PyObject *pObj, CS_Start_Request_t *pDst);
PyObject *PyAsnCS_Start_Request_ToPython(CS_Start_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnCS_Start_Request_ModSetupTypes(void);
void PyAsnCS_Start_Request_ModClear(PyObject *);
int PyAsnCS_Start_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _CS_Start_Request_PY_H_ */
