/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DataAccessError_PY_H_
#define	_DataAccessError_PY_H_


#include <DataAccessError.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataAccessError */
PyCompat_DEF_STRUCT(DataAccessError);
PyCompat_DEF_TYPE(DataAccessError);
PyCompat_DEF_ENUM(DataAccessError);

/* Type Converters */
static inline int PyAsnDataAccessError_FromPython(PyObject *pObj, DataAccessError_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(DataAccessError, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnDataAccessError_ToPython(DataAccessError_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumDataAccessError_Type, *pSrc);
}

/* Module Initializers */
int PyAsnDataAccessError_ModSetupTypes(void);
void PyAsnDataAccessError_ModClear(PyObject *);
int PyAsnDataAccessError_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DataAccessError_PY_H_ */
