/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineEventAction_Response_PY_H_
#define	_DefineEventAction_Response_PY_H_


#include <DefineEventAction-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefineEventAction-Response */
PyCompat_DEF_STRUCT(DefineEventAction_Response);
PyCompat_DEF_TYPE(DefineEventAction_Response);

/* Type Converters */
static inline PyObject *PyAsnDefineEventAction_Response_ToPython(DefineEventAction_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnDefineEventAction_Response_FromPython(PyObject *pObj, DefineEventAction_Response_t *pDst)
{
	*pDst = (DefineEventAction_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnDefineEventAction_Response_ModSetupTypes(void);
void PyAsnDefineEventAction_Response_ModClear(PyObject *);
int PyAsnDefineEventAction_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DefineEventAction_Response_PY_H_ */
