/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineEventConditionList_Error_H_
#define	_DefineEventConditionList_Error_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DefineEventConditionList-Error */
typedef ObjectName_t	 DefineEventConditionList_Error_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventConditionList_Error;
asn_struct_free_f DefineEventConditionList_Error_free;
asn_struct_print_f DefineEventConditionList_Error_print;
asn_constr_check_f DefineEventConditionList_Error_constraint;
ber_type_decoder_f DefineEventConditionList_Error_decode_ber;
der_type_encoder_f DefineEventConditionList_Error_encode_der;
xer_type_decoder_f DefineEventConditionList_Error_decode_xer;
xer_type_encoder_f DefineEventConditionList_Error_encode_xer;
jer_type_encoder_f DefineEventConditionList_Error_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _DefineEventConditionList_Error_H_ */
#include <asn_internal.h>
