/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineScatteredAccess_Request_H_
#define	_DefineScatteredAccess_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct ScatteredAccessDescription;

/* DefineScatteredAccess-Request */
typedef struct DefineScatteredAccess_Request {
	struct ObjectName	*scatteredAccessName;
	struct ScatteredAccessDescription	*scatteredAccessDescription;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineScatteredAccess_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineScatteredAccess_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineScatteredAccess_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineScatteredAccess_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "ScatteredAccessDescription.h"

#endif	/* _DefineScatteredAccess_Request_H_ */
#include <asn_internal.h>
