/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineScatteredAccess_Response_PY_H_
#define	_DefineScatteredAccess_Response_PY_H_


#include <DefineScatteredAccess-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefineScatteredAccess-Response */
PyCompat_DEF_STRUCT(DefineScatteredAccess_Response);
PyCompat_DEF_TYPE(DefineScatteredAccess_Response);

/* Type Converters */
static inline PyObject *PyAsnDefineScatteredAccess_Response_ToPython(DefineScatteredAccess_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnDefineScatteredAccess_Response_FromPython(PyObject *pObj, DefineScatteredAccess_Response_t *pDst)
{
	*pDst = (DefineScatteredAccess_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnDefineScatteredAccess_Response_ModSetupTypes(void);
void PyAsnDefineScatteredAccess_Response_ModClear(PyObject *);
int PyAsnDefineScatteredAccess_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DefineScatteredAccess_Response_PY_H_ */
