/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineAccessControlList_Request_PY_H_
#define	_DefineAccessControlList_Request_PY_H_


#include <DefineAccessControlList-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <AccessCondition_Py.h>
#include <AccessCondition_Py.h>
#include <AccessCondition_Py.h>
#include <AccessCondition_Py.h>
#include <AccessCondition_Py.h>
#include <AccessCondition_Py.h>
#include <AccessCondition_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefineAccessControlList-Request */
PyCompat_DEF_ANON_STRUCT(DefineAccessControlList_Request_accessControlListElements_ANON_3, DefineAccessControlList_Request__accessControlListElements);
PyCompat_DEF_TYPE(DefineAccessControlList_Request_accessControlListElements_ANON_3);
PyCompat_DEF_STRUCT(DefineAccessControlList_Request);
PyCompat_DEF_TYPE(DefineAccessControlList_Request);

/* Type Converters */
int PyAsnDefineAccessControlList_Request_accessControlListElements_ANON_3_FromPython(PyObject *pObj, DefineAccessControlList_Request_accessControlListElements_ANON_3_t *pDst);
PyObject *PyAsnDefineAccessControlList_Request_accessControlListElements_ANON_3_ToPython(DefineAccessControlList_Request_accessControlListElements_ANON_3_t *pSrc, PyObject *parent);
int PyAsnDefineAccessControlList_Request_FromPython(PyObject *pObj, DefineAccessControlList_Request_t *pDst);
PyObject *PyAsnDefineAccessControlList_Request_ToPython(DefineAccessControlList_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnDefineAccessControlList_Request_ModSetupTypes(void);
void PyAsnDefineAccessControlList_Request_ModClear(PyObject *);
int PyAsnDefineAccessControlList_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DefineAccessControlList_Request_PY_H_ */
