/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineNamedType_Request_H_
#define	_DefineNamedType_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct TypeSpecification;

/* DefineNamedType-Request */
typedef struct DefineNamedType_Request {
	struct ObjectName	*typeName;
	struct TypeSpecification	*typeSpecification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedType_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedType_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineNamedType_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineNamedType_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "TypeSpecification.h"

#endif	/* _DefineNamedType_Request_H_ */
#include <asn_internal.h>
