/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineEventCondition_Request_H_
#define	_DefineEventCondition_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EC-Class.h"
#include "Priority.h"
#include "Unsigned8.h"
#include <BOOLEAN.h>
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct VariableSpecification;

/* DefineEventCondition-Request */
typedef struct DefineEventCondition_Request {
	struct ObjectName	*eventConditionName;
	EC_Class_t	 Class;
	Priority_t	*priority;	/* DEFAULT 64 */
	Unsigned8_t	*severity;	/* DEFAULT 64 */
	BOOLEAN_t	*alarmSummaryReports;	/* OPTIONAL */
	struct VariableSpecification	*monitoredVariable;	/* OPTIONAL */
	Unsigned32_t	*evaluationInterval;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineEventCondition_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventCondition_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineEventCondition_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineEventCondition_Request_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "VariableSpecification.h"

#endif	/* _DefineEventCondition_Request_H_ */
#include <asn_internal.h>
