/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineNamedVariableList_Request_H_
#define	_DefineNamedVariableList_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "VariableSpecification.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct AlternateAccess;

/* Forward definitions */
typedef struct DefineNamedVariableList_Request__listOfVariable__listOfVariable_Member {
	VariableSpecification_t	 variableSpecification;
	struct AlternateAccess	*alternateAccess;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedVariableList_Request__listOfVariable__listOfVariable_Member;

/* DefineNamedVariableList-Request */
typedef struct DefineNamedVariableList_Request {
	struct ObjectName	*variableListName;
	struct DefineNamedVariableList_Request__listOfVariable {
		A_SEQUENCE_OF(DefineNamedVariableList_Request__listOfVariable__listOfVariable_Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedVariableList_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedVariableList_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineNamedVariableList_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineNamedVariableList_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "AlternateAccess.h"

#endif	/* _DefineNamedVariableList_Request_H_ */
#include <asn_internal.h>
