/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineEventEnrollment_Request_H_
#define	_DefineEventEnrollment_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Transitions.h"
#include "AlarmAckRule.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct ApplicationReference;

/* DefineEventEnrollment-Request */
typedef struct DefineEventEnrollment_Request {
	struct ObjectName	*eventEnrollmentName;
	struct ObjectName	*eventConditionName;
	Transitions_t	 eventConditionTransitions;
	AlarmAckRule_t	 alarmAcknowledgmentRule;
	struct ObjectName	*eventActionName;	/* OPTIONAL */
	struct ApplicationReference	*clientApplication;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineEventEnrollment_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventEnrollment_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineEventEnrollment_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineEventEnrollment_Request_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "ApplicationReference.h"

#endif	/* _DefineEventEnrollment_Request_H_ */
#include <asn_internal.h>
