/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineEventAction_Request_H_
#define	_DefineEventAction_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct ConfirmedServiceRequest;
struct Request_Detail;
struct Modifier;

/* DefineEventAction-Request */
typedef struct DefineEventAction_Request {
	struct ObjectName	*eventActionName;
	struct DefineEventAction_Request__listOfModifier {
		A_SEQUENCE_OF(struct Modifier) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfModifier;
	struct ConfirmedServiceRequest	*confirmedServiceRequest;
	struct Request_Detail	*cs_extension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineEventAction_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineEventAction_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_DefineEventAction_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_DefineEventAction_Request_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "ConfirmedServiceRequest.h"
#include "Request-Detail.h"
#include "Modifier.h"

#endif	/* _DefineEventAction_Request_H_ */
#include <asn_internal.h>
