/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DefineEventConditionList_Response_PY_H_
#define	_DefineEventConditionList_Response_PY_H_


#include <DefineEventConditionList-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefineEventConditionList-Response */
PyCompat_DEF_STRUCT(DefineEventConditionList_Response);
PyCompat_DEF_TYPE(DefineEventConditionList_Response);

/* Type Converters */
static inline PyObject *PyAsnDefineEventConditionList_Response_ToPython(DefineEventConditionList_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnDefineEventConditionList_Response_FromPython(PyObject *pObj, DefineEventConditionList_Response_t *pDst)
{
	*pDst = (DefineEventConditionList_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnDefineEventConditionList_Response_ModSetupTypes(void);
void PyAsnDefineEventConditionList_Response_ModClear(PyObject *);
int PyAsnDefineEventConditionList_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DefineEventConditionList_Response_PY_H_ */
