/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DeleteUnitControl_Response_PY_H_
#define	_DeleteUnitControl_Response_PY_H_


#include <DeleteUnitControl-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeleteUnitControl-Response */
PyCompat_DEF_STRUCT(DeleteUnitControl_Response);
PyCompat_DEF_TYPE(DeleteUnitControl_Response);

/* Type Converters */
static inline PyObject *PyAsnDeleteUnitControl_Response_ToPython(DeleteUnitControl_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnDeleteUnitControl_Response_FromPython(PyObject *pObj, DeleteUnitControl_Response_t *pDst)
{
	*pDst = (DeleteUnitControl_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnDeleteUnitControl_Response_ModSetupTypes(void);
void PyAsnDeleteUnitControl_Response_ModClear(PyObject *);
int PyAsnDeleteUnitControl_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteUnitControl_Response_PY_H_ */
