/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DeleteVariableAccess_Response_PY_H_
#define	_DeleteVariableAccess_Response_PY_H_


#include <DeleteVariableAccess-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeleteVariableAccess-Response */
PyCompat_DEF_STRUCT(DeleteVariableAccess_Response);
PyCompat_DEF_TYPE(DeleteVariableAccess_Response);

/* Type Converters */
int PyAsnDeleteVariableAccess_Response_FromPython(PyObject *pObj, DeleteVariableAccess_Response_t *pDst);
PyObject *PyAsnDeleteVariableAccess_Response_ToPython(DeleteVariableAccess_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnDeleteVariableAccess_Response_ModSetupTypes(void);
void PyAsnDeleteVariableAccess_Response_ModClear(PyObject *);
int PyAsnDeleteVariableAccess_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteVariableAccess_Response_PY_H_ */
