/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DeleteJournal_Response_PY_H_
#define	_DeleteJournal_Response_PY_H_


#include <DeleteJournal-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeleteJournal-Response */
PyCompat_DEF_STRUCT(DeleteJournal_Response);
PyCompat_DEF_TYPE(DeleteJournal_Response);

/* Type Converters */
static inline PyObject *PyAsnDeleteJournal_Response_ToPython(DeleteJournal_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnDeleteJournal_Response_FromPython(PyObject *pObj, DeleteJournal_Response_t *pDst)
{
	*pDst = (DeleteJournal_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnDeleteJournal_Response_ModSetupTypes(void);
void PyAsnDeleteJournal_Response_ModClear(PyObject *);
int PyAsnDeleteJournal_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteJournal_Response_PY_H_ */
