/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DeleteDomain_Request_PY_H_
#define	_DeleteDomain_Request_PY_H_


#include <DeleteDomain-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeleteDomain-Request */
PyCompat_DEF_STRUCT(DeleteDomain_Request);
PyCompat_DEF_TYPE(DeleteDomain_Request);

/* Type Converters */
static inline PyObject *PyAsnDeleteDomain_Request_ToPython(DeleteDomain_Request_t *pSrc, PyObject *parent)
{
	return PyAsnIdentifier_ToPython(pSrc, parent);
}
static inline int PyAsnDeleteDomain_Request_FromPython(PyObject *pObj, DeleteDomain_Request_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(DeleteDomain_Request, pObj, pDst);
	return PyAsnIdentifier_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnDeleteDomain_Request_ModSetupTypes(void);
void PyAsnDeleteDomain_Request_ModClear(PyObject *);
int PyAsnDeleteDomain_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteDomain_Request_PY_H_ */
