/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DeleteNamedType_Response_PY_H_
#define	_DeleteNamedType_Response_PY_H_


#include <DeleteNamedType-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeleteNamedType-Response */
PyCompat_DEF_STRUCT(DeleteNamedType_Response);
PyCompat_DEF_TYPE(DeleteNamedType_Response);

/* Type Converters */
int PyAsnDeleteNamedType_Response_FromPython(PyObject *pObj, DeleteNamedType_Response_t *pDst);
PyObject *PyAsnDeleteNamedType_Response_ToPython(DeleteNamedType_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnDeleteNamedType_Response_ModSetupTypes(void);
void PyAsnDeleteNamedType_Response_ModClear(PyObject *);
int PyAsnDeleteNamedType_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteNamedType_Response_PY_H_ */
