/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DirectoryEntry_PY_H_
#define	_DirectoryEntry_PY_H_


#include <DirectoryEntry.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <FileName_Py.h>
#include <FileAttributes_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DirectoryEntry */
PyCompat_DEF_STRUCT(DirectoryEntry);
PyCompat_DEF_TYPE(DirectoryEntry);

/* Type Converters */
int PyAsnDirectoryEntry_FromPython(PyObject *pObj, DirectoryEntry_t *pDst);
PyObject *PyAsnDirectoryEntry_ToPython(DirectoryEntry_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnDirectoryEntry_ModSetupTypes(void);
void PyAsnDirectoryEntry_ModClear(PyObject *);
int PyAsnDirectoryEntry_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DirectoryEntry_PY_H_ */
