/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_DirectoryEntry_H_
#define	_DirectoryEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileName;
struct FileAttributes;

/* DirectoryEntry */
typedef struct DirectoryEntry {
	struct FileName	*fileName;
	struct FileAttributes	*fileAttributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DirectoryEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DirectoryEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_DirectoryEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_DirectoryEntry_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileName.h"
#include "FileAttributes.h"

#endif	/* _DirectoryEntry_H_ */
#include <asn_internal.h>
