/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_DomainName_PY_H_
#define	_DomainName_PY_H_


#include <DomainName.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DomainName */
PyCompat_DEF_STRUCT(DomainName);
PyCompat_DEF_TYPE(DomainName);

/* Type Converters */
static inline int PyAsnDomainName_FromPython(PyObject *pObj, DomainName_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(DomainName, pObj, pDst);
	pDst->buf = (uint8_t *)PyCompatUnicode_AsUTF8AndSize(pObj, &pDst->size);
	return pDst->buf ? 0 : -1;
}
static inline PyObject *PyAsnDomainName_ToPython(DomainName_t *pSrc, PyObject *parent)
{
	return PyCompatUnicode_FromStringAndSize(pSrc->buf, pSrc->size);
}

/* Module Initializers */
int PyAsnDomainName_ModSetupTypes(void);
void PyAsnDomainName_ModClear(PyObject *);
int PyAsnDomainName_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _DomainName_PY_H_ */
