/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_EE_Duration_PY_H_
#define	_EE_Duration_PY_H_


#include <EE-Duration.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EE-Duration */
PyCompat_DEF_STRUCT(EE_Duration);
PyCompat_DEF_TYPE(EE_Duration);
PyCompat_DEF_ENUM(EE_Duration);

/* Type Converters */
static inline int PyAsnEE_Duration_FromPython(PyObject *pObj, EE_Duration_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(EE_Duration, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnEE_Duration_ToPython(EE_Duration_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumEE_Duration_Type, *pSrc);
}

/* Module Initializers */
int PyAsnEE_Duration_ModSetupTypes(void);
void PyAsnEE_Duration_ModClear(PyObject *);
int PyAsnEE_Duration_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _EE_Duration_PY_H_ */
