/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_EventTime_PY_H_
#define	_EventTime_PY_H_


#include <EventTime.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <TimeOfDay_Py.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EventTime */
PyCompat_DEF_STRUCT(EventTime);
PyCompat_DEF_TYPE(EventTime);
PyCompat_DEF_ENUM(EventTime_PRESENT);

/* Type Converters */
int PyAsnEventTime_FromPython(PyObject *pObj, EventTime_t *pDst);
PyObject *PyAsnEventTime_ToPython(EventTime_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnEventTime_ModSetupTypes(void);
void PyAsnEventTime_ModClear(PyObject *);
int PyAsnEventTime_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _EventTime_PY_H_ */
