/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <ExchangeData-Response.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfResponseData __attribute__((weak, alias("asn_DEF_listOfResponseData_2")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfResponseData_2;
static asn_TYPE_descriptor_t asn_DEF_listOfResponseData;
__attribute__((constructor)) static void asn_DEF_listOfResponseData_2_alias_init(void) {
	asn_DEF_listOfResponseData = asn_DEF_listOfResponseData_2;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_ExchangeData_Response__listOfResponseData_2[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfResponseData_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfResponseData_specs_2 = {
	sizeof(struct ExchangeData_Response__listOfResponseData),
	offsetof(struct ExchangeData_Response__listOfResponseData, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfResponseData_2 = {
	"listOfResponseData",
	"listOfResponseData",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfResponseData_tags_2,
	sizeof(asn_DEF_listOfResponseData_tags_2)
		/sizeof(asn_DEF_listOfResponseData_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfResponseData_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfResponseData_tags_2)
		/sizeof(asn_DEF_listOfResponseData_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ExchangeData_Response__listOfResponseData_2,
	1,	/* Single element */
	&asn_SPC_listOfResponseData_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ExchangeData_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExchangeData_Response, listOfResponseData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_listOfResponseData_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfResponseData"
		},
};
static const ber_tlv_tag_t asn_DEF_ExchangeData_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ExchangeData_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* listOfResponseData */
};
asn_SEQUENCE_specifics_t asn_SPC_ExchangeData_Response_specs_1 = {
	sizeof(struct ExchangeData_Response),
	offsetof(struct ExchangeData_Response, _asn_ctx),
	asn_MAP_ExchangeData_Response_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ExchangeData_Response = {
	"ExchangeData-Response",
	"ExchangeData-Response",
	&asn_OP_SEQUENCE,
	asn_DEF_ExchangeData_Response_tags_1,
	sizeof(asn_DEF_ExchangeData_Response_tags_1)
		/sizeof(asn_DEF_ExchangeData_Response_tags_1[0]), /* 1 */
	asn_DEF_ExchangeData_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExchangeData_Response_tags_1)
		/sizeof(asn_DEF_ExchangeData_Response_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ExchangeData_Response_1,
	1,	/* Elements count */
	&asn_SPC_ExchangeData_Response_specs_1	/* Additional specs */
};

