/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ExchangeData_Request_PY_H_
#define	_ExchangeData_Request_PY_H_


#include <ExchangeData-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Data_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExchangeData-Request */
typedef struct ExchangeData_Request__listOfRequestData ExchangeData_Request_listOfRequestData_ANON_3_t;
PyCompat_DEF_STRUCT(ExchangeData_Request_listOfRequestData_ANON_3);
PyCompat_DEF_TYPE(ExchangeData_Request_listOfRequestData_ANON_3);
PyCompat_DEF_STRUCT(ExchangeData_Request);
PyCompat_DEF_TYPE(ExchangeData_Request);

/* Type Converters */
int PyAsnExchangeData_Request_listOfRequestData_ANON_3_FromPython(PyObject *pObj, ExchangeData_Request_listOfRequestData_ANON_3_t *pDst);
PyObject *PyAsnExchangeData_Request_listOfRequestData_ANON_3_ToPython(ExchangeData_Request_listOfRequestData_ANON_3_t *pSrc, PyObject *parent);
int PyAsnExchangeData_Request_FromPython(PyObject *pObj, ExchangeData_Request_t *pDst);
PyObject *PyAsnExchangeData_Request_ToPython(ExchangeData_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnExchangeData_Request_ModSetupTypes(void);
void PyAsnExchangeData_Request_ModClear(PyObject *);
int PyAsnExchangeData_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ExchangeData_Request_PY_H_ */
