/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ExchangeData_Response_PY_H_
#define	_ExchangeData_Response_PY_H_


#include <ExchangeData-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Data_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExchangeData-Response */
typedef struct ExchangeData_Response__listOfResponseData ExchangeData_Response_listOfResponseData_ANON_2_t;
PyCompat_DEF_STRUCT(ExchangeData_Response_listOfResponseData_ANON_2);
PyCompat_DEF_TYPE(ExchangeData_Response_listOfResponseData_ANON_2);
PyCompat_DEF_STRUCT(ExchangeData_Response);
PyCompat_DEF_TYPE(ExchangeData_Response);

/* Type Converters */
int PyAsnExchangeData_Response_listOfResponseData_ANON_2_FromPython(PyObject *pObj, ExchangeData_Response_listOfResponseData_ANON_2_t *pDst);
PyObject *PyAsnExchangeData_Response_listOfResponseData_ANON_2_ToPython(ExchangeData_Response_listOfResponseData_ANON_2_t *pSrc, PyObject *parent);
int PyAsnExchangeData_Response_FromPython(PyObject *pObj, ExchangeData_Response_t *pDst);
PyObject *PyAsnExchangeData_Response_ToPython(ExchangeData_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnExchangeData_Response_ModSetupTypes(void);
void PyAsnExchangeData_Response_ModClear(PyObject *);
int PyAsnExchangeData_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ExchangeData_Response_PY_H_ */
