/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ExchangeData_Request_H_
#define	_ExchangeData_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;
struct Data;

/* ExchangeData-Request */
typedef struct ExchangeData_Request {
	struct ObjectName	*dataExchangeName;
	struct ExchangeData_Request__listOfRequestData {
		A_SEQUENCE_OF(struct Data) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfRequestData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExchangeData_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExchangeData_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_ExchangeData_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_ExchangeData_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "Data.h"

#endif	/* _ExchangeData_Request_H_ */
#include <asn_internal.h>
