/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ExtendedStatus_PY_H_
#define	_ExtendedStatus_PY_H_


#include <ExtendedStatus.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <py_convert_BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedStatus */
PyCompat_DEF_STRUCT(ExtendedStatus);
PyCompat_DEF_TYPE(ExtendedStatus);
#define PyAsnExtendedStatus_MAX_SIZE PyCompatBITSTRING_maxLength(3, uint8_t)

/* Type Converters */
static inline int PyAsnExtendedStatus_FromPython(PyObject *pObj, ExtendedStatus_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT_INTERNAL(ExtendedStatus, pObj, pDst, &asn_DEF_BIT_STRING);
	return PyCompatBITSTRING_FromObject(pObj, pDst);
}
static inline PyObject *PyAsnExtendedStatus_ToPython(ExtendedStatus_t *pSrc, PyObject *parent)
{
	return PyCompatBITSTRING_AsObject(pSrc);
}

/* Module Initializers */
int PyAsnExtendedStatus_ModSetupTypes(void);
void PyAsnExtendedStatus_ModClear(PyObject *);
int PyAsnExtendedStatus_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedStatus_PY_H_ */
