/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ExtendedStatus_H_
#define	_ExtendedStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExtendedStatus {
	ExtendedStatus_safetyInterlocksViolated	= 0,
	ExtendedStatus_anyPhysicalResourcePowerOn	= 1,
	ExtendedStatus_allPhysicalResourcesCalibrated	= 2,
	ExtendedStatus_localControl	= 3
} e_ExtendedStatus;

/* ExtendedStatus */
typedef BIT_STRING_t	 ExtendedStatus_t;

/* Implementation */
extern asn_jer_constraints_t asn_JER_type_ExtendedStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExtendedStatus;
asn_struct_free_f ExtendedStatus_free;
asn_struct_print_f ExtendedStatus_print;
asn_constr_check_f ExtendedStatus_constraint;
ber_type_decoder_f ExtendedStatus_decode_ber;
der_type_encoder_f ExtendedStatus_encode_der;
xer_type_decoder_f ExtendedStatus_decode_xer;
xer_type_encoder_f ExtendedStatus_encode_xer;
jer_type_encoder_f ExtendedStatus_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedStatus_H_ */
#include <asn_internal.h>
