/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileName_PY_H_
#define	_FileName_PY_H_


#include <FileName.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileName */
PyCompat_DEF_STRUCT(FileName);
PyCompat_DEF_TYPE(FileName);

/* Type Converters */
int PyAsnFileName_FromPython(PyObject *pObj, FileName_t *pDst);
PyObject *PyAsnFileName_ToPython(FileName_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnFileName_ModSetupTypes(void);
void PyAsnFileName_ModClear(PyObject *);
int PyAsnFileName_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _FileName_PY_H_ */
