/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileRename_Request_H_
#define	_FileRename_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileName;

/* FileRename-Request */
typedef struct FileRename_Request {
	struct FileName	*currentFileName;
	struct FileName	*newFileName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileRename_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileRename_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_FileRename_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_FileRename_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileName.h"

#endif	/* _FileRename_Request_H_ */
#include <asn_internal.h>
