/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileOpen_Request_H_
#define	_FileOpen_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileName;

/* FileOpen-Request */
typedef struct FileOpen_Request {
	struct FileName	*fileName;
	Unsigned32_t	 initialPosition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileOpen_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileOpen_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_FileOpen_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_FileOpen_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileName.h"

#endif	/* _FileOpen_Request_H_ */
#include <asn_internal.h>
