/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileDirectory_Request_PY_H_
#define	_FileDirectory_Request_PY_H_


#include <FileDirectory-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <FileName_Py.h>
#include <FileName_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileDirectory-Request */
PyCompat_DEF_STRUCT(FileDirectory_Request);
PyCompat_DEF_TYPE(FileDirectory_Request);

/* Type Converters */
int PyAsnFileDirectory_Request_FromPython(PyObject *pObj, FileDirectory_Request_t *pDst);
PyObject *PyAsnFileDirectory_Request_ToPython(FileDirectory_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnFileDirectory_Request_ModSetupTypes(void);
void PyAsnFileDirectory_Request_ModClear(PyObject *);
int PyAsnFileDirectory_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _FileDirectory_Request_PY_H_ */
