/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileRead_Request_PY_H_
#define	_FileRead_Request_PY_H_


#include <FileRead-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Integer32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileRead-Request */
PyCompat_DEF_STRUCT(FileRead_Request);
PyCompat_DEF_TYPE(FileRead_Request);

/* Type Converters */
static inline PyObject *PyAsnFileRead_Request_ToPython(FileRead_Request_t *pSrc, PyObject *parent)
{
	return PyAsnInteger32_ToPython(pSrc, parent);
}
static inline int PyAsnFileRead_Request_FromPython(PyObject *pObj, FileRead_Request_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(FileRead_Request, pObj, pDst);
	return PyAsnInteger32_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnFileRead_Request_ModSetupTypes(void);
void PyAsnFileRead_Request_ModClear(PyObject *);
int PyAsnFileRead_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _FileRead_Request_PY_H_ */
