/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileRename_Response_PY_H_
#define	_FileRename_Response_PY_H_


#include <FileRename-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileRename-Response */
PyCompat_DEF_STRUCT(FileRename_Response);
PyCompat_DEF_TYPE(FileRename_Response);

/* Type Converters */
static inline PyObject *PyAsnFileRename_Response_ToPython(FileRename_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnFileRename_Response_FromPython(PyObject *pObj, FileRename_Response_t *pDst)
{
	*pDst = (FileRename_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnFileRename_Response_ModSetupTypes(void);
void PyAsnFileRename_Response_ModClear(PyObject *);
int PyAsnFileRename_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _FileRename_Response_PY_H_ */
