/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileRead_Response_PY_H_
#define	_FileRead_Response_PY_H_


#include <FileRead-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileRead-Response */
PyCompat_DEF_STRUCT(FileRead_Response);
PyCompat_DEF_TYPE(FileRead_Response);

/* Type Converters */
int PyAsnFileRead_Response_FromPython(PyObject *pObj, FileRead_Response_t *pDst);
PyObject *PyAsnFileRead_Response_ToPython(FileRead_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnFileRead_Response_ModSetupTypes(void);
void PyAsnFileRead_Response_ModClear(PyObject *);
int PyAsnFileRead_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _FileRead_Response_PY_H_ */
