/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileRename_Request_PY_H_
#define	_FileRename_Request_PY_H_


#include <FileRename-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <FileName_Py.h>
#include <FileName_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FileRename-Request */
PyCompat_DEF_STRUCT(FileRename_Request);
PyCompat_DEF_TYPE(FileRename_Request);

/* Type Converters */
int PyAsnFileRename_Request_FromPython(PyObject *pObj, FileRename_Request_t *pDst);
PyObject *PyAsnFileRename_Request_ToPython(FileRename_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnFileRename_Request_ModSetupTypes(void);
void PyAsnFileRename_Request_ModClear(PyObject *);
int PyAsnFileRename_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _FileRename_Request_PY_H_ */
