/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_FileDirectory_Response_H_
#define	_FileDirectory_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DirectoryEntry;

/* FileDirectory-Response */
typedef struct FileDirectory_Response {
	struct FileDirectory_Response__listOfDirectoryEntry {
		A_SEQUENCE_OF(struct DirectoryEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfDirectoryEntry;
	BOOLEAN_t	 moreFollows;	/* DEFAULT FALSE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FileDirectory_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FileDirectory_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_FileDirectory_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_FileDirectory_Response_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DirectoryEntry.h"

#endif	/* _FileDirectory_Response_H_ */
#include <asn_internal.h>
