/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetAlarmEnrollmentSummary_Request_PY_H_
#define	_GetAlarmEnrollmentSummary_Request_PY_H_


#include <GetAlarmEnrollmentSummary-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned8_Py.h>
#include <Unsigned8_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetAlarmEnrollmentSummary-Request */
PyCompat_DEF_ANON_STRUCT(GetAlarmEnrollmentSummary_Request_severityFilter_ANON_8, GetAlarmEnrollmentSummary_Request__severityFilter);
PyCompat_DEF_TYPE(GetAlarmEnrollmentSummary_Request_severityFilter_ANON_8);
PyCompat_DEF_STRUCT(GetAlarmEnrollmentSummary_Request);
PyCompat_DEF_TYPE(GetAlarmEnrollmentSummary_Request);
PyCompat_DEF_ENUM(GetAlarmEnrollmentSummary_Request_acknowledgementFilter);

/* Type Converters */
int PyAsnGetAlarmEnrollmentSummary_Request_severityFilter_ANON_8_FromPython(PyObject *pObj, GetAlarmEnrollmentSummary_Request_severityFilter_ANON_8_t *pDst);
PyObject *PyAsnGetAlarmEnrollmentSummary_Request_severityFilter_ANON_8_ToPython(GetAlarmEnrollmentSummary_Request_severityFilter_ANON_8_t *pSrc, PyObject *parent);
int PyAsnGetAlarmEnrollmentSummary_Request_FromPython(PyObject *pObj, GetAlarmEnrollmentSummary_Request_t *pDst);
PyObject *PyAsnGetAlarmEnrollmentSummary_Request_ToPython(GetAlarmEnrollmentSummary_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetAlarmEnrollmentSummary_Request_ModSetupTypes(void);
void PyAsnGetAlarmEnrollmentSummary_Request_ModClear(PyObject *);
int PyAsnGetAlarmEnrollmentSummary_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetAlarmEnrollmentSummary_Request_PY_H_ */
