/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetAlarmSummary_Response_PY_H_
#define	_GetAlarmSummary_Response_PY_H_


#include <GetAlarmSummary-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <AlarmSummary_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetAlarmSummary-Response */
typedef struct GetAlarmSummary_Response__listOfAlarmSummary GetAlarmSummary_Response_listOfAlarmSummary_ANON_2_t;
PyCompat_DEF_STRUCT(GetAlarmSummary_Response_listOfAlarmSummary_ANON_2);
PyCompat_DEF_TYPE(GetAlarmSummary_Response_listOfAlarmSummary_ANON_2);
PyCompat_DEF_STRUCT(GetAlarmSummary_Response);
PyCompat_DEF_TYPE(GetAlarmSummary_Response);

/* Type Converters */
int PyAsnGetAlarmSummary_Response_listOfAlarmSummary_ANON_2_FromPython(PyObject *pObj, GetAlarmSummary_Response_listOfAlarmSummary_ANON_2_t *pDst);
PyObject *PyAsnGetAlarmSummary_Response_listOfAlarmSummary_ANON_2_ToPython(GetAlarmSummary_Response_listOfAlarmSummary_ANON_2_t *pSrc, PyObject *parent);
int PyAsnGetAlarmSummary_Response_FromPython(PyObject *pObj, GetAlarmSummary_Response_t *pDst);
PyObject *PyAsnGetAlarmSummary_Response_ToPython(GetAlarmSummary_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetAlarmSummary_Response_ModSetupTypes(void);
void PyAsnGetAlarmSummary_Response_ModClear(PyObject *);
int PyAsnGetAlarmSummary_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetAlarmSummary_Response_PY_H_ */
