/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetDataExchangeAttributes_Response_PY_H_
#define	_GetDataExchangeAttributes_Response_PY_H_


#include <GetDataExchangeAttributes-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <TypeDescription_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <TypeDescription_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetDataExchangeAttributes-Response */
typedef struct GetDataExchangeAttributes_Response__listOfRequestTypeDescriptions GetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3_t;
PyCompat_DEF_STRUCT(GetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3);
PyCompat_DEF_TYPE(GetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3);
typedef struct GetDataExchangeAttributes_Response__listOfResponseTypeDescriptions GetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5_t;
PyCompat_DEF_STRUCT(GetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5);
PyCompat_DEF_TYPE(GetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5);
PyCompat_DEF_STRUCT(GetDataExchangeAttributes_Response);
PyCompat_DEF_TYPE(GetDataExchangeAttributes_Response);

/* Type Converters */
int PyAsnGetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3_FromPython(PyObject *pObj, GetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3_t *pDst);
PyObject *PyAsnGetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3_ToPython(GetDataExchangeAttributes_Response_listOfRequestTypeDescriptions_ANON_3_t *pSrc, PyObject *parent);
int PyAsnGetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5_FromPython(PyObject *pObj, GetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5_t *pDst);
PyObject *PyAsnGetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5_ToPython(GetDataExchangeAttributes_Response_listOfResponseTypeDescriptions_ANON_5_t *pSrc, PyObject *parent);
int PyAsnGetDataExchangeAttributes_Response_FromPython(PyObject *pObj, GetDataExchangeAttributes_Response_t *pDst);
PyObject *PyAsnGetDataExchangeAttributes_Response_ToPython(GetDataExchangeAttributes_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetDataExchangeAttributes_Response_ModSetupTypes(void);
void PyAsnGetDataExchangeAttributes_Response_ModClear(PyObject *);
int PyAsnGetDataExchangeAttributes_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetDataExchangeAttributes_Response_PY_H_ */
