/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetEventActionAttributes_Response_PY_H_
#define	_GetEventActionAttributes_Response_PY_H_


#include <GetEventActionAttributes-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Modifier_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <ConfirmedServiceRequest_Py.h>
#include <Request-Detail_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetEventActionAttributes-Response */
typedef struct GetEventActionAttributes_Response__listOfModifier GetEventActionAttributes_Response_listOfModifier_ANON_3_t;
PyCompat_DEF_STRUCT(GetEventActionAttributes_Response_listOfModifier_ANON_3);
PyCompat_DEF_TYPE(GetEventActionAttributes_Response_listOfModifier_ANON_3);
PyCompat_DEF_STRUCT(GetEventActionAttributes_Response);
PyCompat_DEF_TYPE(GetEventActionAttributes_Response);

/* Type Converters */
int PyAsnGetEventActionAttributes_Response_listOfModifier_ANON_3_FromPython(PyObject *pObj, GetEventActionAttributes_Response_listOfModifier_ANON_3_t *pDst);
PyObject *PyAsnGetEventActionAttributes_Response_listOfModifier_ANON_3_ToPython(GetEventActionAttributes_Response_listOfModifier_ANON_3_t *pSrc, PyObject *parent);
int PyAsnGetEventActionAttributes_Response_FromPython(PyObject *pObj, GetEventActionAttributes_Response_t *pDst);
PyObject *PyAsnGetEventActionAttributes_Response_ToPython(GetEventActionAttributes_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetEventActionAttributes_Response_ModSetupTypes(void);
void PyAsnGetEventActionAttributes_Response_ModClear(PyObject *);
int PyAsnGetEventActionAttributes_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetEventActionAttributes_Response_PY_H_ */
