/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetEventEnrollmentAttributes_Response_PY_H_
#define	_GetEventEnrollmentAttributes_Response_PY_H_


#include <GetEventEnrollmentAttributes-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <EEAttributes_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetEventEnrollmentAttributes-Response */
typedef struct GetEventEnrollmentAttributes_Response__listOfEEAttributes GetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2_t;
PyCompat_DEF_STRUCT(GetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2);
PyCompat_DEF_TYPE(GetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2);
PyCompat_DEF_STRUCT(GetEventEnrollmentAttributes_Response);
PyCompat_DEF_TYPE(GetEventEnrollmentAttributes_Response);

/* Type Converters */
int PyAsnGetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2_FromPython(PyObject *pObj, GetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2_t *pDst);
PyObject *PyAsnGetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2_ToPython(GetEventEnrollmentAttributes_Response_listOfEEAttributes_ANON_2_t *pSrc, PyObject *parent);
int PyAsnGetEventEnrollmentAttributes_Response_FromPython(PyObject *pObj, GetEventEnrollmentAttributes_Response_t *pDst);
PyObject *PyAsnGetEventEnrollmentAttributes_Response_ToPython(GetEventEnrollmentAttributes_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetEventEnrollmentAttributes_Response_ModSetupTypes(void);
void PyAsnGetEventEnrollmentAttributes_Response_ModClear(PyObject *);
int PyAsnGetEventEnrollmentAttributes_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetEventEnrollmentAttributes_Response_PY_H_ */
