/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetNameList_Response_PY_H_
#define	_GetNameList_Response_PY_H_


#include <GetNameList-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetNameList-Response */
typedef struct GetNameList_Response__listOfIdentifier GetNameList_Response_listOfIdentifier_ANON_2_t;
PyCompat_DEF_STRUCT(GetNameList_Response_listOfIdentifier_ANON_2);
PyCompat_DEF_TYPE(GetNameList_Response_listOfIdentifier_ANON_2);
PyCompat_DEF_STRUCT(GetNameList_Response);
PyCompat_DEF_TYPE(GetNameList_Response);

/* Type Converters */
int PyAsnGetNameList_Response_listOfIdentifier_ANON_2_FromPython(PyObject *pObj, GetNameList_Response_listOfIdentifier_ANON_2_t *pDst);
PyObject *PyAsnGetNameList_Response_listOfIdentifier_ANON_2_ToPython(GetNameList_Response_listOfIdentifier_ANON_2_t *pSrc, PyObject *parent);
int PyAsnGetNameList_Response_FromPython(PyObject *pObj, GetNameList_Response_t *pDst);
PyObject *PyAsnGetNameList_Response_ToPython(GetNameList_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetNameList_Response_ModSetupTypes(void);
void PyAsnGetNameList_Response_ModClear(PyObject *);
int PyAsnGetNameList_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetNameList_Response_PY_H_ */
