/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetScatteredAccessAttributes_Response_PY_H_
#define	_GetScatteredAccessAttributes_Response_PY_H_


#include <GetScatteredAccessAttributes-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ScatteredAccessDescription_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetScatteredAccessAttributes-Response */
PyCompat_DEF_STRUCT(GetScatteredAccessAttributes_Response);
PyCompat_DEF_TYPE(GetScatteredAccessAttributes_Response);

/* Type Converters */
int PyAsnGetScatteredAccessAttributes_Response_FromPython(PyObject *pObj, GetScatteredAccessAttributes_Response_t *pDst);
PyObject *PyAsnGetScatteredAccessAttributes_Response_ToPython(GetScatteredAccessAttributes_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetScatteredAccessAttributes_Response_ModSetupTypes(void);
void PyAsnGetScatteredAccessAttributes_Response_ModClear(PyObject *);
int PyAsnGetScatteredAccessAttributes_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetScatteredAccessAttributes_Response_PY_H_ */
