/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetScatteredAccessAttributes_Response_H_
#define	_GetScatteredAccessAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ScatteredAccessDescription;

/* GetScatteredAccessAttributes-Response */
typedef struct GetScatteredAccessAttributes_Response {
	BOOLEAN_t	 mmsDeletable;
	struct ScatteredAccessDescription	*scatteredAccessDescription;
	Identifier_t	*accessControlList;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetScatteredAccessAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetScatteredAccessAttributes_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_GetScatteredAccessAttributes_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_GetScatteredAccessAttributes_Response_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ScatteredAccessDescription.h"

#endif	/* _GetScatteredAccessAttributes_Response_H_ */
#include <asn_internal.h>
