/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <GetUnitControlAttributes-Response.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_domains __attribute__((weak, alias("asn_DEF_domains_2")));
#else
static asn_TYPE_descriptor_t asn_DEF_domains_2;
static asn_TYPE_descriptor_t asn_DEF_domains;
__attribute__((constructor)) static void asn_DEF_domains_2_alias_init(void) {
	asn_DEF_domains = asn_DEF_domains_2;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_programInvocations __attribute__((weak, alias("asn_DEF_programInvocations_4")));
#else
static asn_TYPE_descriptor_t asn_DEF_programInvocations_4;
static asn_TYPE_descriptor_t asn_DEF_programInvocations;
__attribute__((constructor)) static void asn_DEF_programInvocations_4_alias_init(void) {
	asn_DEF_programInvocations = asn_DEF_programInvocations_4;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_GetUnitControlAttributes_Response__domains_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_Identifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_domains_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_domains_specs_2 = {
	sizeof(struct GetUnitControlAttributes_Response__domains),
	offsetof(struct GetUnitControlAttributes_Response__domains, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_domains_2 = {
	"domains",
	"domains",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_domains_tags_2,
	sizeof(asn_DEF_domains_tags_2)
		/sizeof(asn_DEF_domains_tags_2[0]) - 1, /* 1 */
	asn_DEF_domains_tags_2,	/* Same as above */
	sizeof(asn_DEF_domains_tags_2)
		/sizeof(asn_DEF_domains_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_GetUnitControlAttributes_Response__domains_2,
	1,	/* Single element */
	&asn_SPC_domains_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetUnitControlAttributes_Response__programInvocations_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_Identifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_programInvocations_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_programInvocations_specs_4 = {
	sizeof(struct GetUnitControlAttributes_Response__programInvocations),
	offsetof(struct GetUnitControlAttributes_Response__programInvocations, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_programInvocations_4 = {
	"programInvocations",
	"programInvocations",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_programInvocations_tags_4,
	sizeof(asn_DEF_programInvocations_tags_4)
		/sizeof(asn_DEF_programInvocations_tags_4[0]) - 1, /* 1 */
	asn_DEF_programInvocations_tags_4,	/* Same as above */
	sizeof(asn_DEF_programInvocations_tags_4)
		/sizeof(asn_DEF_programInvocations_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_GetUnitControlAttributes_Response__programInvocations_4,
	1,	/* Single element */
	&asn_SPC_programInvocations_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_GetUnitControlAttributes_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetUnitControlAttributes_Response, domains),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_domains_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"domains"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetUnitControlAttributes_Response, programInvocations),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_programInvocations_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"programInvocations"
		},
};
static const ber_tlv_tag_t asn_DEF_GetUnitControlAttributes_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetUnitControlAttributes_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* domains */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* programInvocations */
};
asn_SEQUENCE_specifics_t asn_SPC_GetUnitControlAttributes_Response_specs_1 = {
	sizeof(struct GetUnitControlAttributes_Response),
	offsetof(struct GetUnitControlAttributes_Response, _asn_ctx),
	asn_MAP_GetUnitControlAttributes_Response_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetUnitControlAttributes_Response = {
	"GetUnitControlAttributes-Response",
	"GetUnitControlAttributes-Response",
	&asn_OP_SEQUENCE,
	asn_DEF_GetUnitControlAttributes_Response_tags_1,
	sizeof(asn_DEF_GetUnitControlAttributes_Response_tags_1)
		/sizeof(asn_DEF_GetUnitControlAttributes_Response_tags_1[0]), /* 1 */
	asn_DEF_GetUnitControlAttributes_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetUnitControlAttributes_Response_tags_1)
		/sizeof(asn_DEF_GetUnitControlAttributes_Response_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GetUnitControlAttributes_Response_1,
	2,	/* Elements count */
	&asn_SPC_GetUnitControlAttributes_Response_specs_1	/* Additional specs */
};

