/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetUnitControlAttributes_Response_H_
#define	_GetUnitControlAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetUnitControlAttributes-Response */
typedef struct GetUnitControlAttributes_Response {
	struct GetUnitControlAttributes_Response__domains {
		A_SEQUENCE_OF(Identifier_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} domains;
	struct GetUnitControlAttributes_Response__programInvocations {
		A_SEQUENCE_OF(Identifier_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} programInvocations;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetUnitControlAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetUnitControlAttributes_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_GetUnitControlAttributes_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_GetUnitControlAttributes_Response_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GetUnitControlAttributes_Response_H_ */
#include <asn_internal.h>
