/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetVariableAccessAttributes_Response_H_
#define	_GetVariableAccessAttributes_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "Identifier.h"
#include <VisibleString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Address;
struct TypeDescription;

/* GetVariableAccessAttributes-Response */
typedef struct GetVariableAccessAttributes_Response {
	BOOLEAN_t	 mmsDeletable;
	struct Address	*address;	/* OPTIONAL */
	struct TypeDescription	*typeDescription;
	Identifier_t	*accessControlList;	/* OPTIONAL */
	VisibleString_t	*meaning;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetVariableAccessAttributes_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributes_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_GetVariableAccessAttributes_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_GetVariableAccessAttributes_Response_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Address.h"
#include "TypeDescription.h"

#endif	/* _GetVariableAccessAttributes_Response_H_ */
#include <asn_internal.h>
