/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetVariableAccessAttributes_Request_H_
#define	_GetVariableAccessAttributes_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetVariableAccessAttributes_Request_PR {
	GetVariableAccessAttributes_Request_PR_NOTHING,	/* No components present */
	GetVariableAccessAttributes_Request_PR_name,
	GetVariableAccessAttributes_Request_PR_address
} GetVariableAccessAttributes_Request_PR;

/* Forward declarations */
struct ObjectName;
struct Address;

/* GetVariableAccessAttributes-Request */
typedef struct GetVariableAccessAttributes_Request {
	GetVariableAccessAttributes_Request_PR present;
	union GetVariableAccessAttributes_Request_u {
		struct ObjectName	*name;
		struct Address	*address;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetVariableAccessAttributes_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetVariableAccessAttributes_Request;
extern asn_CHOICE_specifics_t asn_SPC_GetVariableAccessAttributes_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_GetVariableAccessAttributes_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"
#include "Address.h"

#endif	/* _GetVariableAccessAttributes_Request_H_ */
#include <asn_internal.h>
