/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_GetVariableAccessAttributes_Request_PY_H_
#define	_GetVariableAccessAttributes_Request_PY_H_


#include <GetVariableAccessAttributes-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Address_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetVariableAccessAttributes-Request */
PyCompat_DEF_STRUCT(GetVariableAccessAttributes_Request);
PyCompat_DEF_TYPE(GetVariableAccessAttributes_Request);
PyCompat_DEF_ENUM(GetVariableAccessAttributes_Request_PRESENT);

/* Type Converters */
int PyAsnGetVariableAccessAttributes_Request_FromPython(PyObject *pObj, GetVariableAccessAttributes_Request_t *pDst);
PyObject *PyAsnGetVariableAccessAttributes_Request_ToPython(GetVariableAccessAttributes_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnGetVariableAccessAttributes_Request_ModSetupTypes(void);
void PyAsnGetVariableAccessAttributes_Request_ModClear(PyObject *);
int PyAsnGetVariableAccessAttributes_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _GetVariableAccessAttributes_Request_PY_H_ */
