/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Identifier_PY_H_
#define	_Identifier_PY_H_


#include <Identifier.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Identifier */
PyCompat_DEF_STRUCT(Identifier);
PyCompat_DEF_TYPE(Identifier);

/* Type Converters */
static inline int PyAsnIdentifier_FromPython(PyObject *pObj, Identifier_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Identifier, pObj, pDst);
	pDst->buf = (uint8_t *)PyCompatUnicode_AsUTF8AndSize(pObj, &pDst->size);
	return pDst->buf ? 0 : -1;
}
static inline PyObject *PyAsnIdentifier_ToPython(Identifier_t *pSrc, PyObject *parent)
{
	return PyCompatUnicode_FromStringAndSize(pSrc->buf, pSrc->size);
}

/* Module Initializers */
int PyAsnIdentifier_ModSetupTypes(void);
void PyAsnIdentifier_ModClear(PyObject *);
int PyAsnIdentifier_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Identifier_PY_H_ */
