/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Identify_Response_PY_H_
#define	_Identify_Response_PY_H_


#include <Identify-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <py_convert_OBJECT_IDENTIFIER.h>
#include <py_application.h>
#include <py_convert.h>
#include <MMSString_Py.h>
#include <MMSString_Py.h>
#include <MMSString_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Identify-Response */
typedef struct Identify_Response__listOfAbstractSyntaxes Identify_Response_listOfAbstractSyntaxes_ANON_5_t;
PyCompat_DEF_STRUCT(Identify_Response_listOfAbstractSyntaxes_ANON_5);
PyCompat_DEF_TYPE(Identify_Response_listOfAbstractSyntaxes_ANON_5);
PyCompat_DEF_STRUCT(Identify_Response);
PyCompat_DEF_TYPE(Identify_Response);

/* Type Converters */
int PyAsnIdentify_Response_listOfAbstractSyntaxes_ANON_5_FromPython(PyObject *pObj, Identify_Response_listOfAbstractSyntaxes_ANON_5_t *pDst);
PyObject *PyAsnIdentify_Response_listOfAbstractSyntaxes_ANON_5_ToPython(Identify_Response_listOfAbstractSyntaxes_ANON_5_t *pSrc, PyObject *parent);
int PyAsnIdentify_Response_FromPython(PyObject *pObj, Identify_Response_t *pDst);
PyObject *PyAsnIdentify_Response_ToPython(Identify_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnIdentify_Response_ModSetupTypes(void);
void PyAsnIdentify_Response_ModClear(PyObject *);
int PyAsnIdentify_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Identify_Response_PY_H_ */
