/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Implementation_data_PY_H_
#define	_Implementation_data_PY_H_


#include <Implementation-data.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Implementation-data */
PyCompat_DEF_STRUCT(Implementation_data);
PyCompat_DEF_TYPE(Implementation_data);

/* Type Converters */
static inline int PyAsnImplementation_data_FromPython(PyObject *pObj, Implementation_data_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Implementation_data, pObj, pDst);
	pDst->buf = (uint8_t *)PyCompatUnicode_AsUTF8AndSize(pObj, &pDst->size);
	return pDst->buf ? 0 : -1;
}
static inline PyObject *PyAsnImplementation_data_ToPython(Implementation_data_t *pSrc, PyObject *parent)
{
	return PyCompatUnicode_FromStringAndSize(pSrc->buf, pSrc->size);
}

/* Module Initializers */
int PyAsnImplementation_data_ModSetupTypes(void);
void PyAsnImplementation_data_ModClear(PyObject *);
int PyAsnImplementation_data_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Implementation_data_PY_H_ */
