/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InformationReport_PY_H_
#define	_InformationReport_PY_H_


#include <InformationReport.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <AccessResult_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <VariableAccessSpecification_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InformationReport */
typedef struct InformationReport__listOfAccessResult InformationReport_listOfAccessResult_ANON_3_t;
PyCompat_DEF_STRUCT(InformationReport_listOfAccessResult_ANON_3);
PyCompat_DEF_TYPE(InformationReport_listOfAccessResult_ANON_3);
PyCompat_DEF_STRUCT(InformationReport);
PyCompat_DEF_TYPE(InformationReport);

/* Type Converters */
int PyAsnInformationReport_listOfAccessResult_ANON_3_FromPython(PyObject *pObj, InformationReport_listOfAccessResult_ANON_3_t *pDst);
PyObject *PyAsnInformationReport_listOfAccessResult_ANON_3_ToPython(InformationReport_listOfAccessResult_ANON_3_t *pSrc, PyObject *parent);
int PyAsnInformationReport_FromPython(PyObject *pObj, InformationReport_t *pDst);
PyObject *PyAsnInformationReport_ToPython(InformationReport_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnInformationReport_ModSetupTypes(void);
void PyAsnInformationReport_ModClear(PyObject *);
int PyAsnInformationReport_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _InformationReport_PY_H_ */
