/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitiateUnitControlLoad_Request_PY_H_
#define	_InitiateUnitControlLoad_Request_PY_H_


#include <InitiateUnitControlLoad-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateUnitControlLoad-Request */
PyCompat_DEF_STRUCT(InitiateUnitControlLoad_Request);
PyCompat_DEF_TYPE(InitiateUnitControlLoad_Request);

/* Type Converters */
static inline PyObject *PyAsnInitiateUnitControlLoad_Request_ToPython(InitiateUnitControlLoad_Request_t *pSrc, PyObject *parent)
{
	return PyAsnIdentifier_ToPython(pSrc, parent);
}
static inline int PyAsnInitiateUnitControlLoad_Request_FromPython(PyObject *pObj, InitiateUnitControlLoad_Request_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(InitiateUnitControlLoad_Request, pObj, pDst);
	return PyAsnIdentifier_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnInitiateUnitControlLoad_Request_ModSetupTypes(void);
void PyAsnInitiateUnitControlLoad_Request_ModClear(PyObject *);
int PyAsnInitiateUnitControlLoad_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateUnitControlLoad_Request_PY_H_ */
