/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitiateUploadSequence_Response_H_
#define	_InitiateUploadSequence_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Integer32.h"
#include "MMSString.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateUploadSequence-Response */
typedef struct InitiateUploadSequence_Response {
	Integer32_t	 ulsmID;
	struct InitiateUploadSequence_Response__listOfCapabilities {
		A_SEQUENCE_OF(MMSString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfCapabilities;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateUploadSequence_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateUploadSequence_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiateUploadSequence_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiateUploadSequence_Response_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateUploadSequence_Response_H_ */
#include <asn_internal.h>
