/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <InitiateUploadSequence-Response.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfCapabilities __attribute__((weak, alias("asn_DEF_listOfCapabilities_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfCapabilities_3;
static asn_TYPE_descriptor_t asn_DEF_listOfCapabilities;
__attribute__((constructor)) static void asn_DEF_listOfCapabilities_3_alias_init(void) {
	asn_DEF_listOfCapabilities = asn_DEF_listOfCapabilities_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_InitiateUploadSequence_Response__listOfCapabilities_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_MMSString,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfCapabilities_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfCapabilities_specs_3 = {
	sizeof(struct InitiateUploadSequence_Response__listOfCapabilities),
	offsetof(struct InitiateUploadSequence_Response__listOfCapabilities, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfCapabilities_3 = {
	"listOfCapabilities",
	"listOfCapabilities",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfCapabilities_tags_3,
	sizeof(asn_DEF_listOfCapabilities_tags_3)
		/sizeof(asn_DEF_listOfCapabilities_tags_3[0]) - 1, /* 1 */
	asn_DEF_listOfCapabilities_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfCapabilities_tags_3)
		/sizeof(asn_DEF_listOfCapabilities_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_InitiateUploadSequence_Response__listOfCapabilities_3,
	1,	/* Single element */
	&asn_SPC_listOfCapabilities_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_InitiateUploadSequence_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateUploadSequence_Response, ulsmID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Integer32,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ulsmID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateUploadSequence_Response, listOfCapabilities),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfCapabilities_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfCapabilities"
		},
};
static const ber_tlv_tag_t asn_DEF_InitiateUploadSequence_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitiateUploadSequence_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ulsmID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* listOfCapabilities */
};
asn_SEQUENCE_specifics_t asn_SPC_InitiateUploadSequence_Response_specs_1 = {
	sizeof(struct InitiateUploadSequence_Response),
	offsetof(struct InitiateUploadSequence_Response, _asn_ctx),
	asn_MAP_InitiateUploadSequence_Response_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitiateUploadSequence_Response = {
	"InitiateUploadSequence-Response",
	"InitiateUploadSequence-Response",
	&asn_OP_SEQUENCE,
	asn_DEF_InitiateUploadSequence_Response_tags_1,
	sizeof(asn_DEF_InitiateUploadSequence_Response_tags_1)
		/sizeof(asn_DEF_InitiateUploadSequence_Response_tags_1[0]), /* 1 */
	asn_DEF_InitiateUploadSequence_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiateUploadSequence_Response_tags_1)
		/sizeof(asn_DEF_InitiateUploadSequence_Response_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_InitiateUploadSequence_Response_1,
	2,	/* Elements count */
	&asn_SPC_InitiateUploadSequence_Response_specs_1	/* Additional specs */
};

