/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitializeJournal_Request_H_
#define	_InitializeJournal_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeOfDay.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* InitializeJournal-Request */
typedef struct InitializeJournal_Request {
	struct ObjectName	*journalName;
	struct InitializeJournal_Request__limitSpecification {
		TimeOfDay_t	 limitingTime;
		OCTET_STRING_t	*limitingEntry;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *limitSpecification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitializeJournal_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitializeJournal_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_InitializeJournal_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_InitializeJournal_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _InitializeJournal_Request_H_ */
#include <asn_internal.h>
