/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitiateDownloadSequence_Request_PY_H_
#define	_InitiateDownloadSequence_Request_PY_H_


#include <InitiateDownloadSequence-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <MMSString_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateDownloadSequence-Request */
typedef struct InitiateDownloadSequence_Request__listOfCapabilities InitiateDownloadSequence_Request_listOfCapabilities_ANON_3_t;
PyCompat_DEF_STRUCT(InitiateDownloadSequence_Request_listOfCapabilities_ANON_3);
PyCompat_DEF_TYPE(InitiateDownloadSequence_Request_listOfCapabilities_ANON_3);
PyCompat_DEF_STRUCT(InitiateDownloadSequence_Request);
PyCompat_DEF_TYPE(InitiateDownloadSequence_Request);

/* Type Converters */
int PyAsnInitiateDownloadSequence_Request_listOfCapabilities_ANON_3_FromPython(PyObject *pObj, InitiateDownloadSequence_Request_listOfCapabilities_ANON_3_t *pDst);
PyObject *PyAsnInitiateDownloadSequence_Request_listOfCapabilities_ANON_3_ToPython(InitiateDownloadSequence_Request_listOfCapabilities_ANON_3_t *pSrc, PyObject *parent);
int PyAsnInitiateDownloadSequence_Request_FromPython(PyObject *pObj, InitiateDownloadSequence_Request_t *pDst);
PyObject *PyAsnInitiateDownloadSequence_Request_ToPython(InitiateDownloadSequence_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnInitiateDownloadSequence_Request_ModSetupTypes(void);
void PyAsnInitiateDownloadSequence_Request_ModClear(PyObject *);
int PyAsnInitiateDownloadSequence_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateDownloadSequence_Request_PY_H_ */
