/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <Initiate-ErrorPDU.h>
/*
 * This type is implemented using ServiceError,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_Initiate_ErrorPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Initiate_ErrorPDU = {
	"Initiate-ErrorPDU",
	"Initiate-ErrorPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_Initiate_ErrorPDU_tags_1,
	sizeof(asn_DEF_Initiate_ErrorPDU_tags_1)
		/sizeof(asn_DEF_Initiate_ErrorPDU_tags_1[0]), /* 1 */
	asn_DEF_Initiate_ErrorPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_Initiate_ErrorPDU_tags_1)
		/sizeof(asn_DEF_Initiate_ErrorPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ServiceError_1,
	4,	/* Elements count */
	&asn_SPC_ServiceError_specs_1	/* Additional specs */
};

