/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitiateUploadSequence_Request_PY_H_
#define	_InitiateUploadSequence_Request_PY_H_


#include <InitiateUploadSequence-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateUploadSequence-Request */
PyCompat_DEF_STRUCT(InitiateUploadSequence_Request);
PyCompat_DEF_TYPE(InitiateUploadSequence_Request);

/* Type Converters */
static inline PyObject *PyAsnInitiateUploadSequence_Request_ToPython(InitiateUploadSequence_Request_t *pSrc, PyObject *parent)
{
	return PyAsnIdentifier_ToPython(pSrc, parent);
}
static inline int PyAsnInitiateUploadSequence_Request_FromPython(PyObject *pObj, InitiateUploadSequence_Request_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(InitiateUploadSequence_Request, pObj, pDst);
	return PyAsnIdentifier_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnInitiateUploadSequence_Request_ModSetupTypes(void);
void PyAsnInitiateUploadSequence_Request_ModClear(PyObject *);
int PyAsnInitiateUploadSequence_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateUploadSequence_Request_PY_H_ */
