/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitiateUnitControl_Error_PY_H_
#define	_InitiateUnitControl_Error_PY_H_


#include <InitiateUnitControl-Error.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateUnitControl-Error */
PyCompat_DEF_STRUCT(InitiateUnitControl_Error);
PyCompat_DEF_TYPE(InitiateUnitControl_Error);
PyCompat_DEF_ENUM(InitiateUnitControl_Error_PRESENT);

/* Type Converters */
int PyAsnInitiateUnitControl_Error_FromPython(PyObject *pObj, InitiateUnitControl_Error_t *pDst);
PyObject *PyAsnInitiateUnitControl_Error_ToPython(InitiateUnitControl_Error_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnInitiateUnitControl_Error_ModSetupTypes(void);
void PyAsnInitiateUnitControl_Error_ModClear(PyObject *);
int PyAsnInitiateUnitControl_Error_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateUnitControl_Error_PY_H_ */
