/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_InitiateUploadSequence_Response_PY_H_
#define	_InitiateUploadSequence_Response_PY_H_


#include <InitiateUploadSequence-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <MMSString_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <Integer32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitiateUploadSequence-Response */
typedef struct InitiateUploadSequence_Response__listOfCapabilities InitiateUploadSequence_Response_listOfCapabilities_ANON_3_t;
PyCompat_DEF_STRUCT(InitiateUploadSequence_Response_listOfCapabilities_ANON_3);
PyCompat_DEF_TYPE(InitiateUploadSequence_Response_listOfCapabilities_ANON_3);
PyCompat_DEF_STRUCT(InitiateUploadSequence_Response);
PyCompat_DEF_TYPE(InitiateUploadSequence_Response);

/* Type Converters */
int PyAsnInitiateUploadSequence_Response_listOfCapabilities_ANON_3_FromPython(PyObject *pObj, InitiateUploadSequence_Response_listOfCapabilities_ANON_3_t *pDst);
PyObject *PyAsnInitiateUploadSequence_Response_listOfCapabilities_ANON_3_ToPython(InitiateUploadSequence_Response_listOfCapabilities_ANON_3_t *pSrc, PyObject *parent);
int PyAsnInitiateUploadSequence_Response_FromPython(PyObject *pObj, InitiateUploadSequence_Response_t *pDst);
PyObject *PyAsnInitiateUploadSequence_Response_ToPython(InitiateUploadSequence_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnInitiateUploadSequence_Response_ModSetupTypes(void);
void PyAsnInitiateUploadSequence_Response_ModClear(PyObject *);
int PyAsnInitiateUploadSequence_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateUploadSequence_Response_PY_H_ */
