/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Integer16_PY_H_
#define	_Integer16_PY_H_


#include <Integer16.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Integer16 */
PyCompat_DEF_STRUCT(Integer16);
PyCompat_DEF_TYPE(Integer16);

/* Type Converters */
static inline PyObject *PyAsnInteger16_ToPython(Integer16_t *pSrc, PyObject *parent)
{
	return PyCompatLong_FromSsize_t(*pSrc);
}
static inline int PyAsnInteger16_FromPython(PyObject *pObj, Integer16_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Integer16, pObj, pDst);
	PyCompatLong_Check(pObj, -1);
	*pDst = (Integer16_t)PyCompatLong_AsSsize_t(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnInteger16_ModSetupTypes(void);
void PyAsnInteger16_ModClear(PyObject *);
int PyAsnInteger16_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Integer16_PY_H_ */
