/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Integer16_H_
#define	_Integer16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Integer16 */
typedef long	 Integer16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Integer16;
asn_struct_free_f Integer16_free;
asn_struct_print_f Integer16_print;
asn_constr_check_f Integer16_constraint;
ber_type_decoder_f Integer16_decode_ber;
der_type_encoder_f Integer16_encode_der;
xer_type_decoder_f Integer16_decode_xer;
xer_type_encoder_f Integer16_encode_xer;
jer_type_encoder_f Integer16_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Integer16_H_ */
#include <asn_internal.h>
