/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_JournalEntry_PY_H_
#define	_JournalEntry_PY_H_


#include <JournalEntry.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ApplicationReference_Py.h>
#include <EntryContent_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* JournalEntry */
PyCompat_DEF_STRUCT(JournalEntry);
PyCompat_DEF_TYPE(JournalEntry);

/* Type Converters */
int PyAsnJournalEntry_FromPython(PyObject *pObj, JournalEntry_t *pDst);
PyObject *PyAsnJournalEntry_ToPython(JournalEntry_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnJournalEntry_ModSetupTypes(void);
void PyAsnJournalEntry_ModClear(PyObject *);
int PyAsnJournalEntry_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _JournalEntry_PY_H_ */
