/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Journal_Variable_H_
#define	_Journal_Variable_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MMS255String.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data;

/* Journal-Variable */
typedef struct Journal_Variable {
	MMS255String_t	 variableTag;
	struct Data	*valueSpecification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Journal_Variable_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Journal_Variable;
extern asn_SEQUENCE_specifics_t asn_SPC_Journal_Variable_specs_1;
extern asn_TYPE_member_t asn_MBR_Journal_Variable_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Data.h"

#endif	/* _Journal_Variable_H_ */
#include <asn_internal.h>
