/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_JournalEntry_H_
#define	_JournalEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ApplicationReference;
struct EntryContent;

/* JournalEntry */
typedef struct JournalEntry {
	OCTET_STRING_t	 entryIdentifier;
	struct ApplicationReference	*originatingApplication;
	struct EntryContent	*entryContent;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} JournalEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_JournalEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_JournalEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_JournalEntry_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ApplicationReference.h"
#include "EntryContent.h"

#endif	/* _JournalEntry_H_ */
#include <asn_internal.h>
