/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Kill_Response_PY_H_
#define	_Kill_Response_PY_H_


#include <Kill-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Kill-Response */
PyCompat_DEF_STRUCT(Kill_Response);
PyCompat_DEF_TYPE(Kill_Response);

/* Type Converters */
static inline PyObject *PyAsnKill_Response_ToPython(Kill_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnKill_Response_FromPython(PyObject *pObj, Kill_Response_t *pDst)
{
	*pDst = (Kill_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnKill_Response_ModSetupTypes(void);
void PyAsnKill_Response_ModClear(PyObject *);
int PyAsnKill_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Kill_Response_PY_H_ */
