/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_LoadData_H_
#define	_LoadData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadData_PR {
	LoadData_PR_NOTHING,	/* No components present */
	LoadData_PR_non_coded,
	LoadData_PR_coded,
	LoadData_PR_embedded
} LoadData_PR;

/* Forward declarations */
struct EXTERNAL;
struct EMBEDDED_PDV;

/* LoadData */
typedef struct LoadData {
	LoadData_PR present;
	union LoadData_u {
		OCTET_STRING_t	 non_coded;
		struct EXTERNAL	*coded;
		struct EMBEDDED_PDV	*embedded;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadData;
extern asn_CHOICE_specifics_t asn_SPC_LoadData_specs_1;
extern asn_TYPE_member_t asn_MBR_LoadData_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EXTERNAL.h"
#include "EMBEDDED-PDV.h"

#endif	/* _LoadData_H_ */
#include <asn_internal.h>
