/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_LoadDomainContent_Response_PY_H_
#define	_LoadDomainContent_Response_PY_H_


#include <LoadDomainContent-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoadDomainContent-Response */
PyCompat_DEF_STRUCT(LoadDomainContent_Response);
PyCompat_DEF_TYPE(LoadDomainContent_Response);

/* Type Converters */
static inline PyObject *PyAsnLoadDomainContent_Response_ToPython(LoadDomainContent_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnLoadDomainContent_Response_FromPython(PyObject *pObj, LoadDomainContent_Response_t *pDst)
{
	*pDst = (LoadDomainContent_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnLoadDomainContent_Response_ModSetupTypes(void);
void PyAsnLoadDomainContent_Response_ModClear(PyObject *);
int PyAsnLoadDomainContent_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _LoadDomainContent_Response_PY_H_ */
