/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_LoadUnitControlFromFile_Response_PY_H_
#define	_LoadUnitControlFromFile_Response_PY_H_


#include <LoadUnitControlFromFile-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoadUnitControlFromFile-Response */
PyCompat_DEF_STRUCT(LoadUnitControlFromFile_Response);
PyCompat_DEF_TYPE(LoadUnitControlFromFile_Response);

/* Type Converters */
static inline PyObject *PyAsnLoadUnitControlFromFile_Response_ToPython(LoadUnitControlFromFile_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnLoadUnitControlFromFile_Response_FromPython(PyObject *pObj, LoadUnitControlFromFile_Response_t *pDst)
{
	*pDst = (LoadUnitControlFromFile_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnLoadUnitControlFromFile_Response_ModSetupTypes(void);
void PyAsnLoadUnitControlFromFile_Response_ModClear(PyObject *);
int PyAsnLoadUnitControlFromFile_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _LoadUnitControlFromFile_Response_PY_H_ */
