/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_LoadUnitControlFromFile_Error_PY_H_
#define	_LoadUnitControlFromFile_Error_PY_H_


#include <LoadUnitControlFromFile-Error.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoadUnitControlFromFile-Error */
PyCompat_DEF_STRUCT(LoadUnitControlFromFile_Error);
PyCompat_DEF_TYPE(LoadUnitControlFromFile_Error);
PyCompat_DEF_ENUM(LoadUnitControlFromFile_Error_PRESENT);

/* Type Converters */
int PyAsnLoadUnitControlFromFile_Error_FromPython(PyObject *pObj, LoadUnitControlFromFile_Error_t *pDst);
PyObject *PyAsnLoadUnitControlFromFile_Error_ToPython(LoadUnitControlFromFile_Error_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnLoadUnitControlFromFile_Error_ModSetupTypes(void);
void PyAsnLoadUnitControlFromFile_Error_ModClear(PyObject *);
int PyAsnLoadUnitControlFromFile_Error_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _LoadUnitControlFromFile_Error_PY_H_ */
