/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Mechanism_name_PY_H_
#define	_Mechanism_name_PY_H_


#include <Mechanism-name.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <py_convert_OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Mechanism-name */
PyCompat_DEF_STRUCT(Mechanism_name);
PyCompat_DEF_TYPE(Mechanism_name);

/* Type Converters */
static inline int PyAsnMechanism_name_FromPython(PyObject *pObj, Mechanism_name_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Mechanism_name, pObj, pDst);
	return PyCompatOID_FromUnicode(pObj, pDst);
}
static inline PyObject *PyAsnMechanism_name_ToPython(Mechanism_name_t *pSrc, PyObject *parent)
{
	return PyCompatOID_AsUTF8String(pSrc);
}

/* Module Initializers */
int PyAsnMechanism_name_ModSetupTypes(void);
void PyAsnMechanism_name_ModClear(PyObject *);
int PyAsnMechanism_name_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Mechanism_name_PY_H_ */
