/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_MMS255String_PY_H_
#define	_MMS255String_PY_H_


#include <MMS255String.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MMS255String */
PyCompat_DEF_STRUCT(MMS255String);
PyCompat_DEF_TYPE(MMS255String);

/* Type Converters */
static inline int PyAsnMMS255String_FromPython(PyObject *pObj, MMS255String_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(MMS255String, pObj, pDst);
	pDst->buf = (uint8_t *)PyCompatUnicode_AsUTF8AndSize(pObj, &pDst->size);
	return pDst->buf ? 0 : -1;
}
static inline PyObject *PyAsnMMS255String_ToPython(MMS255String_t *pSrc, PyObject *parent)
{
	return PyCompatUnicode_FromStringAndSize(pSrc->buf, pSrc->size);
}

/* Module Initializers */
int PyAsnMMS255String_ModSetupTypes(void);
void PyAsnMMS255String_ModClear(PyObject *);
int PyAsnMMS255String_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _MMS255String_PY_H_ */
