/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_MMSpdu_H_
#define	_MMSpdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Cancel-RequestPDU.h"
#include "Cancel-ResponsePDU.h"
#include "Conclude-RequestPDU.h"
#include "Conclude-ResponsePDU.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MMSpdu_PR {
	MMSpdu_PR_NOTHING,	/* No components present */
	MMSpdu_PR_confirmed_RequestPDU,
	MMSpdu_PR_confirmed_ResponsePDU,
	MMSpdu_PR_confirmed_ErrorPDU,
	MMSpdu_PR_unconfirmed_PDU,
	MMSpdu_PR_rejectPDU,
	MMSpdu_PR_cancel_RequestPDU,
	MMSpdu_PR_cancel_ResponsePDU,
	MMSpdu_PR_cancel_ErrorPDU,
	MMSpdu_PR_initiate_RequestPDU,
	MMSpdu_PR_initiate_ResponsePDU,
	MMSpdu_PR_initiate_ErrorPDU,
	MMSpdu_PR_conclude_RequestPDU,
	MMSpdu_PR_conclude_ResponsePDU,
	MMSpdu_PR_conclude_ErrorPDU
} MMSpdu_PR;

/* Forward declarations */
struct Confirmed_RequestPDU;
struct Confirmed_ResponsePDU;
struct Confirmed_ErrorPDU;
struct Unconfirmed_PDU;
struct RejectPDU;
struct Cancel_ErrorPDU;
struct Initiate_RequestPDU;
struct Initiate_ResponsePDU;
struct Initiate_ErrorPDU;
struct Conclude_ErrorPDU;
struct ServiceError;

/* MMSpdu */
typedef struct MMSpdu {
	MMSpdu_PR present;
	union MMSpdu_u {
		struct Confirmed_RequestPDU	*confirmed_RequestPDU;
		struct Confirmed_ResponsePDU	*confirmed_ResponsePDU;
		struct Confirmed_ErrorPDU	*confirmed_ErrorPDU;
		struct Unconfirmed_PDU	*unconfirmed_PDU;
		struct RejectPDU	*rejectPDU;
		Cancel_RequestPDU_t	 cancel_RequestPDU;
		Cancel_ResponsePDU_t	 cancel_ResponsePDU;
		struct Cancel_ErrorPDU	*cancel_ErrorPDU;
		struct Initiate_RequestPDU	*initiate_RequestPDU;
		struct Initiate_ResponsePDU	*initiate_ResponsePDU;
		struct ServiceError	*initiate_ErrorPDU;
		Conclude_RequestPDU_t	 conclude_RequestPDU;
		Conclude_ResponsePDU_t	 conclude_ResponsePDU;
		struct ServiceError	*conclude_ErrorPDU;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MMSpdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MMSpdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Confirmed-RequestPDU.h"
#include "Confirmed-ResponsePDU.h"
#include "Confirmed-ErrorPDU.h"
#include "Unconfirmed-PDU.h"
#include "RejectPDU.h"
#include "Cancel-ErrorPDU.h"
#include "Initiate-RequestPDU.h"
#include "Initiate-ResponsePDU.h"
#include "Initiate-ErrorPDU.h"
#include "Conclude-ErrorPDU.h"

#endif	/* _MMSpdu_H_ */
#include <asn_internal.h>
