/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ModifierStep_H_
#define	_ModifierStep_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Modifier;

/* ModifierStep */
typedef struct ModifierStep {
	long	 modifierID;
	struct Modifier	*modifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModifierStep_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModifierStep;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Modifier.h"

#endif	/* _ModifierStep_H_ */
#include <asn_internal.h>
