/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Modifier_H_
#define	_Modifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Modifier_PR {
	Modifier_PR_NOTHING,	/* No components present */
	Modifier_PR_eventModifier,
	Modifier_PR_semaphoreModifier
} Modifier_PR;

/* Forward declarations */
struct AttachToEventCondition;
struct AttachToSemaphore;

/* Modifier */
typedef struct Modifier {
	Modifier_PR present;
	union Modifier_u {
		struct AttachToEventCondition	*eventModifier;
		struct AttachToSemaphore	*semaphoreModifier;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Modifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Modifier;
extern asn_CHOICE_specifics_t asn_SPC_Modifier_specs_1;
extern asn_TYPE_member_t asn_MBR_Modifier_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AttachToEventCondition.h"
#include "AttachToSemaphore.h"

#endif	/* _Modifier_H_ */
#include <asn_internal.h>
