/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Name_H_
#define	_Name_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Name_PR {
	Name_PR_NOTHING,	/* No components present */
	Name_PR_rdnSequence
} Name_PR;

/* Forward declarations */
struct RDNSequence;

/* Name */
typedef struct Name {
	Name_PR present;
	union Name_u {
		struct RDNSequence	*rdnSequence;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Name;
extern asn_CHOICE_specifics_t asn_SPC_Name_specs_1;
extern asn_TYPE_member_t asn_MBR_Name_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RDNSequence.h"

#endif	/* _Name_H_ */
#include <asn_internal.h>
