/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Name_PY_H_
#define	_Name_PY_H_


#include <Name.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <RDNSequence_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Name */
PyCompat_DEF_STRUCT(Name);
PyCompat_DEF_TYPE(Name);
PyCompat_DEF_ENUM(Name_PRESENT);

/* Type Converters */
int PyAsnName_FromPython(PyObject *pObj, Name_t *pDst);
PyObject *PyAsnName_ToPython(Name_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnName_ModSetupTypes(void);
void PyAsnName_ModClear(PyObject *);
int PyAsnName_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Name_PY_H_ */
