/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ObjectClass_PY_H_
#define	_ObjectClass_PY_H_


#include <ObjectClass.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectClass */
PyCompat_DEF_STRUCT(ObjectClass);
PyCompat_DEF_TYPE(ObjectClass);
PyCompat_DEF_ENUM(ObjectClass_PRESENT);
PyCompat_DEF_ENUM(ObjectClass_basicObjectClass);
PyCompat_DEF_ENUM(ObjectClass_csObjectClass);

/* Type Converters */
int PyAsnObjectClass_FromPython(PyObject *pObj, ObjectClass_t *pDst);
PyObject *PyAsnObjectClass_ToPython(ObjectClass_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnObjectClass_ModSetupTypes(void);
void PyAsnObjectClass_ModClear(PyObject *);
int PyAsnObjectClass_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectClass_PY_H_ */
