/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ObtainFile_Request_H_
#define	_ObtainFile_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ApplicationReference;
struct FileName;

/* ObtainFile-Request */
typedef struct ObtainFile_Request {
	struct ApplicationReference	*sourceFileServer;	/* OPTIONAL */
	struct FileName	*sourceFile;
	struct FileName	*destinationFile;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObtainFile_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObtainFile_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_ObtainFile_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_ObtainFile_Request_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ApplicationReference.h"
#include "FileName.h"

#endif	/* _ObtainFile_Request_H_ */
#include <asn_internal.h>
