/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ObtainFile_Response_PY_H_
#define	_ObtainFile_Response_PY_H_


#include <ObtainFile-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ObtainFile-Response */
PyCompat_DEF_STRUCT(ObtainFile_Response);
PyCompat_DEF_TYPE(ObtainFile_Response);

/* Type Converters */
static inline PyObject *PyAsnObtainFile_Response_ToPython(ObtainFile_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnObtainFile_Response_FromPython(PyObject *pObj, ObtainFile_Response_t *pDst)
{
	*pDst = (ObtainFile_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnObtainFile_Response_ModSetupTypes(void);
void PyAsnObtainFile_Response_ModClear(PyObject *);
int PyAsnObtainFile_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ObtainFile_Response_PY_H_ */
