/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_OperationState_PY_H_
#define	_OperationState_PY_H_


#include <OperationState.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OperationState */
PyCompat_DEF_STRUCT(OperationState);
PyCompat_DEF_TYPE(OperationState);
PyCompat_DEF_ENUM(OperationState);

/* Type Converters */
static inline int PyAsnOperationState_FromPython(PyObject *pObj, OperationState_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(OperationState, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnOperationState_ToPython(OperationState_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumOperationState_Type, *pSrc);
}

/* Module Initializers */
int PyAsnOperationState_ModSetupTypes(void);
void PyAsnOperationState_ModClear(PyObject *);
int PyAsnOperationState_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _OperationState_PY_H_ */
