/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Priority_PY_H_
#define	_Priority_PY_H_


#include <Priority.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Priority */
PyCompat_DEF_STRUCT(Priority);
PyCompat_DEF_TYPE(Priority);

/* Type Converters */
static inline PyObject *PyAsnPriority_ToPython(Priority_t *pSrc, PyObject *parent)
{
	return PyCompatLong_FromSsize_t(*pSrc);
}
static inline int PyAsnPriority_FromPython(PyObject *pObj, Priority_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Priority, pObj, pDst);
	PyCompatLong_Check(pObj, -1);
	*pDst = (Priority_t)PyCompatLong_AsSsize_t(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnPriority_ModSetupTypes(void);
void PyAsnPriority_ModClear(PyObject *);
int PyAsnPriority_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Priority_PY_H_ */
