/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_RDNSequence_PY_H_
#define	_RDNSequence_PY_H_


#include <RDNSequence.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <RelativeDistinguishedName_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RDNSequence */
PyCompat_DEF_STRUCT(RDNSequence);
PyCompat_DEF_TYPE(RDNSequence);

/* Type Converters */
int PyAsnRDNSequence_FromPython(PyObject *pObj, RDNSequence_t *pDst);
PyObject *PyAsnRDNSequence_ToPython(RDNSequence_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnRDNSequence_ModSetupTypes(void);
void PyAsnRDNSequence_ModClear(PyObject *);
int PyAsnRDNSequence_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RDNSequence_PY_H_ */
