/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <ReadJournal-Response.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry __attribute__((weak, alias("asn_DEF_listOfJournalEntry_2")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry_2;
static asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry;
__attribute__((constructor)) static void asn_DEF_listOfJournalEntry_2_alias_init(void) {
	asn_DEF_listOfJournalEntry = asn_DEF_listOfJournalEntry_2;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_ReadJournal_Response__listOfJournalEntry_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_JournalEntry,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfJournalEntry_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfJournalEntry_specs_2 = {
	sizeof(struct ReadJournal_Response__listOfJournalEntry),
	offsetof(struct ReadJournal_Response__listOfJournalEntry, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry_2 = {
	"listOfJournalEntry",
	"listOfJournalEntry",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfJournalEntry_tags_2,
	sizeof(asn_DEF_listOfJournalEntry_tags_2)
		/sizeof(asn_DEF_listOfJournalEntry_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfJournalEntry_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfJournalEntry_tags_2)
		/sizeof(asn_DEF_listOfJournalEntry_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ReadJournal_Response__listOfJournalEntry_2,
	1,	/* Single element */
	&asn_SPC_listOfJournalEntry_specs_2	/* Additional specs */
};

static int asn_DFL_4_cmp_0(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_4_set_0(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
asn_TYPE_member_t asn_MBR_ReadJournal_Response_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReadJournal_Response, listOfJournalEntry),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_listOfJournalEntry_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfJournalEntry"
		},
	{ ATF_NOFLAGS, 1, offsetof(struct ReadJournal_Response, moreFollows),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		&asn_DFL_4_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_4_set_0,	/* Set DEFAULT 0 */
		"moreFollows"
		},
};
static const int asn_MAP_ReadJournal_Response_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ReadJournal_Response_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ReadJournal_Response_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfJournalEntry */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* moreFollows */
};
asn_SEQUENCE_specifics_t asn_SPC_ReadJournal_Response_specs_1 = {
	sizeof(struct ReadJournal_Response),
	offsetof(struct ReadJournal_Response, _asn_ctx),
	asn_MAP_ReadJournal_Response_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ReadJournal_Response_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ReadJournal_Response = {
	"ReadJournal-Response",
	"ReadJournal-Response",
	&asn_OP_SEQUENCE,
	asn_DEF_ReadJournal_Response_tags_1,
	sizeof(asn_DEF_ReadJournal_Response_tags_1)
		/sizeof(asn_DEF_ReadJournal_Response_tags_1[0]), /* 1 */
	asn_DEF_ReadJournal_Response_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReadJournal_Response_tags_1)
		/sizeof(asn_DEF_ReadJournal_Response_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ReadJournal_Response_1,
	2,	/* Elements count */
	&asn_SPC_ReadJournal_Response_specs_1	/* Additional specs */
};

