/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Read_Request_H_
#define	_Read_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableAccessSpecification;

/* Read-Request */
typedef struct Read_Request {
	BOOLEAN_t	 specificationWithResult;	/* DEFAULT FALSE */
	struct VariableAccessSpecification	*variableAccessSpecification;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Read_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Read_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_Read_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_Read_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableAccessSpecification.h"

#endif	/* _Read_Request_H_ */
#include <asn_internal.h>
