/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_RelativeDistinguishedName_PY_H_
#define	_RelativeDistinguishedName_PY_H_


#include <RelativeDistinguishedName.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <AttributeTypeAndValue_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RelativeDistinguishedName */
PyCompat_DEF_STRUCT(RelativeDistinguishedName);
PyCompat_DEF_TYPE(RelativeDistinguishedName);

/* Type Converters */
int PyAsnRelativeDistinguishedName_FromPython(PyObject *pObj, RelativeDistinguishedName_t *pDst);
PyObject *PyAsnRelativeDistinguishedName_ToPython(RelativeDistinguishedName_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnRelativeDistinguishedName_ModSetupTypes(void);
void PyAsnRelativeDistinguishedName_ModClear(PyObject *);
int PyAsnRelativeDistinguishedName_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RelativeDistinguishedName_PY_H_ */
