/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Release_request_reason_PY_H_
#define	_Release_request_reason_PY_H_


#include <Release-request-reason.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Release-request-reason */
PyCompat_DEF_STRUCT(Release_request_reason);
PyCompat_DEF_TYPE(Release_request_reason);
PyCompat_DEF_ENUM(Release_request_reason);

/* Type Converters */
static inline int PyAsnRelease_request_reason_FromPython(PyObject *pObj, Release_request_reason_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Release_request_reason, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnRelease_request_reason_ToPython(Release_request_reason_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumRelease_request_reason_Type, *pSrc);
}

/* Module Initializers */
int PyAsnRelease_request_reason_ModSetupTypes(void);
void PyAsnRelease_request_reason_ModClear(PyObject *);
int PyAsnRelease_request_reason_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Release_request_reason_PY_H_ */
