/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_Release_response_reason_PY_H_
#define	_Release_response_reason_PY_H_


#include <Release-response-reason.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Release-response-reason */
PyCompat_DEF_STRUCT(Release_response_reason);
PyCompat_DEF_TYPE(Release_response_reason);
PyCompat_DEF_ENUM(Release_response_reason);

/* Type Converters */
static inline int PyAsnRelease_response_reason_FromPython(PyObject *pObj, Release_response_reason_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Release_response_reason, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnRelease_response_reason_ToPython(Release_response_reason_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumRelease_response_reason_Type, *pSrc);
}

/* Module Initializers */
int PyAsnRelease_response_reason_ModSetupTypes(void);
void PyAsnRelease_response_reason_ModClear(PyObject *);
int PyAsnRelease_response_reason_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Release_response_reason_PY_H_ */
