/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_RemoveEventConditionListReference_Request_H_
#define	_RemoveEventConditionListReference_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* RemoveEventConditionListReference-Request */
typedef struct RemoveEventConditionListReference_Request {
	struct ObjectName	*eventConditionListName;
	struct RemoveEventConditionListReference_Request__listOfEventConditionName {
		A_SEQUENCE_OF(struct ObjectName) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfEventConditionName;
	struct RemoveEventConditionListReference_Request__listOfEventConditionListName {
		A_SEQUENCE_OF(struct ObjectName) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfEventConditionListName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RemoveEventConditionListReference_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RemoveEventConditionListReference_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_RemoveEventConditionListReference_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_RemoveEventConditionListReference_Request_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _RemoveEventConditionListReference_Request_H_ */
#include <asn_internal.h>
