/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_RemoveFromUnitControl_Response_PY_H_
#define	_RemoveFromUnitControl_Response_PY_H_


#include <RemoveFromUnitControl-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RemoveFromUnitControl-Response */
PyCompat_DEF_STRUCT(RemoveFromUnitControl_Response);
PyCompat_DEF_TYPE(RemoveFromUnitControl_Response);

/* Type Converters */
static inline PyObject *PyAsnRemoveFromUnitControl_Response_ToPython(RemoveFromUnitControl_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnRemoveFromUnitControl_Response_FromPython(PyObject *pObj, RemoveFromUnitControl_Response_t *pDst)
{
	*pDst = (RemoveFromUnitControl_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnRemoveFromUnitControl_Response_ModSetupTypes(void);
void PyAsnRemoveFromUnitControl_Response_ModClear(PyObject *);
int PyAsnRemoveFromUnitControl_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RemoveFromUnitControl_Response_PY_H_ */
