/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_RemoveEventConditionListReference_Response_PY_H_
#define	_RemoveEventConditionListReference_Response_PY_H_


#include <RemoveEventConditionListReference-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RemoveEventConditionListReference-Response */
PyCompat_DEF_STRUCT(RemoveEventConditionListReference_Response);
PyCompat_DEF_TYPE(RemoveEventConditionListReference_Response);

/* Type Converters */
static inline PyObject *PyAsnRemoveEventConditionListReference_Response_ToPython(RemoveEventConditionListReference_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnRemoveEventConditionListReference_Response_FromPython(PyObject *pObj, RemoveEventConditionListReference_Response_t *pDst)
{
	*pDst = (RemoveEventConditionListReference_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnRemoveEventConditionListReference_Response_ModSetupTypes(void);
void PyAsnRemoveEventConditionListReference_Response_ModClear(PyObject *);
int PyAsnRemoveEventConditionListReference_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RemoveEventConditionListReference_Response_PY_H_ */
