/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <RemoveEventConditionListReference-Request.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfEventConditionName __attribute__((weak, alias("asn_DEF_listOfEventConditionName_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfEventConditionName_3;
static asn_TYPE_descriptor_t asn_DEF_listOfEventConditionName;
__attribute__((constructor)) static void asn_DEF_listOfEventConditionName_3_alias_init(void) {
	asn_DEF_listOfEventConditionName = asn_DEF_listOfEventConditionName_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfEventConditionListName __attribute__((weak, alias("asn_DEF_listOfEventConditionListName_5")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfEventConditionListName_5;
static asn_TYPE_descriptor_t asn_DEF_listOfEventConditionListName;
__attribute__((constructor)) static void asn_DEF_listOfEventConditionListName_5_alias_init(void) {
	asn_DEF_listOfEventConditionListName = asn_DEF_listOfEventConditionListName_5;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_RemoveEventConditionListReference_Request__listOfEventConditionName_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfEventConditionName_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfEventConditionName_specs_3 = {
	sizeof(struct RemoveEventConditionListReference_Request__listOfEventConditionName),
	offsetof(struct RemoveEventConditionListReference_Request__listOfEventConditionName, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfEventConditionName_3 = {
	"listOfEventConditionName",
	"listOfEventConditionName",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfEventConditionName_tags_3,
	sizeof(asn_DEF_listOfEventConditionName_tags_3)
		/sizeof(asn_DEF_listOfEventConditionName_tags_3[0]) - 1, /* 1 */
	asn_DEF_listOfEventConditionName_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfEventConditionName_tags_3)
		/sizeof(asn_DEF_listOfEventConditionName_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_RemoveEventConditionListReference_Request__listOfEventConditionName_3,
	1,	/* Single element */
	&asn_SPC_listOfEventConditionName_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RemoveEventConditionListReference_Request__listOfEventConditionListName_5[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ObjectName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfEventConditionListName_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfEventConditionListName_specs_5 = {
	sizeof(struct RemoveEventConditionListReference_Request__listOfEventConditionListName),
	offsetof(struct RemoveEventConditionListReference_Request__listOfEventConditionListName, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfEventConditionListName_5 = {
	"listOfEventConditionListName",
	"listOfEventConditionListName",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfEventConditionListName_tags_5,
	sizeof(asn_DEF_listOfEventConditionListName_tags_5)
		/sizeof(asn_DEF_listOfEventConditionListName_tags_5[0]) - 1, /* 1 */
	asn_DEF_listOfEventConditionListName_tags_5,	/* Same as above */
	sizeof(asn_DEF_listOfEventConditionListName_tags_5)
		/sizeof(asn_DEF_listOfEventConditionListName_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_RemoveEventConditionListReference_Request__listOfEventConditionListName_5,
	1,	/* Single element */
	&asn_SPC_listOfEventConditionListName_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RemoveEventConditionListReference_Request_1[] = {
	{ ATF_POINTER, 0, offsetof(struct RemoveEventConditionListReference_Request, eventConditionListName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"eventConditionListName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoveEventConditionListReference_Request, listOfEventConditionName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfEventConditionName_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfEventConditionName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoveEventConditionListReference_Request, listOfEventConditionListName),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_listOfEventConditionListName_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfEventConditionListName"
		},
};
static const ber_tlv_tag_t asn_DEF_RemoveEventConditionListReference_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RemoveEventConditionListReference_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventConditionListName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listOfEventConditionName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* listOfEventConditionListName */
};
asn_SEQUENCE_specifics_t asn_SPC_RemoveEventConditionListReference_Request_specs_1 = {
	sizeof(struct RemoveEventConditionListReference_Request),
	offsetof(struct RemoveEventConditionListReference_Request, _asn_ctx),
	asn_MAP_RemoveEventConditionListReference_Request_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RemoveEventConditionListReference_Request = {
	"RemoveEventConditionListReference-Request",
	"RemoveEventConditionListReference-Request",
	&asn_OP_SEQUENCE,
	asn_DEF_RemoveEventConditionListReference_Request_tags_1,
	sizeof(asn_DEF_RemoveEventConditionListReference_Request_tags_1)
		/sizeof(asn_DEF_RemoveEventConditionListReference_Request_tags_1[0]), /* 1 */
	asn_DEF_RemoveEventConditionListReference_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_RemoveEventConditionListReference_Request_tags_1)
		/sizeof(asn_DEF_RemoveEventConditionListReference_Request_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RemoveEventConditionListReference_Request_1,
	3,	/* Elements count */
	&asn_SPC_RemoveEventConditionListReference_Request_specs_1	/* Additional specs */
};

