/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Rename_Response_PY_H_
#define	_Rename_Response_PY_H_


#include <Rename-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Rename-Response */
PyCompat_DEF_STRUCT(Rename_Response);
PyCompat_DEF_TYPE(Rename_Response);

/* Type Converters */
static inline PyObject *PyAsnRename_Response_ToPython(Rename_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnRename_Response_FromPython(PyObject *pObj, Rename_Response_t *pDst)
{
	*pDst = (Rename_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnRename_Response_ModSetupTypes(void);
void PyAsnRename_Response_ModClear(PyObject *);
int PyAsnRename_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Rename_Response_PY_H_ */
