/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Rename_Request_H_
#define	_Rename_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectClass;
struct ObjectName;

/* Rename-Request */
typedef struct Rename_Request {
	struct ObjectClass	*objectClass;
	struct ObjectName	*currentName;
	Identifier_t	 newIdentifier;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Rename_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Rename_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_Rename_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_Rename_Request_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectClass.h"
#include "ObjectName.h"

#endif	/* _Rename_Request_H_ */
#include <asn_internal.h>
