/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportJournalStatus_Response_PY_H_
#define	_ReportJournalStatus_Response_PY_H_


#include <ReportJournalStatus-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportJournalStatus-Response */
PyCompat_DEF_STRUCT(ReportJournalStatus_Response);
PyCompat_DEF_TYPE(ReportJournalStatus_Response);

/* Type Converters */
int PyAsnReportJournalStatus_Response_FromPython(PyObject *pObj, ReportJournalStatus_Response_t *pDst);
PyObject *PyAsnReportJournalStatus_Response_ToPython(ReportJournalStatus_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnReportJournalStatus_Response_ModSetupTypes(void);
void PyAsnReportJournalStatus_Response_ModClear(PyObject *);
int PyAsnReportJournalStatus_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ReportJournalStatus_Response_PY_H_ */
