/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportSemaphoreStatus_Response_PY_H_
#define	_ReportSemaphoreStatus_Response_PY_H_


#include <ReportSemaphoreStatus-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned16_Py.h>
#include <Unsigned16_Py.h>
#include <Unsigned16_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportSemaphoreStatus-Response */
PyCompat_DEF_STRUCT(ReportSemaphoreStatus_Response);
PyCompat_DEF_TYPE(ReportSemaphoreStatus_Response);
PyCompat_DEF_ENUM(ReportSemaphoreStatus_Response_Class);

/* Type Converters */
int PyAsnReportSemaphoreStatus_Response_FromPython(PyObject *pObj, ReportSemaphoreStatus_Response_t *pDst);
PyObject *PyAsnReportSemaphoreStatus_Response_ToPython(ReportSemaphoreStatus_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnReportSemaphoreStatus_Response_ModSetupTypes(void);
void PyAsnReportSemaphoreStatus_Response_ModClear(PyObject *);
int PyAsnReportSemaphoreStatus_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ReportSemaphoreStatus_Response_PY_H_ */
