/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportEventConditionStatus_Response_PY_H_
#define	_ReportEventConditionStatus_Response_PY_H_


#include <ReportEventConditionStatus-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <EC-State_Py.h>
#include <Unsigned32_Py.h>
#include <EventTime_Py.h>
#include <EventTime_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportEventConditionStatus-Response */
PyCompat_DEF_STRUCT(ReportEventConditionStatus_Response);
PyCompat_DEF_TYPE(ReportEventConditionStatus_Response);

/* Type Converters */
int PyAsnReportEventConditionStatus_Response_FromPython(PyObject *pObj, ReportEventConditionStatus_Response_t *pDst);
PyObject *PyAsnReportEventConditionStatus_Response_ToPython(ReportEventConditionStatus_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnReportEventConditionStatus_Response_ModSetupTypes(void);
void PyAsnReportEventConditionStatus_Response_ModClear(PyObject *);
int PyAsnReportEventConditionStatus_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ReportEventConditionStatus_Response_PY_H_ */
