/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportEventConditionListStatus_Request_H_
#define	_ReportEventConditionListStatus_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* ReportEventConditionListStatus-Request */
typedef struct ReportEventConditionListStatus_Request {
	struct ObjectName	*eventConditionListName;
	Identifier_t	*continueAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportEventConditionListStatus_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportEventConditionListStatus_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportEventConditionListStatus_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportEventConditionListStatus_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _ReportEventConditionListStatus_Request_H_ */
#include <asn_internal.h>
