/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportPoolSemaphoreStatus_Response_H_
#define	_ReportPoolSemaphoreStatus_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "Identifier.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR {
	ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR_NOTHING,	/* No components present */
	ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR_freeNamedToken,
	ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR_ownedNamedToken,
	ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR_hungNamedToken
} ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR;

/* Forward definitions */
typedef struct ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member {
	ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_PR present;
	union ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member_u {
		Identifier_t	 freeNamedToken;
		Identifier_t	 ownedNamedToken;
		Identifier_t	 hungNamedToken;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member;

/* ReportPoolSemaphoreStatus-Response */
typedef struct ReportPoolSemaphoreStatus_Response {
	struct ReportPoolSemaphoreStatus_Response__listOfNamedTokens {
		A_SEQUENCE_OF(ReportPoolSemaphoreStatus_Response__listOfNamedTokens__listOfNamedTokens_Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfNamedTokens;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportPoolSemaphoreStatus_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportPoolSemaphoreStatus_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportPoolSemaphoreStatus_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportPoolSemaphoreStatus_Response_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ReportPoolSemaphoreStatus_Response_H_ */
#include <asn_internal.h>
