/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportSemaphoreEntryStatus_Request_H_
#define	_ReportSemaphoreEntryStatus_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportSemaphoreEntryStatus_Request__state {
	ReportSemaphoreEntryStatus_Request__state_queued	= 0,
	ReportSemaphoreEntryStatus_Request__state_owner	= 1,
	ReportSemaphoreEntryStatus_Request__state_hung	= 2
} e_ReportSemaphoreEntryStatus_Request__state;

/* Forward declarations */
struct ObjectName;

/* ReportSemaphoreEntryStatus-Request */
typedef struct ReportSemaphoreEntryStatus_Request {
	struct ObjectName	*semaphoreName;
	long	 state;
	OCTET_STRING_t	*entryIDToStartAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportSemaphoreEntryStatus_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportSemaphoreEntryStatus_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportSemaphoreEntryStatus_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportSemaphoreEntryStatus_Request_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _ReportSemaphoreEntryStatus_Request_H_ */
#include <asn_internal.h>
