/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportEventActionStatus_Response_PY_H_
#define	_ReportEventActionStatus_Response_PY_H_


#include <ReportEventActionStatus-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Unsigned32_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportEventActionStatus-Response */
PyCompat_DEF_STRUCT(ReportEventActionStatus_Response);
PyCompat_DEF_TYPE(ReportEventActionStatus_Response);

/* Type Converters */
static inline PyObject *PyAsnReportEventActionStatus_Response_ToPython(ReportEventActionStatus_Response_t *pSrc, PyObject *parent)
{
	return PyAsnUnsigned32_ToPython(pSrc, parent);
}
static inline int PyAsnReportEventActionStatus_Response_FromPython(PyObject *pObj, ReportEventActionStatus_Response_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(ReportEventActionStatus_Response, pObj, pDst);
	return PyAsnUnsigned32_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnReportEventActionStatus_Response_ModSetupTypes(void);
void PyAsnReportEventActionStatus_Response_ModClear(PyObject *);
int PyAsnReportEventActionStatus_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ReportEventActionStatus_Response_PY_H_ */
