/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportAccessControlledObjects_Response_H_
#define	_ReportAccessControlledObjects_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* ReportAccessControlledObjects-Response */
typedef struct ReportAccessControlledObjects_Response {
	struct ReportAccessControlledObjects_Response__listOfNames {
		A_SEQUENCE_OF(struct ObjectName) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfNames;
	BOOLEAN_t	 moreFollows;	/* DEFAULT FALSE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportAccessControlledObjects_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportAccessControlledObjects_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_ReportAccessControlledObjects_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportAccessControlledObjects_Response_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _ReportAccessControlledObjects_Response_H_ */
#include <asn_internal.h>
