/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportEventConditionListStatus_Response_PY_H_
#define	_ReportEventConditionListStatus_Response_PY_H_


#include <ReportEventConditionListStatus-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <EventConditionStatus_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportEventConditionListStatus-Response */
typedef struct ReportEventConditionListStatus_Response__listOfEventConditionStatus ReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2_t;
PyCompat_DEF_STRUCT(ReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2);
PyCompat_DEF_TYPE(ReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2);
PyCompat_DEF_STRUCT(ReportEventConditionListStatus_Response);
PyCompat_DEF_TYPE(ReportEventConditionListStatus_Response);

/* Type Converters */
int PyAsnReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2_FromPython(PyObject *pObj, ReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2_t *pDst);
PyObject *PyAsnReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2_ToPython(ReportEventConditionListStatus_Response_listOfEventConditionStatus_ANON_2_t *pSrc, PyObject *parent);
int PyAsnReportEventConditionListStatus_Response_FromPython(PyObject *pObj, ReportEventConditionListStatus_Response_t *pDst);
PyObject *PyAsnReportEventConditionListStatus_Response_ToPython(ReportEventConditionListStatus_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnReportEventConditionListStatus_Response_ModSetupTypes(void);
void PyAsnReportEventConditionListStatus_Response_ModClear(PyObject *);
int PyAsnReportEventConditionListStatus_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ReportEventConditionListStatus_Response_PY_H_ */
