/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ReportEventConditionListStatus_Request_PY_H_
#define	_ReportEventConditionListStatus_Request_PY_H_


#include <ReportEventConditionListStatus-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportEventConditionListStatus-Request */
PyCompat_DEF_STRUCT(ReportEventConditionListStatus_Request);
PyCompat_DEF_TYPE(ReportEventConditionListStatus_Request);

/* Type Converters */
int PyAsnReportEventConditionListStatus_Request_FromPython(PyObject *pObj, ReportEventConditionListStatus_Request_t *pDst);
PyObject *PyAsnReportEventConditionListStatus_Request_ToPython(ReportEventConditionListStatus_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnReportEventConditionListStatus_Request_ModSetupTypes(void);
void PyAsnReportEventConditionListStatus_Request_ModClear(PyObject *);
int PyAsnReportEventConditionListStatus_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ReportEventConditionListStatus_Request_PY_H_ */
