/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_RequestDomainUpload_Response_PY_H_
#define	_RequestDomainUpload_Response_PY_H_


#include <RequestDomainUpload-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RequestDomainUpload-Response */
PyCompat_DEF_STRUCT(RequestDomainUpload_Response);
PyCompat_DEF_TYPE(RequestDomainUpload_Response);

/* Type Converters */
static inline PyObject *PyAsnRequestDomainUpload_Response_ToPython(RequestDomainUpload_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnRequestDomainUpload_Response_FromPython(PyObject *pObj, RequestDomainUpload_Response_t *pDst)
{
	*pDst = (RequestDomainUpload_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnRequestDomainUpload_Response_ModSetupTypes(void);
void PyAsnRequestDomainUpload_Response_ModClear(PyObject *);
int PyAsnRequestDomainUpload_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RequestDomainUpload_Response_PY_H_ */
