/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Request_Detail_H_
#define	_Request_Detail_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "CS-CreateProgramInvocation-Request.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Request_Detail_PR {
	Request_Detail_PR_NOTHING,	/* No components present */
	Request_Detail_PR_otherRequests,
	Request_Detail_PR_createProgramInvocation,
	Request_Detail_PR_start,
	Request_Detail_PR_resume,
	Request_Detail_PR_defineEventCondition,
	Request_Detail_PR_alterEventConditionMonitoring,
	Request_Detail_PR_defineEventEnrollment,
	Request_Detail_PR_alterEventEnrollment
} Request_Detail_PR;

/* Forward declarations */
struct CS_Start_Request;
struct CS_Resume_Request;
struct CS_DefineEventCondition_Request;
struct CS_AlterEventConditionMonitoring_Request;
struct CS_DefineEventEnrollment_Request;
struct CS_AlterEventEnrollment_Request;

/* Request-Detail */
typedef struct Request_Detail {
	Request_Detail_PR present;
	union Request_Detail_u {
		NULL_t	 otherRequests;
		CS_CreateProgramInvocation_Request_t	 createProgramInvocation;
		struct CS_Start_Request	*start;
		struct CS_Resume_Request	*resume;
		struct CS_DefineEventCondition_Request	*defineEventCondition;
		struct CS_AlterEventConditionMonitoring_Request	*alterEventConditionMonitoring;
		struct CS_DefineEventEnrollment_Request	*defineEventEnrollment;
		struct CS_AlterEventEnrollment_Request	*alterEventEnrollment;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Request_Detail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Request_Detail;
extern asn_CHOICE_specifics_t asn_SPC_Request_Detail_specs_1;
extern asn_TYPE_member_t asn_MBR_Request_Detail_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CS-Start-Request.h"
#include "CS-Resume-Request.h"
#include "CS-DefineEventCondition-Request.h"
#include "CS-AlterEventConditionMonitoring-Request.h"
#include "CS-DefineEventEnrollment-Request.h"
#include "CS-AlterEventEnrollment-Request.h"

#endif	/* _Request_Detail_H_ */
#include <asn_internal.h>
