/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_RequestDomainDownload_Request_H_
#define	_RequestDomainDownload_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <BOOLEAN.h>
#include "MMSString.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileName;

/* RequestDomainDownload-Request */
typedef struct RequestDomainDownload_Request {
	Identifier_t	 domainName;
	struct RequestDomainDownload_Request__listOfCapabilities {
		A_SEQUENCE_OF(MMSString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfCapabilities;
	BOOLEAN_t	 sharable;
	struct FileName	*fileName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestDomainDownload_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestDomainDownload_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_RequestDomainDownload_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_RequestDomainDownload_Request_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileName.h"

#endif	/* _RequestDomainDownload_Request_H_ */
#include <asn_internal.h>
