/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Response_Detail_H_
#define	_Response_Detail_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Response_Detail_PR {
	Response_Detail_PR_NOTHING,	/* No components present */
	Response_Detail_PR_otherRequests,
	Response_Detail_PR_status,
	Response_Detail_PR_getProgramInvocationAttributes,
	Response_Detail_PR_getEventConditionAttributes
} Response_Detail_PR;

/* Forward declarations */
struct CS_Status_Response;
struct CS_GetProgramInvocationAttributes_Response;
struct CS_GetEventConditionAttributes_Response;

/* Response-Detail */
typedef struct Response_Detail {
	Response_Detail_PR present;
	union Response_Detail_u {
		NULL_t	 otherRequests;
		struct CS_Status_Response	*status;
		struct CS_GetProgramInvocationAttributes_Response	*getProgramInvocationAttributes;
		struct CS_GetEventConditionAttributes_Response	*getEventConditionAttributes;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Response_Detail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Response_Detail;
extern asn_CHOICE_specifics_t asn_SPC_Response_Detail_specs_1;
extern asn_TYPE_member_t asn_MBR_Response_Detail_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CS-Status-Response.h"
#include "CS-GetProgramInvocationAttributes-Response.h"
#include "CS-GetEventConditionAttributes-Response.h"

#endif	/* _Response_Detail_H_ */
#include <asn_internal.h>
