/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Resume_Response_PY_H_
#define	_Resume_Response_PY_H_


#include <Resume-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Resume-Response */
PyCompat_DEF_STRUCT(Resume_Response);
PyCompat_DEF_TYPE(Resume_Response);

/* Type Converters */
static inline PyObject *PyAsnResume_Response_ToPython(Resume_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnResume_Response_FromPython(PyObject *pObj, Resume_Response_t *pDst)
{
	*pDst = (Resume_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnResume_Response_ModSetupTypes(void);
void PyAsnResume_Response_ModClear(PyObject *);
int PyAsnResume_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Resume_Response_PY_H_ */
