/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Resume_Error_H_
#define	_Resume_Error_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProgramInvocationState.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Resume-Error */
typedef ProgramInvocationState_t	 Resume_Error_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Resume_Error;
asn_struct_free_f Resume_Error_free;
asn_struct_print_f Resume_Error_print;
asn_constr_check_f Resume_Error_constraint;
ber_type_decoder_f Resume_Error_decode_ber;
der_type_encoder_f Resume_Error_encode_der;
xer_type_decoder_f Resume_Error_decode_xer;
xer_type_encoder_f Resume_Error_encode_xer;
jer_type_encoder_f Resume_Error_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Resume_Error_H_ */
#include <asn_internal.h>
