/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_RLRE_apdu_PY_H_
#define	_RLRE_apdu_PY_H_


#include <RLRE-apdu.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Release-response-reason_Py.h>
#include <Association-information_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RLRE-apdu */
PyCompat_DEF_STRUCT(RLRE_apdu);
PyCompat_DEF_TYPE(RLRE_apdu);

/* Type Converters */
int PyAsnRLRE_apdu_FromPython(PyObject *pObj, RLRE_apdu_t *pDst);
PyObject *PyAsnRLRE_apdu_ToPython(RLRE_apdu_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnRLRE_apdu_ModSetupTypes(void);
void PyAsnRLRE_apdu_ModClear(PyObject *);
int PyAsnRLRE_apdu_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RLRE_apdu_PY_H_ */
