/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_RLRQ_apdu_PY_H_
#define	_RLRQ_apdu_PY_H_


#include <RLRQ-apdu.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Release-request-reason_Py.h>
#include <Association-information_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RLRQ-apdu */
PyCompat_DEF_STRUCT(RLRQ_apdu);
PyCompat_DEF_TYPE(RLRQ_apdu);

/* Type Converters */
int PyAsnRLRQ_apdu_FromPython(PyObject *pObj, RLRQ_apdu_t *pDst);
PyObject *PyAsnRLRQ_apdu_ToPython(RLRQ_apdu_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnRLRQ_apdu_ModSetupTypes(void);
void PyAsnRLRQ_apdu_ModClear(PyObject *);
int PyAsnRLRQ_apdu_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RLRQ_apdu_PY_H_ */
