/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ACSE-1"
 */

#ifndef	_RLRQ_apdu_H_
#define	_RLRQ_apdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Release-request-reason.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Association_information;

/* RLRQ-apdu */
typedef struct RLRQ_apdu {
	Release_request_reason_t	*reason;	/* OPTIONAL */
	struct Association_information	*user_information;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLRQ_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLRQ_apdu;
extern asn_SEQUENCE_specifics_t asn_SPC_RLRQ_apdu_specs_1;
extern asn_TYPE_member_t asn_MBR_RLRQ_apdu_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Association-information.h"

#endif	/* _RLRQ_apdu_H_ */
#include <asn_internal.h>
