/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ScatteredAccessDescription_PY_H_
#define	_ScatteredAccessDescription_PY_H_


#include <ScatteredAccessDescription.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>
#include <VariableSpecification_Py.h>
#include <AlternateAccess_Py.h>
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ScatteredAccessDescription */
PyCompat_DEF_ANON_STRUCT(ScatteredAccessDescription_ScatteredAccessDescription_Member_ANON_2, ScatteredAccessDescription__ScatteredAccessDescription_Member);
PyCompat_DEF_TYPE(ScatteredAccessDescription_ScatteredAccessDescription_Member_ANON_2);
PyCompat_DEF_STRUCT(ScatteredAccessDescription);
PyCompat_DEF_TYPE(ScatteredAccessDescription);

/* Type Converters */
int PyAsnScatteredAccessDescription_ScatteredAccessDescription_Member_ANON_2_FromPython(PyObject *pObj, ScatteredAccessDescription_ScatteredAccessDescription_Member_ANON_2_t *pDst);
PyObject *PyAsnScatteredAccessDescription_ScatteredAccessDescription_Member_ANON_2_ToPython(ScatteredAccessDescription_ScatteredAccessDescription_Member_ANON_2_t *pSrc, PyObject *parent);
int PyAsnScatteredAccessDescription_FromPython(PyObject *pObj, ScatteredAccessDescription_t *pDst);
PyObject *PyAsnScatteredAccessDescription_ToPython(ScatteredAccessDescription_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnScatteredAccessDescription_ModSetupTypes(void);
void PyAsnScatteredAccessDescription_ModClear(PyObject *);
int PyAsnScatteredAccessDescription_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ScatteredAccessDescription_PY_H_ */
