/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_ScatteredAccessDescription_H_
#define	_ScatteredAccessDescription_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Identifier.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableSpecification;
struct AlternateAccess;

/* Forward definitions */
typedef struct ScatteredAccessDescription__ScatteredAccessDescription_Member {
	Identifier_t	*componentName;	/* OPTIONAL */
	struct VariableSpecification	*variableSpecification;
	struct AlternateAccess	*alternateAccess;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScatteredAccessDescription__ScatteredAccessDescription_Member;

/* ScatteredAccessDescription */
typedef struct ScatteredAccessDescription {
	A_SEQUENCE_OF(ScatteredAccessDescription__ScatteredAccessDescription_Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScatteredAccessDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScatteredAccessDescription;
extern asn_SET_OF_specifics_t asn_SPC_ScatteredAccessDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_ScatteredAccessDescription_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableSpecification.h"
#include "AlternateAccess.h"

#endif	/* _ScatteredAccessDescription_H_ */
#include <asn_internal.h>
