/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_StartUnitControl_Response_PY_H_
#define	_StartUnitControl_Response_PY_H_


#include <StartUnitControl-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StartUnitControl-Response */
PyCompat_DEF_STRUCT(StartUnitControl_Response);
PyCompat_DEF_TYPE(StartUnitControl_Response);

/* Type Converters */
static inline PyObject *PyAsnStartUnitControl_Response_ToPython(StartUnitControl_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnStartUnitControl_Response_FromPython(PyObject *pObj, StartUnitControl_Response_t *pDst)
{
	*pDst = (StartUnitControl_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnStartUnitControl_Response_ModSetupTypes(void);
void PyAsnStartUnitControl_Response_ModClear(PyObject *);
int PyAsnStartUnitControl_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _StartUnitControl_Response_PY_H_ */
