/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Start_Error_PY_H_
#define	_Start_Error_PY_H_


#include <Start-Error.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ProgramInvocationState_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Start-Error */
PyCompat_DEF_STRUCT(Start_Error);
PyCompat_DEF_TYPE(Start_Error);
PyCompat_DEF_ENUM(Start_Error);

/* Type Converters */
static inline PyObject *PyAsnStart_Error_ToPython(Start_Error_t *pSrc, PyObject *parent)
{
	return PyAsnProgramInvocationState_ToPython(pSrc, parent);
}
static inline int PyAsnStart_Error_FromPython(PyObject *pObj, Start_Error_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Start_Error, pObj, pDst);
	return PyAsnProgramInvocationState_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnStart_Error_ModSetupTypes(void);
void PyAsnStart_Error_ModClear(PyObject *);
int PyAsnStart_Error_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Start_Error_PY_H_ */
