/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_StartCount_H_
#define	_StartCount_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StartCount_PR {
	StartCount_PR_NOTHING,	/* No components present */
	StartCount_PR_noLimit,
	StartCount_PR_cycleCount,
	StartCount_PR_stepCount
} StartCount_PR;

/* StartCount */
typedef struct StartCount {
	StartCount_PR present;
	union StartCount_u {
		NULL_t	 noLimit;
		long	 cycleCount;
		long	 stepCount;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartCount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartCount;
extern asn_CHOICE_specifics_t asn_SPC_StartCount_specs_1;
extern asn_TYPE_member_t asn_MBR_StartCount_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _StartCount_H_ */
#include <asn_internal.h>
