/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Start_Request_H_
#define	_Start_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include "MMSString.h"
#include "EXTERNAL.h"
#include "EMBEDDED-PDV.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Start_Request__executionArgument_PR {
	Start_Request__executionArgument_PR_NOTHING,	/* No components present */
	Start_Request__executionArgument_PR_simpleString,
	Start_Request__executionArgument_PR_encodedString,
	Start_Request__executionArgument_PR_embeddedString
} Start_Request__executionArgument_PR;

/* Start-Request */
typedef struct Start_Request {
	Identifier_t	 programInvocationName;
	struct Start_Request__executionArgument {
		Start_Request__executionArgument_PR present;
		union Start_Request__executionArgument_u {
			MMSString_t	 simpleString;
			EXTERNAL_t	 encodedString;
			EMBEDDED_PDV_t	 embeddedString;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *executionArgument;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Start_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Start_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_Start_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_Start_Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Start_Request_H_ */
#include <asn_internal.h>
