/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Start_Response_PY_H_
#define	_Start_Response_PY_H_


#include <Start-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Start-Response */
PyCompat_DEF_STRUCT(Start_Response);
PyCompat_DEF_TYPE(Start_Response);

/* Type Converters */
static inline PyObject *PyAsnStart_Response_ToPython(Start_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnStart_Response_FromPython(PyObject *pObj, Start_Response_t *pDst)
{
	*pDst = (Start_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnStart_Response_ModSetupTypes(void);
void PyAsnStart_Response_ModClear(PyObject *);
int PyAsnStart_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Start_Response_PY_H_ */
