/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Status_Response_PY_H_
#define	_Status_Response_PY_H_


#include <Status-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <StatusResponse_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Status-Response */
PyCompat_DEF_STRUCT(Status_Response);
PyCompat_DEF_TYPE(Status_Response);
PyCompat_DEF_ENUM(Status_Response);

/* Type Converters */
static inline PyObject *PyAsnStatus_Response_ToPython(Status_Response_t *pSrc, PyObject *parent)
{
	return PyAsnStatusResponse_ToPython(pSrc, parent);
}
static inline int PyAsnStatus_Response_FromPython(PyObject *pObj, Status_Response_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Status_Response, pObj, pDst);
	return PyAsnStatusResponse_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnStatus_Response_ModSetupTypes(void);
void PyAsnStatus_Response_ModClear(PyObject *);
int PyAsnStatus_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Status_Response_PY_H_ */
