/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <StopUnitControl-Request.h>
/*
 * This type is implemented using Identifier,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_StopUnitControl_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (26 << 2))
};
asn_TYPE_descriptor_t asn_DEF_StopUnitControl_Request = {
	"StopUnitControl-Request",
	"StopUnitControl-Request",
	&asn_OP_VisibleString,
	asn_DEF_StopUnitControl_Request_tags_1,
	sizeof(asn_DEF_StopUnitControl_Request_tags_1)
		/sizeof(asn_DEF_StopUnitControl_Request_tags_1[0]), /* 1 */
	asn_DEF_StopUnitControl_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_StopUnitControl_Request_tags_1)
		/sizeof(asn_DEF_StopUnitControl_Request_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		VisibleString_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

