/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Stop_Request_PY_H_
#define	_Stop_Request_PY_H_


#include <Stop-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Stop-Request */
PyCompat_DEF_STRUCT(Stop_Request);
PyCompat_DEF_TYPE(Stop_Request);

/* Type Converters */
int PyAsnStop_Request_FromPython(PyObject *pObj, Stop_Request_t *pDst);
PyObject *PyAsnStop_Request_ToPython(Stop_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnStop_Request_ModSetupTypes(void);
void PyAsnStop_Request_ModClear(PyObject *);
int PyAsnStop_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Stop_Request_PY_H_ */
