/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_StoreUnitControlToFile_Request_H_
#define	_StoreUnitControlToFile_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileName;
struct ApplicationReference;

/* StoreUnitControlToFile-Request */
typedef struct StoreUnitControlToFile_Request {
	Identifier_t	 unitControlName;
	struct FileName	*fileName;
	struct ApplicationReference	*thirdParty;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StoreUnitControlToFile_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StoreUnitControlToFile_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_StoreUnitControlToFile_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_StoreUnitControlToFile_Request_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileName.h"
#include "ApplicationReference.h"

#endif	/* _StoreUnitControlToFile_Request_H_ */
#include <asn_internal.h>
