/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TakeControl_Request_PY_H_
#define	_TakeControl_Request_PY_H_


#include <TakeControl-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Identifier_Py.h>
#include <Priority_Py.h>
#include <Unsigned32_Py.h>
#include <Unsigned32_Py.h>
#include <ApplicationReference_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TakeControl-Request */
PyCompat_DEF_STRUCT(TakeControl_Request);
PyCompat_DEF_TYPE(TakeControl_Request);

/* Type Converters */
int PyAsnTakeControl_Request_FromPython(PyObject *pObj, TakeControl_Request_t *pDst);
PyObject *PyAsnTakeControl_Request_ToPython(TakeControl_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnTakeControl_Request_ModSetupTypes(void);
void PyAsnTakeControl_Request_ModClear(PyObject *);
int PyAsnTakeControl_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TakeControl_Request_PY_H_ */
