/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TakeControl_Response_PY_H_
#define	_TakeControl_Response_PY_H_


#include <TakeControl-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TakeControl-Response */
PyCompat_DEF_STRUCT(TakeControl_Response);
PyCompat_DEF_TYPE(TakeControl_Response);
PyCompat_DEF_ENUM(TakeControl_Response_PRESENT);

/* Type Converters */
int PyAsnTakeControl_Response_FromPython(PyObject *pObj, TakeControl_Response_t *pDst);
PyObject *PyAsnTakeControl_Response_ToPython(TakeControl_Response_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnTakeControl_Response_ModSetupTypes(void);
void PyAsnTakeControl_Response_ModClear(PyObject *);
int PyAsnTakeControl_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TakeControl_Response_PY_H_ */
