/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TakeControl_Response_H_
#define	_TakeControl_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "Identifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TakeControl_Response_PR {
	TakeControl_Response_PR_NOTHING,	/* No components present */
	TakeControl_Response_PR_noResult,
	TakeControl_Response_PR_namedToken
} TakeControl_Response_PR;

/* TakeControl-Response */
typedef struct TakeControl_Response {
	TakeControl_Response_PR present;
	union TakeControl_Response_u {
		NULL_t	 noResult;
		Identifier_t	 namedToken;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TakeControl_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TakeControl_Response;
extern asn_CHOICE_specifics_t asn_SPC_TakeControl_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_TakeControl_Response_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TakeControl_Response_H_ */
#include <asn_internal.h>
