/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TerminateUploadSequence_Response_PY_H_
#define	_TerminateUploadSequence_Response_PY_H_


#include <TerminateUploadSequence-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TerminateUploadSequence-Response */
PyCompat_DEF_STRUCT(TerminateUploadSequence_Response);
PyCompat_DEF_TYPE(TerminateUploadSequence_Response);

/* Type Converters */
static inline PyObject *PyAsnTerminateUploadSequence_Response_ToPython(TerminateUploadSequence_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnTerminateUploadSequence_Response_FromPython(PyObject *pObj, TerminateUploadSequence_Response_t *pDst)
{
	*pDst = (TerminateUploadSequence_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnTerminateUploadSequence_Response_ModSetupTypes(void);
void PyAsnTerminateUploadSequence_Response_ModClear(PyObject *);
int PyAsnTerminateUploadSequence_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TerminateUploadSequence_Response_PY_H_ */
