/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Transitions_H_
#define	_Transitions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Transitions {
	Transitions_idle_to_disabled	= 0,
	Transitions_active_to_disabled	= 1,
	Transitions_disabled_to_idle	= 2,
	Transitions_active_to_idle	= 3,
	Transitions_disabled_to_active	= 4,
	Transitions_idle_to_active	= 5,
	Transitions_any_to_deleted	= 6
} e_Transitions;

/* Transitions */
typedef BIT_STRING_t	 Transitions_t;

/* Implementation */
extern asn_jer_constraints_t asn_JER_type_Transitions_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Transitions;
asn_struct_free_f Transitions_free;
asn_struct_print_f Transitions_print;
asn_constr_check_f Transitions_constraint;
ber_type_decoder_f Transitions_decode_ber;
der_type_encoder_f Transitions_encode_der;
xer_type_decoder_f Transitions_decode_xer;
xer_type_encoder_f Transitions_encode_xer;
jer_type_encoder_f Transitions_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Transitions_H_ */
#include <asn_internal.h>
