/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TriggerEvent_Request_PY_H_
#define	_TriggerEvent_Request_PY_H_


#include <TriggerEvent-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Priority_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TriggerEvent-Request */
PyCompat_DEF_STRUCT(TriggerEvent_Request);
PyCompat_DEF_TYPE(TriggerEvent_Request);

/* Type Converters */
int PyAsnTriggerEvent_Request_FromPython(PyObject *pObj, TriggerEvent_Request_t *pDst);
PyObject *PyAsnTriggerEvent_Request_ToPython(TriggerEvent_Request_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnTriggerEvent_Request_ModSetupTypes(void);
void PyAsnTriggerEvent_Request_ModClear(PyObject *);
int PyAsnTriggerEvent_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TriggerEvent_Request_PY_H_ */
