/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TriggerEvent_Request_H_
#define	_TriggerEvent_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Priority.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ObjectName;

/* TriggerEvent-Request */
typedef struct TriggerEvent_Request {
	struct ObjectName	*eventConditionName;
	Priority_t	*priority;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TriggerEvent_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TriggerEvent_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_TriggerEvent_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_TriggerEvent_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ObjectName.h"

#endif	/* _TriggerEvent_Request_H_ */
#include <asn_internal.h>
