/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TriggerEvent_Response_PY_H_
#define	_TriggerEvent_Response_PY_H_


#include <TriggerEvent-Response.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TriggerEvent-Response */
PyCompat_DEF_STRUCT(TriggerEvent_Response);
PyCompat_DEF_TYPE(TriggerEvent_Response);

/* Type Converters */
static inline PyObject *PyAsnTriggerEvent_Response_ToPython(TriggerEvent_Response_t *pSrc, PyObject *parent)
{
	return PyCompatNull_FromLong(*pSrc);
}
static inline int PyAsnTriggerEvent_Response_FromPython(PyObject *pObj, TriggerEvent_Response_t *pDst)
{
	*pDst = (TriggerEvent_Response_t)PyCompatNull_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnTriggerEvent_Response_ModSetupTypes(void);
void PyAsnTriggerEvent_Response_ModClear(PyObject *);
int PyAsnTriggerEvent_Response_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TriggerEvent_Response_PY_H_ */
