/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_TypeSpecification_PY_H_
#define	_TypeSpecification_PY_H_


#include <TypeSpecification.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <TypeDescription_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TypeSpecification */
PyCompat_DEF_STRUCT(TypeSpecification);
PyCompat_DEF_TYPE(TypeSpecification);
PyCompat_DEF_ENUM(TypeSpecification_PRESENT);

/* Type Converters */
int PyAsnTypeSpecification_FromPython(PyObject *pObj, TypeSpecification_t *pDst);
PyObject *PyAsnTypeSpecification_ToPython(TypeSpecification_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnTypeSpecification_ModSetupTypes(void);
void PyAsnTypeSpecification_ModClear(PyObject *);
int PyAsnTypeSpecification_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _TypeSpecification_PY_H_ */
