/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_UnconfirmedService_PY_H_
#define	_UnconfirmedService_PY_H_


#include <UnconfirmedService.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <InformationReport_Py.h>
#include <UnsolicitedStatus_Py.h>
#include <EventNotification_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnconfirmedService */
PyCompat_DEF_STRUCT(UnconfirmedService);
PyCompat_DEF_TYPE(UnconfirmedService);
PyCompat_DEF_ENUM(UnconfirmedService_PRESENT);

/* Type Converters */
int PyAsnUnconfirmedService_FromPython(PyObject *pObj, UnconfirmedService_t *pDst);
PyObject *PyAsnUnconfirmedService_ToPython(UnconfirmedService_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnUnconfirmedService_ModSetupTypes(void);
void PyAsnUnconfirmedService_ModClear(PyObject *);
int PyAsnUnconfirmedService_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _UnconfirmedService_PY_H_ */
