/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Unconfirmed_Detail_H_
#define	_Unconfirmed_Detail_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Unconfirmed_Detail_PR {
	Unconfirmed_Detail_PR_NOTHING,	/* No components present */
	Unconfirmed_Detail_PR_otherRequests,
	Unconfirmed_Detail_PR_eventNotification
} Unconfirmed_Detail_PR;

/* Forward declarations */
struct CS_EventNotification;

/* Unconfirmed-Detail */
typedef struct Unconfirmed_Detail {
	Unconfirmed_Detail_PR present;
	union Unconfirmed_Detail_u {
		NULL_t	 otherRequests;
		struct CS_EventNotification	*eventNotification;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Unconfirmed_Detail_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Unconfirmed_Detail;
extern asn_CHOICE_specifics_t asn_SPC_Unconfirmed_Detail_specs_1;
extern asn_TYPE_member_t asn_MBR_Unconfirmed_Detail_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CS-EventNotification.h"

#endif	/* _Unconfirmed_Detail_H_ */
#include <asn_internal.h>
