/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_UnconfirmedService_H_
#define	_UnconfirmedService_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnconfirmedService_PR {
	UnconfirmedService_PR_NOTHING,	/* No components present */
	UnconfirmedService_PR_informationReport,
	UnconfirmedService_PR_unsolicitedStatus,
	UnconfirmedService_PR_eventNotification
} UnconfirmedService_PR;

/* Forward declarations */
struct InformationReport;
struct UnsolicitedStatus;
struct EventNotification;
struct StatusResponse;

/* UnconfirmedService */
typedef struct UnconfirmedService {
	UnconfirmedService_PR present;
	union UnconfirmedService_u {
		struct InformationReport	*informationReport;
		struct StatusResponse	*unsolicitedStatus;
		struct EventNotification	*eventNotification;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnconfirmedService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnconfirmedService;
extern asn_CHOICE_specifics_t asn_SPC_UnconfirmedService_specs_1;
extern asn_TYPE_member_t asn_MBR_UnconfirmedService_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InformationReport.h"
#include "UnsolicitedStatus.h"
#include "EventNotification.h"

#endif	/* _UnconfirmedService_H_ */
#include <asn_internal.h>
