/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Unconfirmed_Detail_PY_H_
#define	_Unconfirmed_Detail_PY_H_


#include <Unconfirmed-Detail.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <CS-EventNotification_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Unconfirmed-Detail */
PyCompat_DEF_STRUCT(Unconfirmed_Detail);
PyCompat_DEF_TYPE(Unconfirmed_Detail);
PyCompat_DEF_ENUM(Unconfirmed_Detail_PRESENT);

/* Type Converters */
int PyAsnUnconfirmed_Detail_FromPython(PyObject *pObj, Unconfirmed_Detail_t *pDst);
PyObject *PyAsnUnconfirmed_Detail_ToPython(Unconfirmed_Detail_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnUnconfirmed_Detail_ModSetupTypes(void);
void PyAsnUnconfirmed_Detail_ModClear(PyObject *);
int PyAsnUnconfirmed_Detail_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Unconfirmed_Detail_PY_H_ */
