/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Unsigned8_H_
#define	_Unsigned8_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Unsigned8 */
typedef long	 Unsigned8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Unsigned8;
asn_struct_free_f Unsigned8_free;
asn_struct_print_f Unsigned8_print;
asn_constr_check_f Unsigned8_constraint;
ber_type_decoder_f Unsigned8_decode_ber;
der_type_encoder_f Unsigned8_encode_der;
xer_type_decoder_f Unsigned8_decode_xer;
xer_type_encoder_f Unsigned8_encode_xer;
jer_type_encoder_f Unsigned8_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Unsigned8_H_ */
#include <asn_internal.h>
