/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_UnsolicitedStatus_PY_H_
#define	_UnsolicitedStatus_PY_H_


#include <UnsolicitedStatus.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <StatusResponse_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnsolicitedStatus */
PyCompat_DEF_STRUCT(UnsolicitedStatus);
PyCompat_DEF_TYPE(UnsolicitedStatus);
PyCompat_DEF_ENUM(UnsolicitedStatus);

/* Type Converters */
static inline PyObject *PyAsnUnsolicitedStatus_ToPython(UnsolicitedStatus_t *pSrc, PyObject *parent)
{
	return PyAsnStatusResponse_ToPython(pSrc, parent);
}
static inline int PyAsnUnsolicitedStatus_FromPython(PyObject *pObj, UnsolicitedStatus_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(UnsolicitedStatus, pObj, pDst);
	return PyAsnStatusResponse_FromPython(pObj, pDst);
}

/* Module Initializers */
int PyAsnUnsolicitedStatus_ModSetupTypes(void);
void PyAsnUnsolicitedStatus_ModClear(PyObject *);
int PyAsnUnsolicitedStatus_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _UnsolicitedStatus_PY_H_ */
