/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_UploadSegment_Response_H_
#define	_UploadSegment_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LoadData;

/* UploadSegment-Response */
typedef struct UploadSegment_Response {
	struct LoadData	*loadData;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UploadSegment_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UploadSegment_Response;
extern asn_SEQUENCE_specifics_t asn_SPC_UploadSegment_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_UploadSegment_Response_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LoadData.h"

#endif	/* _UploadSegment_Response_H_ */
#include <asn_internal.h>
