/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_VariableSpecification_PY_H_
#define	_VariableSpecification_PY_H_


#include <VariableSpecification.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Address_Py.h>
#include <TypeSpecification_Py.h>
#include <py_application.h>
#include <py_convert.h>
#include <ObjectName_Py.h>
#include <Address_Py.h>
#include <ScatteredAccessDescription_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VariableSpecification */
PyCompat_DEF_ANON_STRUCT(VariableSpecification_variableDescription_ANON_4, VariableSpecification__variableDescription);
PyCompat_DEF_TYPE(VariableSpecification_variableDescription_ANON_4);
PyCompat_DEF_STRUCT(VariableSpecification);
PyCompat_DEF_TYPE(VariableSpecification);
PyCompat_DEF_ENUM(VariableSpecification_PRESENT);

/* Type Converters */
int PyAsnVariableSpecification_variableDescription_ANON_4_FromPython(PyObject *pObj, VariableSpecification_variableDescription_ANON_4_t *pDst);
PyObject *PyAsnVariableSpecification_variableDescription_ANON_4_ToPython(VariableSpecification_variableDescription_ANON_4_t *pSrc, PyObject *parent);
int PyAsnVariableSpecification_FromPython(PyObject *pObj, VariableSpecification_t *pDst);
PyObject *PyAsnVariableSpecification_ToPython(VariableSpecification_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnVariableSpecification_ModSetupTypes(void);
void PyAsnVariableSpecification_ModClear(PyObject *);
int PyAsnVariableSpecification_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _VariableSpecification_PY_H_ */
