/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_VMDReset_Request_PY_H_
#define	_VMDReset_Request_PY_H_


#include <VMDReset-Request.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VMDReset-Request */
PyCompat_DEF_STRUCT(VMDReset_Request);
PyCompat_DEF_TYPE(VMDReset_Request);

/* Type Converters */
static inline PyObject *PyAsnVMDReset_Request_ToPython(VMDReset_Request_t *pSrc, PyObject *parent)
{
	return PyCompatBool_FromLong(*pSrc);
}
static inline int PyAsnVMDReset_Request_FromPython(PyObject *pObj, VMDReset_Request_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(VMDReset_Request, pObj, pDst);
	*pDst = (VMDReset_Request_t)PyCompatBool_AsLong(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnVMDReset_Request_ModSetupTypes(void);
void PyAsnVMDReset_Request_ModClear(PyObject *);
int PyAsnVMDReset_Request_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _VMDReset_Request_PY_H_ */
