/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#include <WriteJournal-Request.h>
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry __attribute__((weak, alias("asn_DEF_listOfJournalEntry_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry_3;
static asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry;
__attribute__((constructor)) static void asn_DEF_listOfJournalEntry_3_alias_init(void) {
	asn_DEF_listOfJournalEntry = asn_DEF_listOfJournalEntry_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
static asn_TYPE_member_t asn_MBR_WriteJournal_Request__listOfJournalEntry_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntryContent,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"Member"
		},
};
static const ber_tlv_tag_t asn_DEF_listOfJournalEntry_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfJournalEntry_specs_3 = {
	sizeof(struct WriteJournal_Request__listOfJournalEntry),
	offsetof(struct WriteJournal_Request__listOfJournalEntry, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfJournalEntry_3 = {
	"listOfJournalEntry",
	"listOfJournalEntry",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfJournalEntry_tags_3,
	sizeof(asn_DEF_listOfJournalEntry_tags_3)
		/sizeof(asn_DEF_listOfJournalEntry_tags_3[0]) - 1, /* 1 */
	asn_DEF_listOfJournalEntry_tags_3,	/* Same as above */
	sizeof(asn_DEF_listOfJournalEntry_tags_3)
		/sizeof(asn_DEF_listOfJournalEntry_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_WriteJournal_Request__listOfJournalEntry_3,
	1,	/* Single element */
	&asn_SPC_listOfJournalEntry_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_WriteJournal_Request_1[] = {
	{ ATF_POINTER, 0, offsetof(struct WriteJournal_Request, journalName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ObjectName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"journalName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WriteJournal_Request, listOfJournalEntry),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listOfJournalEntry_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"listOfJournalEntry"
		},
};
static const ber_tlv_tag_t asn_DEF_WriteJournal_Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WriteJournal_Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* journalName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* listOfJournalEntry */
};
asn_SEQUENCE_specifics_t asn_SPC_WriteJournal_Request_specs_1 = {
	sizeof(struct WriteJournal_Request),
	offsetof(struct WriteJournal_Request, _asn_ctx),
	asn_MAP_WriteJournal_Request_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WriteJournal_Request = {
	"WriteJournal-Request",
	"WriteJournal-Request",
	&asn_OP_SEQUENCE,
	asn_DEF_WriteJournal_Request_tags_1,
	sizeof(asn_DEF_WriteJournal_Request_tags_1)
		/sizeof(asn_DEF_WriteJournal_Request_tags_1[0]), /* 1 */
	asn_DEF_WriteJournal_Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_WriteJournal_Request_tags_1)
		/sizeof(asn_DEF_WriteJournal_Request_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_WriteJournal_Request_1,
	2,	/* Elements count */
	&asn_SPC_WriteJournal_Request_specs_1	/* Additional specs */
};

