/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Write_Request_H_
#define	_Write_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariableAccessSpecification;
struct Data;

/* Write-Request */
typedef struct Write_Request {
	struct VariableAccessSpecification	*variableAccessSpecification;
	struct Write_Request__listOfData {
		A_SEQUENCE_OF(struct Data) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Write_Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Write_Request;
extern asn_SEQUENCE_specifics_t asn_SPC_Write_Request_specs_1;
extern asn_TYPE_member_t asn_MBR_Write_Request_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariableAccessSpecification.h"
#include "Data.h"

#endif	/* _Write_Request_H_ */
#include <asn_internal.h>
