/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO-9506-MMS-1"
 */

#ifndef	_Write_Response_H_
#define	_Write_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "DataAccessError.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Write_Response__Write_Response_Member_PR {
	Write_Response__Write_Response_Member_PR_NOTHING,	/* No components present */
	Write_Response__Write_Response_Member_PR_failure,
	Write_Response__Write_Response_Member_PR_success
} Write_Response__Write_Response_Member_PR;

/* Forward definitions */
typedef struct Write_Response__Write_Response_Member {
	Write_Response__Write_Response_Member_PR present;
	union Write_Response__Write_Response_Member_u {
		DataAccessError_t	 failure;
		NULL_t	 success;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Write_Response__Write_Response_Member;

/* Write-Response */
typedef struct Write_Response {
	A_SEQUENCE_OF(Write_Response__Write_Response_Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Write_Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Write_Response;
extern asn_SET_OF_specifics_t asn_SPC_Write_Response_specs_1;
extern asn_TYPE_member_t asn_MBR_Write_Response_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Write_Response_H_ */
#include <asn_internal.h>
