/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Abort_type_H_
#define	_Abort_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Abort_type_PR {
	Abort_type_PR_NOTHING,	/* No components present */
	Abort_type_PR_aru_ppdu,
	Abort_type_PR_arp_ppdu
} Abort_type_PR;

/* Forward declarations */
struct ARU_PPDU;
struct ARP_PPDU;

/* Abort-type */
typedef struct Abort_type {
	Abort_type_PR present;
	union Abort_type_u {
		struct ARU_PPDU	*aru_ppdu;
		struct ARP_PPDU	*arp_ppdu;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Abort_type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Abort_type;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ARU-PPDU.h"
#include "ARP-PPDU.h"

#endif	/* _Abort_type_H_ */
#include <asn_internal.h>
