/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_ACA_PPDU_H_
#define	_ACA_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Presentation_context_addition_result_list;
struct Presentation_context_deletion_result_list;
struct User_data;
struct Result_list;

/* ACA-PPDU */
typedef struct ACA_PPDU {
	struct Result_list	*presentation_context_addition_result_list;	/* OPTIONAL */
	struct Presentation_context_deletion_result_list	*presentation_context_deletion_result_list;	/* OPTIONAL */
	struct User_data	*user_data;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ACA_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACA_PPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_ACA_PPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_ACA_PPDU_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentation-context-addition-result-list.h"
#include "Presentation-context-deletion-result-list.h"
#include "User-data.h"

#endif	/* _ACA_PPDU_H_ */
#include <asn_internal.h>
