/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_ARP_PPDU_PY_H_
#define	_ARP_PPDU_PY_H_


#include <ARP-PPDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Abort-reason_Py.h>
#include <Event-identifier_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ARP-PPDU */
PyCompat_DEF_STRUCT(ARP_PPDU);
PyCompat_DEF_TYPE(ARP_PPDU);

/* Type Converters */
int PyAsnARP_PPDU_FromPython(PyObject *pObj, ARP_PPDU_t *pDst);
PyObject *PyAsnARP_PPDU_ToPython(ARP_PPDU_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnARP_PPDU_ModSetupTypes(void);
void PyAsnARP_PPDU_ModClear(PyObject *);
int PyAsnARP_PPDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _ARP_PPDU_PY_H_ */
