/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_CPR_PPDU_H_
#define	_CPR_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Protocol-version.h"
#include "Responding-presentation-selector.h"
#include "Default-context-result.h"
#include "Provider-reason.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CPR_PPDU_PR {
	CPR_PPDU_PR_NOTHING,	/* No components present */
	CPR_PPDU_PR_normal_mode_parameters
} CPR_PPDU_PR;

/* Forward declarations */
struct Presentation_context_definition_result_list;
struct User_data;
struct Result_list;

/* CPR-PPDU */
typedef struct CPR_PPDU {
	CPR_PPDU_PR present;
	union CPR_PPDU_u {
		struct CPR_PPDU__normal_mode_parameters {
			Protocol_version_t	*protocol_version;	/* DEFAULT {version-1} */
			Responding_presentation_selector_t	*responding_presentation_selector;	/* OPTIONAL */
			struct Result_list	*presentation_context_definition_result_list;	/* OPTIONAL */
			Default_context_result_t	*default_context_result;	/* OPTIONAL */
			Provider_reason_t	*provider_reason;	/* OPTIONAL */
			struct User_data	*user_data;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} normal_mode_parameters;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CPR_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CPR_PPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentation-context-definition-result-list.h"
#include "User-data.h"

#endif	/* _CPR_PPDU_H_ */
#include <asn_internal.h>
