/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Presentation_context_identifier_H_
#define	_Presentation_context_identifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Presentation-context-identifier */
typedef long	 Presentation_context_identifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Presentation_context_identifier;
asn_struct_free_f Presentation_context_identifier_free;
asn_struct_print_f Presentation_context_identifier_print;
asn_constr_check_f Presentation_context_identifier_constraint;
ber_type_decoder_f Presentation_context_identifier_decode_ber;
der_type_encoder_f Presentation_context_identifier_encode_der;
xer_type_decoder_f Presentation_context_identifier_decode_xer;
xer_type_encoder_f Presentation_context_identifier_encode_xer;
jer_type_encoder_f Presentation_context_identifier_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Presentation_context_identifier_H_ */
#include <asn_internal.h>
