/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Presentation_context_deletion_list_H_
#define	_Presentation_context_deletion_list_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Presentation-context-identifier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Presentation-context-deletion-list */
typedef struct Presentation_context_deletion_list {
	A_SEQUENCE_OF(Presentation_context_identifier_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Presentation_context_deletion_list_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Presentation_context_deletion_list;
extern asn_SET_OF_specifics_t asn_SPC_Presentation_context_deletion_list_specs_1;
extern asn_TYPE_member_t asn_MBR_Presentation_context_deletion_list_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Presentation_context_deletion_list_H_ */
#include <asn_internal.h>
