/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Presentation_context_identifier_PY_H_
#define	_Presentation_context_identifier_PY_H_


#include <Presentation-context-identifier.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Presentation-context-identifier */
PyCompat_DEF_STRUCT(Presentation_context_identifier);
PyCompat_DEF_TYPE(Presentation_context_identifier);

/* Type Converters */
static inline PyObject *PyAsnPresentation_context_identifier_ToPython(Presentation_context_identifier_t *pSrc, PyObject *parent)
{
	return PyCompatLong_FromSsize_t(*pSrc);
}
static inline int PyAsnPresentation_context_identifier_FromPython(PyObject *pObj, Presentation_context_identifier_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Presentation_context_identifier, pObj, pDst);
	PyCompatLong_Check(pObj, -1);
	*pDst = (Presentation_context_identifier_t)PyCompatLong_AsSsize_t(pObj);
	return 0;
}

/* Module Initializers */
int PyAsnPresentation_context_identifier_ModSetupTypes(void);
void PyAsnPresentation_context_identifier_ModClear(PyObject *);
int PyAsnPresentation_context_identifier_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Presentation_context_identifier_PY_H_ */
