/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Presentation_requirements_H_
#define	_Presentation_requirements_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Presentation_requirements {
	Presentation_requirements_context_management	= 0,
	Presentation_requirements_restoration	= 1
} e_Presentation_requirements;

/* Presentation-requirements */
typedef BIT_STRING_t	 Presentation_requirements_t;

/* Implementation */
extern asn_jer_constraints_t asn_JER_type_Presentation_requirements_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Presentation_requirements;
asn_struct_free_f Presentation_requirements_free;
asn_struct_print_f Presentation_requirements_print;
asn_constr_check_f Presentation_requirements_constraint;
ber_type_decoder_f Presentation_requirements_decode_ber;
der_type_encoder_f Presentation_requirements_encode_der;
xer_type_decoder_f Presentation_requirements_decode_xer;
xer_type_encoder_f Presentation_requirements_encode_xer;
jer_type_encoder_f Presentation_requirements_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Presentation_requirements_H_ */
#include <asn_internal.h>
