/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Protocol_version_H_
#define	_Protocol_version_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Protocol_version {
	Protocol_version_version_1	= 0
} e_Protocol_version;

/* Protocol-version */
typedef BIT_STRING_t	 Protocol_version_t;

/* Implementation */
extern asn_jer_constraints_t asn_JER_type_Protocol_version_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Protocol_version;
asn_struct_free_f Protocol_version_free;
asn_struct_print_f Protocol_version_print;
asn_constr_check_f Protocol_version_constraint;
ber_type_decoder_f Protocol_version_decode_ber;
der_type_encoder_f Protocol_version_encode_der;
xer_type_decoder_f Protocol_version_decode_xer;
xer_type_encoder_f Protocol_version_encode_xer;
jer_type_encoder_f Protocol_version_encode_jer;

#ifdef __cplusplus
}
#endif

#endif	/* _Protocol_version_H_ */
#include <asn_internal.h>
