/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Provider_reason_PY_H_
#define	_Provider_reason_PY_H_


#include <Provider-reason.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Provider-reason */
PyCompat_DEF_STRUCT(Provider_reason);
PyCompat_DEF_TYPE(Provider_reason);
PyCompat_DEF_ENUM(Provider_reason);

/* Type Converters */
static inline int PyAsnProvider_reason_FromPython(PyObject *pObj, Provider_reason_t *pDst)
{
	PY_IMPL_FROMPY_COMPAT(Provider_reason, pObj, pDst);
	return PyCompatEnum_FromObject(pObj, (void *)pDst, 0);
}
static inline PyObject *PyAsnProvider_reason_ToPython(Provider_reason_t *pSrc, PyObject *parent)
{
	return PyCompatEnum_FromSsize_t(PyAsnEnumProvider_reason_Type, *pSrc);
}

/* Module Initializers */
int PyAsnProvider_reason_ModSetupTypes(void);
void PyAsnProvider_reason_ModClear(PyObject *);
int PyAsnProvider_reason_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _Provider_reason_PY_H_ */
