/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_RS_PPDU_H_
#define	_RS_PPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Presentation_context_identifier_list;
struct User_data;

/* RS-PPDU */
typedef struct RS_PPDU {
	struct Presentation_context_identifier_list	*presentation_context_identifier_list;	/* OPTIONAL */
	struct User_data	*user_data;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RS_PPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RS_PPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentation-context-identifier-list.h"
#include "User-data.h"

#endif	/* _RS_PPDU_H_ */
#include <asn_internal.h>
