/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_RSA_PPDU_PY_H_
#define	_RSA_PPDU_PY_H_


#include <RSA-PPDU.h>

/* Including dependencies */
#include <py_application.h>
#include <py_convert.h>
#include <Presentation-context-identifier-list_Py.h>
#include <User-data_Py.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSA-PPDU */
PyCompat_DEF_STRUCT(RSA_PPDU);
PyCompat_DEF_TYPE(RSA_PPDU);

/* Type Converters */
int PyAsnRSA_PPDU_FromPython(PyObject *pObj, RSA_PPDU_t *pDst);
PyObject *PyAsnRSA_PPDU_ToPython(RSA_PPDU_t *pSrc, PyObject *parent);

/* Module Initializers */
int PyAsnRSA_PPDU_ModSetupTypes(void);
void PyAsnRSA_PPDU_ModClear(PyObject *);
int PyAsnRSA_PPDU_ModInit(PyObject *);

#ifdef __cplusplus
}
#endif

#endif	/* _RSA_PPDU_PY_H_ */
