/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_Typed_data_type_H_
#define	_Typed_data_type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Typed_data_type_PR {
	Typed_data_type_PR_NOTHING,	/* No components present */
	Typed_data_type_PR_acPPDU,
	Typed_data_type_PR_acaPPDU,
	Typed_data_type_PR_ttdPPDU
} Typed_data_type_PR;

/* Forward declarations */
struct AC_PPDU;
struct ACA_PPDU;
struct User_data;

/* Typed-data-type */
typedef struct Typed_data_type {
	Typed_data_type_PR present;
	union Typed_data_type_u {
		struct AC_PPDU	*acPPDU;
		struct ACA_PPDU	*acaPPDU;
		struct User_data	*ttdPPDU;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Typed_data_type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Typed_data_type;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AC-PPDU.h"
#include "ACA-PPDU.h"
#include "User-data.h"

#endif	/* _Typed_data_type_H_ */
#include <asn_internal.h>
