/*
 * Generated by asn1c-bc17e5a1 (https://github.com/MatrixEditor/asn1c-bindings/issues)
 * From ASN.1 module "ISO8823-PRESENTATION"
 */

#ifndef	_User_data_H_
#define	_User_data_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Simply-encoded-data.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum User_data_PR {
	User_data_PR_NOTHING,	/* No components present */
	User_data_PR_simply_encoded_data,
	User_data_PR_fully_encoded_data
} User_data_PR;

/* Forward declarations */
struct Fully_encoded_data;

/* User-data */
typedef struct User_data {
	User_data_PR present;
	union User_data_u {
		Simply_encoded_data_t	 simply_encoded_data;
		struct Fully_encoded_data	*fully_encoded_data;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} User_data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_User_data;
extern asn_CHOICE_specifics_t asn_SPC_User_data_specs_1;
extern asn_TYPE_member_t asn_MBR_User_data_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Fully-encoded-data.h"

#endif	/* _User_data_H_ */
#include <asn_internal.h>
