name: "CI: Build and Deploy Docs"

on:
  workflow_dispatch:
  push:
    branches: [master]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # Documentation uses the most stable Python version
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements-docs.txt

      - name: Install Package
        run: |
          pip install -v .

      - name: Build docs
        run: |
          cd docs
          make html
          touch build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html